import type {
  HistoricalMemoryRecord,
  HistoricalMemoryStatus,
} from "@/lib/historical-memory"
import type { SignalDirection, SignalOutcomeStatus } from "@/lib/signal-evaluation"
import type { TrackingWindowId } from "@/lib/signal-tracking"

export const PATTERN_SCHEMA_VERSION = 1 as const

export const PATTERN_STATUSES = [
  "DRAFT",
  "CANDIDATE",
  "VALIDATED",
  "REJECTED",
  "ARCHIVED",
] as const

export type PatternStatus = typeof PATTERN_STATUSES[number]

export interface PatternDateRange {
  readonly from: string
  readonly to: string
}

export interface PatternScope {
  readonly symbol: string | null
  readonly timeframe: string | null
  readonly direction: SignalDirection | null
  readonly evaluationWindow: TrackingWindowId | null
  readonly outcomeStatus: SignalOutcomeStatus | null
  readonly dateRange: PatternDateRange | null
}

export interface PatternIdentity {
  readonly patternId: string
  readonly patternVersion: number
  readonly scope: PatternScope
  readonly evidenceSetHash: string
}

export interface PatternEvidence {
  readonly memoryId: string
  readonly eventId: string
  readonly outcomeId: string
  readonly memoryStatus: Exclude<HistoricalMemoryStatus, "CREATED">
  readonly memoryCreatedAt: string
  readonly evaluatedAt: string
  readonly symbol: string
  readonly timeframe: string
  readonly direction: SignalDirection
  readonly evaluationWindow: TrackingWindowId
  readonly outcomeStatus: SignalOutcomeStatus
}

export interface PatternDrawdownProfile {
  readonly averageDrawdown: number
  readonly medianDrawdown: number
  readonly maximumDrawdown: number
}

export interface PatternWindowDistributionEntry {
  readonly evaluationWindow: TrackingWindowId
  readonly count: number
}

export interface PatternDirectionDistributionEntry {
  readonly direction: SignalDirection
  readonly count: number
}

export interface PatternMetricSummary {
  readonly sampleSize: number
  readonly winRate: number
  readonly averageReturnPercent: number
  readonly medianReturnPercent: number
  readonly averageMaxFavorableExcursion: number
  readonly averageMaxAdverseExcursion: number
  readonly drawdownProfile: PatternDrawdownProfile
  readonly windowDistribution: readonly PatternWindowDistributionEntry[]
  readonly directionDistribution: readonly PatternDirectionDistributionEntry[]
}

export interface PatternRecord {
  readonly schemaVersion: typeof PATTERN_SCHEMA_VERSION
  readonly identity: PatternIdentity
  readonly status: PatternStatus
  readonly createdAt: string
  /** Caller-supplied interpretation; never generated by this runtime. */
  readonly interpretation: string
  readonly evidence: readonly PatternEvidence[]
  readonly metricSummary: PatternMetricSummary
}

export interface PatternQuery {
  readonly symbol?: string
  readonly timeframe?: string
  readonly direction?: SignalDirection
  readonly evaluationWindow?: TrackingWindowId
  readonly outcomeStatus?: SignalOutcomeStatus
  readonly patternStatus?: PatternStatus
  readonly minimumSampleSize?: number
  readonly dateRange?: PatternDateRange
}

export type PatternErrorCode =
  | "duplicate_evidence_reference"
  | "duplicate_pattern_identity"
  | "identity_mismatch"
  | "immutable_fact_conflict"
  | "invalid_evidence_reference"
  | "invalid_lifecycle"
  | "invalid_metric"
  | "invalid_query"
  | "invalid_scope"
  | "invalid_timestamp"
  | "invalid_version"
  | "malformed_input"
  | "malformed_json"
  | "missing_evidence_reference"
  | "missing_pattern_identity"
  | "serialization_failure"
  | "unsupported_schema_version"
  | "version_required"

export interface PatternError {
  readonly code: PatternErrorCode
  readonly message: string
  readonly field?: string
  readonly cause?: unknown
}

export type PatternResult<T> =
  | { readonly success: true; readonly value: T }
  | { readonly success: false; readonly errors: readonly PatternError[] }

export type PatternValidationResult = PatternResult<PatternRecord>

export interface CreatePatternInput {
  readonly patternVersion: number
  readonly scope: PatternScope
  readonly createdAt: string
  readonly interpretation: string
  readonly historicalMemory: readonly HistoricalMemoryRecord[]
  readonly metricSummary: PatternMetricSummary
  readonly existingPatternIds?: ReadonlySet<string>
}
