import { createHash } from "node:crypto"
import { inspectD3Target } from "@/lib/data-platform/population/postgres"
import { DeterministicD2Port, FixtureNormalizerRegistry, InMemoryObjectStorage } from "@/lib/data-platform/population/testing"
import { createCandidateId, expandPopulationUnits, watermarkResultForOutcome } from "@/lib/data-platform/population"
import { fundingCommand } from "@/tests/data-platform/persistence/postgres/fixtures"
import { fundingCandidate, job, units } from "./fixtures"

async function bytes(value: string) { async function* stream(){ yield new TextEncoder().encode(value) }; return stream() }
async function main() {
  const checks: Array<[string,boolean]> = []; const check=(name:string,pass:boolean)=>checks.push([name,pass])
  check("D3 isolated target accepted",inspectD3Target("postgres://redacted@localhost/quantterminal_d3_isolated").safe)
  check("production target rejected",!inspectD3Target("postgres://redacted@primary/quantterminal_prod").safe)
  check("D2 target reuse rejected",!inspectD3Target("postgres://redacted@localhost/quantterminal_d3_isolated",null,"postgres://redacted@localhost/quantterminal_d3_isolated").safe)
  const first=units(); const second=units(); check("unit expansion deterministic",first.map(x=>x.unitId).join()===second.map(x=>x.unitId).join()); check("duplicate specification deduplicated",expandPopulationUnits(job(),[...first.map(u=>({...u.identity,providerSnapshotId:u.providerSnapshotId,policyVersionId:u.policyVersionId,requestFingerprint:u.requestFingerprint,requestParameters:u.requestParameters,required:u.required})),{...first[0].identity,providerSnapshotId:first[0].providerSnapshotId,policyVersionId:first[0].policyVersionId,requestFingerprint:first[0].requestFingerprint,requestParameters:first[0].requestParameters,required:first[0].required}],first[0].createdAt).length===2)
  const store=new InMemoryObjectStorage(); const content="bounded fixture content"; const hash=createHash("sha256").update(content).digest("hex"); const ref=await store.putImmutable({objectStorageKey:`fixture/${hash}`,contentHash:hash,mediaType:"text/plain",byteLength:new TextEncoder().encode(content).byteLength,content:await bytes(content)}); const same=await store.putImmutable({objectStorageKey:`fixture/${hash}`,contentHash:hash,mediaType:"text/plain",byteLength:new TextEncoder().encode(content).byteLength,content:await bytes(content)}); check("immutable object idempotent",ref.contentHash===same.contentHash); check("object stat",(await store.stat(ref.objectStorageKey)).exists)
  let replacementRejected=false; try { const other="other"; const otherHash=createHash("sha256").update(other).digest("hex"); await store.putImmutable({objectStorageKey:ref.objectStorageKey,contentHash:otherHash,mediaType:"text/plain",byteLength:5,content:await bytes(other)}) } catch { replacementRejected=true }; check("immutable replacement rejected",replacementRejected)
  let missingRejected=false; try { for await (const _ of store.read("missing")) void _ } catch { missingRejected=true }; check("missing object rejected",missingRejected)
  const candidate=fundingCandidate(first[0].unitId,"attempt:fixture"); check("candidate identity stable",candidate.candidateId===createCandidateId({rawManifestId:candidate.rawManifestId,sourceObservationId:candidate.sourceObservationId,parserVersion:candidate.parserVersion,candidateOrdinal:"0"}))
  const registry=new FixtureNormalizerRegistry(); registry.register({datasetId:"funding",candidateKind:"FUNDING",normalizationVersion:"fixture-normalizer",normalize:()=>fundingCommand().requiredLineage.length?fundingCommand():fundingCommand()}); const command=registry.normalize({candidate,datasetRegistrySnapshotId:"dataset",providerRegistrySnapshotId:"provider",providerCertificationSnapshotId:"certification",policyVersionId:"policy",schemaVersion:"1",normalizationVersion:"fixture-normalizer",rawManifestId:candidate.rawManifestId}); check("fixture normalization deterministic",command.idempotencyKey===registry.normalize({candidate,datasetRegistrySnapshotId:"dataset",providerRegistrySnapshotId:"provider",providerCertificationSnapshotId:"certification",policyVersionId:"policy",schemaVersion:"1",normalizationVersion:"fixture-normalizer",rawManifestId:candidate.rawManifestId}).idempotencyKey)
  let missingBindingRejected=false; try { registry.normalize({candidate,datasetRegistrySnapshotId:"",providerRegistrySnapshotId:"provider",providerCertificationSnapshotId:"certification",policyVersionId:"policy",schemaVersion:"1",normalizationVersion:"fixture-normalizer",rawManifestId:candidate.rawManifestId}) } catch { missingBindingRejected=true }; check("missing normalization binding rejected",missingBindingRejected)
  const d2=new DeterministicD2Port(()=>({status:"DUPLICATE",canonicalRecordId:"canonical:fixture",recordVersion:1,checksum:"a".repeat(64)})); const d2a=await d2.execute(command); const d2b=await d2.execute(command); check("D2 retry idempotent",d2a.status==="DUPLICATE"&&d2b.status==="DUPLICATE"); check("conflict watermark blocked",watermarkResultForOutcome("CONFLICT")==="BLOCKED_CONFLICT"); check("cancelled watermark blocked",watermarkResultForOutcome("CANCELLED")==="BLOCKED_CANCELLED")
  const failures=checks.filter(([,pass])=>!pass); console.log(`D3 PHASE 2 UNIT SUITE: ${failures.length?"FAIL":"PASS"}`); for(const [name,pass] of checks) console.log(`[${pass?"PASS":"FAIL"}] ${name}`); if(failures.length) process.exitCode=1
}
void main().catch((error:unknown)=>{console.error(error);process.exitCode=1})
