export type HistoricalPanelFrequency = "always" | "often" | "situational" | "rare" | "internal"

export interface HistoricalIntelligencePanelInventoryItem {
  panelName: string
  purpose: string
  inputs: string[]
  outputs: string[]
  dependencies: string[]
  userValue: string
  complexityScore: number
  frequencyScore: number
  onboardingDifficulty: number
  frequency: HistoricalPanelFrequency
}

export const historicalIntelligencePanelInventory: HistoricalIntelligencePanelInventoryItem[] = [
  {
    panelName: "Replay Case Selector",
    purpose: "Switch between mock replay cases and drive selected-case intelligence.",
    inputs: ["Replay catalog", "selected case id"],
    outputs: ["selected ReplayCase"],
    dependencies: ["core/replay mock catalog"],
    userValue: "Creates the primary entry point into the forensics workflow.",
    complexityScore: 24,
    frequencyScore: 95,
    onboardingDifficulty: 18,
    frequency: "always",
  },
  {
    panelName: "Selected Case Summary",
    purpose: "Summarize event title, symbol, timeframe, event window, verdict, and confidence.",
    inputs: ["selected ReplayCase", "active ReplayFrame"],
    outputs: ["case brief", "final verdict", "confidence read"],
    dependencies: ["ReplayCase canonical model"],
    userValue: "Answers what case is being reviewed before the user inspects details.",
    complexityScore: 28,
    frequencyScore: 95,
    onboardingDifficulty: 15,
    frequency: "always",
  },
  {
    panelName: "Replay Learning Summary",
    purpose: "Compress explanation, memory, agent alignment, and playbook lessons into one learning read.",
    inputs: ["case id", "replay explanation", "agent accuracy", "market memory", "tactical playbook"],
    outputs: ["case verdict", "what worked", "what failed", "future execution rule"],
    dependencies: ["replayLearningSummaryEngine"],
    userValue: "Gives the fastest answer to what the system learned.",
    complexityScore: 62,
    frequencyScore: 88,
    onboardingDifficulty: 38,
    frequency: "always",
  },
  {
    panelName: "Narrative vs Reality",
    purpose: "Compare claimed narrative with supporting and contradicting evidence.",
    inputs: ["ReplayFrame narrative snapshot"],
    outputs: ["claimed narrative", "evidence split", "conclusion"],
    dependencies: ["ReplayFrame.narrative"],
    userValue: "Makes unsupported narratives visible.",
    complexityScore: 46,
    frequencyScore: 84,
    onboardingDifficulty: 30,
    frequency: "often",
  },
  {
    panelName: "Replay Timeline",
    purpose: "Show price, news, funding/OI, and expectation snapshots in replay order.",
    inputs: ["selected ReplayCase", "active ReplayFrame"],
    outputs: ["event timeline", "price reaction", "news items", "market snapshots"],
    dependencies: ["ReplayCase.frames"],
    userValue: "Provides evidence chronology and context.",
    complexityScore: 58,
    frequencyScore: 84,
    onboardingDifficulty: 34,
    frequency: "often",
  },
  {
    panelName: "Possible Drivers",
    purpose: "Rank likely drivers behind the event with confidence and rationale.",
    inputs: ["ReplayFrame narrative possible drivers"],
    outputs: ["ranked drivers", "confidence", "explanations"],
    dependencies: ["ReplayFrame.narrative.possibleDrivers"],
    userValue: "Acts as the immediate driver anchor for the case.",
    complexityScore: 34,
    frequencyScore: 90,
    onboardingDifficulty: 22,
    frequency: "always",
  },
  {
    panelName: "Replay Explanation",
    purpose: "Explain why the setup worked, failed, or remained mixed.",
    inputs: ["case id", "similar events", "outcome memory", "market memory", "prediction context"],
    outputs: ["primary reason", "supporting factors", "failure factors", "future rule"],
    dependencies: ["replayExplanationEngine"],
    userValue: "Provides the main interpretive diagnosis.",
    complexityScore: 72,
    frequencyScore: 82,
    onboardingDifficulty: 46,
    frequency: "often",
  },
  {
    panelName: "Replay Decision Journal",
    purpose: "Show the hypothetical decision, invalidation, expected outcome, actual outcome, and lesson.",
    inputs: ["case id", "ReplayCase"],
    outputs: ["decision", "reason", "mistake tag", "future rule", "confidence"],
    dependencies: ["replayDecisionJournalEngine"],
    userValue: "Connects forensics to decision hygiene.",
    complexityScore: 55,
    frequencyScore: 76,
    onboardingDifficulty: 35,
    frequency: "often",
  },
  {
    panelName: "Similar Historical Events",
    purpose: "Compare selected case to top historical analogs.",
    inputs: ["selected ReplayCase", "mock Replay catalog"],
    outputs: ["similarity score", "match reasons", "key differences", "takeaway"],
    dependencies: ["similarHistoricalEventEngine"],
    userValue: "Adds analog memory and prevents one-off interpretation.",
    complexityScore: 60,
    frequencyScore: 74,
    onboardingDifficulty: 40,
    frequency: "often",
  },
  {
    panelName: "Setup Outcome Memory",
    purpose: "Summarize how similar setups historically performed.",
    inputs: ["ReplayCase", "setup query"],
    outputs: ["sample size", "win rate", "average move", "failure mode", "lesson"],
    dependencies: ["setupOutcomeMemoryEngine"],
    userValue: "Turns history into execution expectations.",
    complexityScore: 64,
    frequencyScore: 72,
    onboardingDifficulty: 42,
    frequency: "often",
  },
  {
    panelName: "Historical Query Explorer",
    purpose: "Search historical records by keyword, asset, narrative, tag, and limit.",
    inputs: ["query params", "read API"],
    outputs: ["matched cases", "events", "memories", "decisions", "playbooks"],
    dependencies: ["/api/historical-intelligence/query"],
    userValue: "Useful for analysts, but less useful in default case review.",
    complexityScore: 76,
    frequencyScore: 44,
    onboardingDifficulty: 64,
    frequency: "situational",
  },
  {
    panelName: "Market Memory",
    purpose: "Summarize remembered regimes, clusters, patterns, reliability notes, and expected reactions.",
    inputs: ["case id", "market memory repository"],
    outputs: ["regimes", "clusters", "patterns", "tactical memory takeaway"],
    dependencies: ["marketMemoryEngine"],
    userValue: "Provides broad memory context for a case.",
    complexityScore: 68,
    frequencyScore: 62,
    onboardingDifficulty: 48,
    frequency: "situational",
  },
  {
    panelName: "Expectation Intelligence",
    purpose: "Explain what market participants appeared to expect and how surprising the event was.",
    inputs: ["ReplayCase expectation snapshot"],
    outputs: ["expected outcome", "probability", "surprise score", "priced-in status"],
    dependencies: ["expectationIntelligenceEngine"],
    userValue: "Clarifies whether the market was surprised or already positioned.",
    complexityScore: 54,
    frequencyScore: 70,
    onboardingDifficulty: 32,
    frequency: "often",
  },
  {
    panelName: "Prediction Markets",
    purpose: "Show mock prediction market context and crowd expectation interpretation.",
    inputs: ["case id", "prediction market repository"],
    outputs: ["market events", "implied probability", "market disagreement", "interpretation"],
    dependencies: ["predictionMarketEngine"],
    userValue: "Adds an explicit expectation layer, but overlaps with Expectation Intelligence.",
    complexityScore: 66,
    frequencyScore: 58,
    onboardingDifficulty: 48,
    frequency: "situational",
  },
  {
    panelName: "Event Memory Linker",
    purpose: "Connect a source event to prediction, similar events, setup memory, agents, and playbook context.",
    inputs: ["case id", "linked intelligence engines"],
    outputs: ["possible linkages", "execution implication", "memory confidence"],
    dependencies: ["eventMemoryLinkerEngine"],
    userValue: "Powerful synthesis layer, but conceptually overlaps with Market Memory and Replay Explanation.",
    complexityScore: 82,
    frequencyScore: 48,
    onboardingDifficulty: 68,
    frequency: "situational",
  },
  {
    panelName: "External Adapter Preview",
    purpose: "Preview mock/live-capable external event candidates before review.",
    inputs: ["source type", "keyword", "asset", "limit"],
    outputs: ["adapter health", "raw count", "normalized candidates", "warnings"],
    dependencies: ["externalEventAdapterRegistry", "preview APIs"],
    userValue: "Developer/operator utility for source readiness, not core replay value.",
    complexityScore: 74,
    frequencyScore: 24,
    onboardingDifficulty: 72,
    frequency: "internal",
  },
  {
    panelName: "Polymarket Live Validation",
    purpose: "Validate live Polymarket sample quality without writing to persistence.",
    inputs: ["keyword", "asset", "limit"],
    outputs: ["schema issues", "confidence summary", "sample diagnostics"],
    dependencies: ["polymarketLiveValidationEngine"],
    userValue: "Important for adapter QA, but should not be in the primary analyst journey.",
    complexityScore: 78,
    frequencyScore: 20,
    onboardingDifficulty: 76,
    frequency: "internal",
  },
  {
    panelName: "External Review Queue",
    purpose: "Review normalized external candidates before accepting, rejecting, or ignoring them.",
    inputs: ["adapter candidates", "review action"],
    outputs: ["pending items", "review status", "accepted item id"],
    dependencies: ["externalEventReviewQueueService"],
    userValue: "Critical for future ingestion governance, low value in default replay read mode.",
    complexityScore: 72,
    frequencyScore: 30,
    onboardingDifficulty: 70,
    frequency: "internal",
  },
  {
    panelName: "Accepted Event Linker",
    purpose: "Generate and review links between accepted events and historical records.",
    inputs: ["accepted review item id", "mock persistence records"],
    outputs: ["link candidates", "accepted links", "rationale"],
    dependencies: ["acceptedEventLinkerService"],
    userValue: "Enables relationship memory, but requires operator context.",
    complexityScore: 80,
    frequencyScore: 26,
    onboardingDifficulty: 78,
    frequency: "internal",
  },
  {
    panelName: "Relationship Graph",
    purpose: "Render accepted event links as a compact text-first trace.",
    inputs: ["source event id", "target type", "accepted links"],
    outputs: ["nodes", "edges", "relationship summary"],
    dependencies: ["historicalRelationshipGraphEngine"],
    userValue: "Useful once links exist; weak empty-state value before ingestion workflow is used.",
    complexityScore: 70,
    frequencyScore: 34,
    onboardingDifficulty: 58,
    frequency: "situational",
  },
  {
    panelName: "Historical Scoring",
    purpose: "Rank events, memories, and playbooks by importance, confidence, and learning value.",
    inputs: ["mock persistence records", "relationship context"],
    outputs: ["top scored records", "average score", "highest learning item"],
    dependencies: ["historicalScoringEngine"],
    userValue: "Strong triage signal if integrated into records; noisy as a standalone panel.",
    complexityScore: 66,
    frequencyScore: 42,
    onboardingDifficulty: 52,
    frequency: "situational",
  },
  {
    panelName: "Record Inspector",
    purpose: "Inspect mock persistence records by type and limit.",
    inputs: ["read APIs", "record type", "limit"],
    outputs: ["latest records", "counts", "compact metadata"],
    dependencies: ["persistence read APIs"],
    userValue: "Developer/operator utility; not a default replay analysis surface.",
    complexityScore: 62,
    frequencyScore: 28,
    onboardingDifficulty: 64,
    frequency: "internal",
  },
  {
    panelName: "Decision Write Test",
    purpose: "Create mock decision records for validation.",
    inputs: ["selected ReplayCase", "form fields"],
    outputs: ["created decision id", "validation feedback"],
    dependencies: ["historicalPersistenceWriteService", "write API"],
    userValue: "Internal persistence validation only.",
    complexityScore: 70,
    frequencyScore: 18,
    onboardingDifficulty: 76,
    frequency: "internal",
  },
  {
    panelName: "Event Ingestion Test",
    purpose: "Generate mock normalized events and optional candidates.",
    inputs: ["mock event type", "ReplayCase context"],
    outputs: ["normalized event preview", "candidate counts", "readiness indicators"],
    dependencies: ["historicalEventIngestionService"],
    userValue: "Internal ingestion validation only.",
    complexityScore: 72,
    frequencyScore: 18,
    onboardingDifficulty: 76,
    frequency: "internal",
  },
  {
    panelName: "Agent Accuracy",
    purpose: "Show case-aware or catalog-level agent alignment and calibration.",
    inputs: ["ReplayCase", "Replay catalog"],
    outputs: ["top agent", "weakest agent", "alignment lessons", "fallback note"],
    dependencies: ["agentAccuracyEngine"],
    userValue: "Explains which agent lens was useful for this case.",
    complexityScore: 64,
    frequencyScore: 64,
    onboardingDifficulty: 46,
    frequency: "situational",
  },
  {
    panelName: "Tactical Playbook",
    purpose: "Translate the case into future execution rules, checklists, and invalidation triggers.",
    inputs: ["ReplayCase"],
    outputs: ["lesson", "mistake", "confirmation", "playbook", "checklists"],
    dependencies: ["tacticalPlaybookEngine"],
    userValue: "Converts forensics into next-time behavior.",
    complexityScore: 54,
    frequencyScore: 78,
    onboardingDifficulty: 36,
    frequency: "often",
  },
  {
    panelName: "Agent Committee",
    purpose: "Show selected-frame agent summaries from Technical, Flow, Narrative, Expectation, and Risk agents.",
    inputs: ["ReplayFrame.agents"],
    outputs: ["agent tone", "confidence", "summary"],
    dependencies: ["ReplayFrame agent summaries"],
    userValue: "Readable multi-lens summary, but overlaps with Agent Accuracy and Learning Summary.",
    complexityScore: 52,
    frequencyScore: 60,
    onboardingDifficulty: 38,
    frequency: "situational",
  },
]

