export const nofxTop20Strengths = [
  "Clear product promise as an AI trading terminal.",
  "Combines research, strategy, execution, and monitoring as one operating surface.",
  "Route-separated workspaces reduce workflow collision.",
  "Beginner and advanced setup modes are explicitly separated.",
  "Dashboard starts from operational state.",
  "Selected trader context scopes the dashboard.",
  "Decision logs create AI accountability.",
  "Expandable AI reasoning reduces default cognitive load.",
  "Account, positions, PnL, and statistics are visible together.",
  "Charts are placed near decisions and positions.",
  "Strategy Studio is separated from monitoring.",
  "Settings/configuration are not the primary dashboard.",
  "System freshness and polling behavior are treated as UX concerns.",
  "Exchange/model/trader identity is visible.",
  "Position tables are dense and scan-friendly.",
  "Failure/empty states exist for missing backend or missing traders.",
  "Agent chat is route-separated from dashboard.",
  "Multi-asset support is product-level, not hidden detail.",
  "Competition/model performance is a distinct workflow.",
  "Architecture communicates layers from terminal to API to model/exchange connectivity.",
] as const

export const quantTerminalTop20Weaknesses = [
  "Replay still contains advanced tooling in the same workspace, even if collapsed.",
  "Historical Ops does not yet have its own route.",
  "Density modes are defined but not implemented.",
  "Realtime and Replay are not yet unified by one operating shell.",
  "Confidence semantics are not fully standardized in UI primitives.",
  "Agent outputs are useful but could become too verbose.",
  "Data freshness is less explicit outside realtime sockets.",
  "Historical graph and scoring are internal but still visible in Replay advanced flow.",
  "Source lineage is not yet summarized at the case level.",
  "Prediction market context is still mock/live-preview transitional.",
  "No route-level playbook authoring workflow yet.",
  "No explicit beginner onboarding for Replay concepts.",
  "No trader/research mode toggle.",
  "No global selected context shell.",
  "No unified activity/health strip for Historical Intelligence pipeline.",
  "Data Operations Workbench can become too large.",
  "Decision Journal is not yet persisted as a normal user action.",
  "Narrative completeness is UI-only and not yet historically tracked.",
  "Case catalog is still mock-first.",
  "Information Intelligence naming is not yet surfaced as a primary route.",
] as const

export const nofxTop20MigrationOpportunities = [
  "Route-separate Historical Intelligence Ops.",
  "Add beginner/trader/research density modes.",
  "Add selected-context shell across QuantTerminal.",
  "Make Replay a default read-only report.",
  "Add freshness/confidence/risk strip.",
  "Move source intake tools out of Replay.",
  "Create Playbook Lab route.",
  "Use expandable evidence traces.",
  "Standardize decision logs as audit artifacts.",
  "Unify agent reliability with current agent read.",
  "Expose source lineage as a compact case footer.",
  "Add onboarding for Replay concepts.",
  "Treat Data Operations as advanced mode.",
  "Create Historical Ops health dashboard.",
  "Use chart/evidence adjacency.",
  "Keep strategy authoring separate from monitoring.",
  "Avoid execution controls in intelligence workflows.",
  "Adopt route-level workflow names.",
  "Use failure/empty states as first-class UX.",
  "Keep product identity as an operating system, not a page collection.",
] as const

export const nofxTop10ThingsNotToCopy = [
  "Do not copy NOFX code, components, styling, or implementation.",
  "Do not copy execution controls into QuantTerminal Replay.",
  "Do not add exchange account setup to Market Forensics.",
  "Do not copy model-provider routing or partner/referral flows.",
  "Do not copy competition/leaderboard mechanics unless QuantTerminal needs agent benchmarking.",
  "Do not make Replay a strategy editor.",
  "Do not expose every operational detail to beginner users.",
  "Do not use automated trading language for historical intelligence.",
  "Do not make AI reasoning feel like an unquestioned authority.",
  "Do not adopt multi-asset breadth at the cost of crypto market depth.",
] as const

export const nofxExecutiveAuditReport = {
  executiveSummary:
    "NOFX is useful to QuantTerminal as a product-structure reference: it separates onboarding, strategy, dashboard monitoring, agent chat, settings, and advanced setup while keeping AI decision traceability close to trading state. QuantTerminal should adapt this separation to Realtime Intelligence, Replay Forensics, Historical Intelligence Ops, Playbook Lab, and Settings without copying code or execution workflows.",
  top20NofxStrengths: nofxTop20Strengths,
  top20QuantTerminalWeaknesses: quantTerminalTop20Weaknesses,
  top20MigrationOpportunities: nofxTop20MigrationOpportunities,
  top10ThingsNotToCopy: nofxTop10ThingsNotToCopy,
  recommendedFutureLayout: [
    "Global shell: selected context, freshness, confidence, risk.",
    "Realtime Tactical Dashboard: now-state and execution risk.",
    "Replay Forensics: narrative investigation report.",
    "Historical Intelligence Ops: intake, review, validation, graph, scoring, inspector.",
    "Tactical Playbook Lab: setup rules and outcome memory.",
    "Settings: sources, connectors, preferences.",
  ],
  nofxInspiredMigrationPhases: [
    "Keep Replay Narrative Flow stable.",
    "Extract Data Operations Workbench into its own route.",
    "Add density modes.",
    "Create Tactical Playbook Lab.",
    "Build route-level Tactical Decision OS shell.",
  ],
} as const

