import type postgres from "postgres"
import type { CanonicalCommitResult } from "@/lib/data-platform/persistence"
import { aggregateJobState, createPopulationJobId, createPopulationRunId, mapCommitResult, watermarkResultForOutcome, type CandidateQualityResult, type CandidateValidationResult, type PopulationCandidate, type PopulationCheckpoint, type PopulationJob, type PopulationJobRequest, type PopulationLease, type PopulationOutcome, type PopulationRun, type PopulationUnit, type PopulationWatermarkEligibility, type RetrievalAttempt } from "@/lib/data-platform/population"
import type { D3PostgresClient } from "./client"

export type CreateJobResult = { readonly status: "CREATED" | "DUPLICATE"; readonly jobId: string }
export type CandidateWriteResult = { readonly status: "CREATED" | "DUPLICATE"; readonly candidateId: string } | { readonly status: "CONFLICT"; readonly candidateId: string }
export interface LeaseClaim { readonly unitId: string; readonly leaseId: string; readonly fencingToken: number }
export interface ReconciliationRead { readonly consistent: boolean; readonly reasons: readonly string[] }

function eventId(kind: string, identity: string) { return `population-event:${kind}:${identity}` }
function json(value: unknown): string { return JSON.stringify(value) }

export interface PopulationPostgresAdapter {
  createJob(request: PopulationJobRequest): Promise<CreateJobResult>
  createRun(jobId: string, attemptNumber: number, createdAt: string): Promise<PopulationRun>
  expandUnits(units: readonly PopulationUnit[]): Promise<number>
  claimUnit(ownerId: string, runId: string, now: string, expiresAt: string): Promise<LeaseClaim | null>
  heartbeat(unitId: string, leaseId: string, ownerId: string, fencingToken: number, now: string, expiresAt: string): Promise<void>
  checkpoint(checkpoint: PopulationCheckpoint, leaseId: string, ownerId: string): Promise<"CREATED" | "DUPLICATE">
  appendRetrievalAttempt(attempt: RetrievalAttempt): Promise<void>
  persistCandidate(candidate: PopulationCandidate): Promise<CandidateWriteResult>
  appendValidation(result: CandidateValidationResult): Promise<void>
  appendQuality(result: CandidateQualityResult): Promise<void>
  createSubmission(submissionId: string, candidateId: string, idempotencyKey: string, submittedAt: string): Promise<"CREATED" | "DUPLICATE">
  recordD2Result(input: { readonly jobId: string; readonly runId: string; readonly unitId: string; readonly candidateId: string; readonly retrievalAttemptId: string; readonly rawManifestId: string; readonly submissionId: string; readonly leaseId: string; readonly ownerId: string; readonly fencingToken: number; readonly result: CanonicalCommitResult; readonly outcomeId: string; readonly createdAt: string }): Promise<PopulationOutcome>
  scheduleRetry(input: { readonly retryEventId: string; readonly jobId: string; readonly runId: string; readonly unitId: string; readonly candidateId: string | null; readonly classificationId: string; readonly policyId: string; readonly policyVersion: string; readonly retryAfter: string | null; readonly createdAt: string }): Promise<void>
  requestCancellation(jobId: string, eventIdentity: string, actorId: string, at: string): Promise<void>
  aggregateJob(jobId: string, at: string): Promise<string>
  writeWatermarkDecision(decision: PopulationWatermarkEligibility): Promise<void>
  readResumableUnits(jobId: string): Promise<readonly string[]>
  reconcileJob(jobId: string): Promise<ReconciliationRead>
  reconcileUnit(unitId: string): Promise<ReconciliationRead>
}

export function createPopulationPostgresAdapter(client: D3PostgresClient): PopulationPostgresAdapter {
  const assertLease = async (sql: postgres.TransactionSql, unitId: string, leaseId: string, ownerId: string, token: number, now: string) => {
    const rows = await sql<{ readonly ok: boolean }[]>`SELECT EXISTS(SELECT 1 FROM control.population_units u JOIN control.population_leases l ON l.lease_id=u.active_lease_id WHERE u.unit_id=${unitId} AND l.lease_id=${leaseId} AND l.owner_id=${ownerId} AND u.current_fencing_token=${token} AND l.fencing_token=${token} AND l.released_at IS NULL AND l.expires_at>${now}) ok`
    if (!rows[0]?.ok) throw new Error("STALE_FENCING_TOKEN")
  }
  return Object.freeze({
    async createJob(request) {
      const jobId = createPopulationJobId(request.requestIdentity, request.occurrenceIdentity, request.intentionalRerunIdentity)
      return client.transaction(async (sql) => {
        const existing = await sql<{ readonly job_id: string }[]>`SELECT job_id FROM control.population_jobs WHERE request_identity=${request.requestIdentity} AND occurrence_identity=${request.occurrenceIdentity} AND COALESCE(intentional_rerun_identity,'')=COALESCE(${request.intentionalRerunIdentity},'') FOR UPDATE`
        if (existing[0]) return { status: "DUPLICATE" as const, jobId: existing[0].job_id }
        const currentEventId = eventId("job-created", jobId)
        await sql`INSERT INTO control.population_jobs(job_id,request_identity,occurrence_identity,intentional_rerun_identity,profile_id,profile_version,dataset_id,provider_id,scope_fingerprint,current_state,current_event_id,requested_at,requested_by,created_at,updated_at) VALUES(${jobId},${request.requestIdentity},${request.occurrenceIdentity},${request.intentionalRerunIdentity},${request.profile.profileId},${request.profile.profileVersion},${request.datasetId},${request.providerId},${request.requestIdentity},'QUEUED',${currentEventId},${request.requestedAt},${request.requestedBy},${request.requestedAt},${request.requestedAt})`
        await sql`INSERT INTO control.population_job_events(event_id,job_id,event_type,previous_state,next_state,actor_id,occurred_at) VALUES(${currentEventId},${jobId},'JOB_CREATED',NULL,'QUEUED',${request.requestedBy},${request.requestedAt})`
        return { status: "CREATED" as const, jobId }
      })
    },
    async createRun(jobId, attemptNumber, createdAt) {
      const runId = createPopulationRunId(jobId, attemptNumber); const createdEvent = eventId("run-created", runId); const startedEvent = eventId("run-started", runId)
      await client.transaction(async (sql) => {
        await sql`INSERT INTO control.population_runs(run_id,job_id,attempt_number,current_state,started_at,heartbeat_at) VALUES(${runId},${jobId},${attemptNumber},'RUNNING',${createdAt},${createdAt}) ON CONFLICT(run_id) DO NOTHING`
        await sql`INSERT INTO control.population_run_events(event_id,run_id,event_type,previous_state,next_state,actor_id,occurred_at) VALUES(${createdEvent},${runId},'RUN_CREATED',NULL,'CREATED','coordinator',${createdAt}) ON CONFLICT DO NOTHING`
        await sql`INSERT INTO control.population_run_events(event_id,run_id,event_type,previous_state,next_state,actor_id,occurred_at) VALUES(${startedEvent},${runId},'RUN_STARTED','CREATED','RUNNING','coordinator',${createdAt}) ON CONFLICT DO NOTHING`
        await sql`UPDATE control.population_jobs SET current_state='RUNNING',updated_at=${createdAt} WHERE job_id=${jobId} AND current_state IN ('QUEUED','PAUSED')`
      })
      const run: PopulationRun = { runId, jobId, attemptNumber, currentState: "RUNNING", workerPoolId: null, startedAt: createdAt, heartbeatAt: createdAt, completedAt: null, retryClassificationId: null, currentCheckpointId: null }
      return run
    },
    async expandUnits(units) {
      return client.transaction(async (sql) => { let inserted = 0; for (const unit of units) { const rows = await sql`INSERT INTO control.population_units(unit_id,job_id,profile_id,profile_version,dataset_id,provider_id,provider_snapshot_id,policy_version_id,venue,subject_or_symbol,window_start,window_end,resolution,partition_key,request_fingerprint,request_parameters,required,current_state,attempt_count,created_at,updated_at) VALUES(${unit.unitId},${unit.jobId},${unit.identity.profileId},${unit.identity.profileVersion},${unit.identity.datasetId},${unit.identity.providerId},${unit.providerSnapshotId},${unit.policyVersionId},${unit.identity.venue},${unit.identity.subjectOrSymbol},${unit.identity.windowStart},${unit.identity.windowEnd},${unit.identity.resolution},${unit.identity.partitionKey},${unit.requestFingerprint},${sql.json(unit.requestParameters)},${unit.required},'PENDING',0,${unit.createdAt},${unit.updatedAt}) ON CONFLICT(unit_id) DO NOTHING RETURNING unit_id`; if (rows.length) { inserted++; await sql`INSERT INTO control.population_unit_events(event_id,unit_id,event_type,previous_state,next_state,actor_id,occurred_at) VALUES(${eventId("unit-created",unit.unitId)},${unit.unitId},'UNIT_CREATED',NULL,'PENDING','coordinator',${unit.createdAt})` } }; return inserted })
    },
    async claimUnit(ownerId, runId, now, expiresAt) { const rows = await client.sql<{ readonly unit_id: string; readonly lease_id: string; readonly fencing_token: number }[]>`SELECT * FROM control.claim_population_unit(${ownerId},${runId},${now},${expiresAt})`; return rows[0] ? { unitId: rows[0].unit_id, leaseId: rows[0].lease_id, fencingToken: Number(rows[0].fencing_token) } : null },
    async heartbeat(unitId, leaseId, ownerId, fencingToken, now, expiresAt) { await client.transaction(async (sql) => { await assertLease(sql,unitId,leaseId,ownerId,fencingToken,now); await sql`SELECT control.heartbeat_population_lease(${unitId},${ownerId},${fencingToken},${now},${expiresAt})`; await sql`INSERT INTO control.population_unit_events(event_id,unit_id,event_type,previous_state,next_state,fencing_token,actor_id,occurred_at) SELECT ${eventId("heartbeat",`${unitId}:${fencingToken}:${now}`)},unit_id,'HEARTBEAT',current_state,current_state,${fencingToken},${ownerId},${now} FROM control.population_units WHERE unit_id=${unitId}` }) },
    async checkpoint(checkpoint, leaseId, ownerId) { return client.transaction(async (sql) => { await assertLease(sql,checkpoint.unitId,leaseId,ownerId,checkpoint.fencingToken,checkpoint.createdAt); if (checkpoint.checkpointType === "RAW_BOUNDARY" && !checkpoint.rawManifestId) throw new Error("RAW_MANIFEST_REQUIRED"); if (checkpoint.checkpointType === "CANDIDATE_BOUNDARY" && !checkpoint.candidateCursor) throw new Error("CANDIDATE_BOUNDARY_REQUIRED"); if (checkpoint.checkpointType === "CANONICAL_BOUNDARY" && (!checkpoint.canonicalSubmissionId || !checkpoint.lastOutcomeId)) throw new Error("CANONICAL_OUTCOME_REQUIRED"); const rows = await sql`INSERT INTO control.population_checkpoints(checkpoint_id,job_id,run_id,unit_id,fencing_token,checkpoint_type,completed_stage,raw_manifest_id,candidate_cursor,canonical_submission_id,last_outcome_id,created_at) VALUES(${checkpoint.checkpointId},${checkpoint.jobId},${checkpoint.runId},${checkpoint.unitId},${checkpoint.fencingToken},${checkpoint.checkpointType},${checkpoint.completedStage},${checkpoint.rawManifestId},${checkpoint.candidateCursor},${checkpoint.canonicalSubmissionId},${checkpoint.lastOutcomeId},${checkpoint.createdAt}) ON CONFLICT(checkpoint_id) DO NOTHING RETURNING checkpoint_id`; if (!rows.length) return "DUPLICATE" as const; await sql`UPDATE control.population_units SET current_checkpoint_id=${checkpoint.checkpointId},updated_at=${checkpoint.createdAt} WHERE unit_id=${checkpoint.unitId}`; await sql`INSERT INTO control.population_unit_events(event_id,unit_id,run_id,event_type,previous_state,next_state,fencing_token,actor_id,occurred_at) SELECT ${eventId("checkpoint",checkpoint.checkpointId)},unit_id,${checkpoint.runId},'CHECKPOINT_ADVANCED',current_state,current_state,${checkpoint.fencingToken},${ownerId},${checkpoint.createdAt} FROM control.population_units WHERE unit_id=${checkpoint.unitId}`; return "CREATED" as const }) },
    async appendRetrievalAttempt(a) { await client.sql`INSERT INTO control.retrieval_attempts(attempt_id,unit_id,run_id,provider_id,provider_snapshot_id,request_fingerprint,started_at,completed_at,outcome,status_code,retry_after,response_media_type,raw_byte_count,raw_manifest_id,error_class,error_code,retry_classification_id) VALUES(${a.attemptId},${a.unitId},${a.runId},${a.providerId},${a.providerSnapshotId},${a.requestFingerprint},${a.startedAt},${a.completedAt},${a.outcome},${a.statusCode},${a.retryAfter},${a.responseMediaType},${a.rawByteCount},${a.rawManifestId},${a.errorClass},${a.errorCode},${a.retryClassificationId}) ON CONFLICT(attempt_id) DO NOTHING` },
    async persistCandidate(c) { return client.transaction(async (sql) => { const existing = await sql<{ readonly candidate_checksum: string }[]>`SELECT candidate_checksum FROM population.candidates WHERE candidate_id=${c.candidateId}`; if (existing[0]) return existing[0].candidate_checksum === c.candidateChecksum ? { status: "DUPLICATE" as const, candidateId: c.candidateId } : { status: "CONFLICT" as const, candidateId: c.candidateId }; await sql`INSERT INTO population.candidates(candidate_id,unit_id,retrieval_attempt_id,raw_manifest_id,dataset_id,provider_id,provider_snapshot_id,source_observation_id,source_observed_at,effective_at,parser_version,candidate_schema_version,candidate_kind,bounded_payload,candidate_checksum,validation_status,quality_eligibility,normalization_eligibility,created_at) VALUES(${c.candidateId},${c.unitId},${c.retrievalAttemptId},${c.rawManifestId},${c.datasetId},${c.providerId},${c.providerSnapshotId},${c.sourceObservationId},${c.sourceObservedAt},${c.effectiveAt},${c.parserVersion},${c.candidateSchemaVersion},${c.kind},${sql.json(c.payload)},${c.candidateChecksum},${c.validationStatus},${c.qualityEligibility},${c.normalizationEligibility},${c.createdAt})`; return { status: "CREATED" as const, candidateId: c.candidateId } }) },
    async appendValidation(v) { await client.sql`INSERT INTO quality.candidate_validation_results(validation_run_id,candidate_id,retrieval_attempt_id,validation_layer,rule_id,rule_version,outcome,blocking,failure_routing,policy_version_id,diagnostics,created_at) VALUES(${v.validationRunId},${v.candidateId},${v.retrievalAttemptId},${v.layer},${v.ruleId},${v.ruleVersion},${v.outcome},${v.blocking},${v.failureRouting},${v.policyVersionId},${client.sql.json(v.diagnostics)},${v.createdAt})` },
    async appendQuality(q) { await client.transaction(async (sql) => { await sql`INSERT INTO quality.candidate_evaluation_runs(evaluation_run_id,unit_id,policy_version_id,provider_certification_snapshot_id,created_at) VALUES(${q.evaluationRunId},${q.unitId},${q.policyVersionId},${q.providerCertificationSnapshotId},${q.createdAt}) ON CONFLICT DO NOTHING`; await sql`INSERT INTO quality.candidate_evaluation_results(quality_result_id,evaluation_run_id,candidate_id,result_level,rule_id,rule_version,outcome,created_at) VALUES(${q.qualityResultId},${q.evaluationRunId},${q.candidateId},${q.level},${q.ruleId},${q.ruleVersion},${q.outcome},${q.createdAt})` }) },
    async createSubmission(submissionId,candidateId,idempotencyKey,submittedAt) { const rows = await client.sql`INSERT INTO population.canonical_submissions(submission_id,candidate_id,idempotency_key,result_status,submitted_at) VALUES(${submissionId},${candidateId},${idempotencyKey},'PENDING',${submittedAt}) ON CONFLICT(candidate_id) DO NOTHING RETURNING submission_id`; return rows.length ? "CREATED" : "DUPLICATE" },
    async recordD2Result(input) { const outcome = mapCommitResult(input.result,input.candidateId,input.outcomeId,input.createdAt); await client.transaction(async (sql) => { await assertLease(sql,input.unitId,input.leaseId,input.ownerId,input.fencingToken,input.createdAt); const commitId = outcome.kind === "COMMITTED" ? outcome.commitId : null; const recordId = outcome.kind === "COMMITTED" || outcome.kind === "DUPLICATE" ? outcome.canonicalRecordId : null; const version = outcome.kind === "COMMITTED" || outcome.kind === "DUPLICATE" ? outcome.recordVersion : null; await sql`UPDATE population.canonical_submissions SET result_status=${input.result.status},canonical_commit_id=${commitId},canonical_record_id=${recordId},record_version=${version},resolved_at=${input.createdAt} WHERE submission_id=${input.submissionId}`; await sql`INSERT INTO control.population_outcomes(outcome_id,job_id,run_id,unit_id,candidate_id,retrieval_attempt_id,raw_manifest_id,submission_id,outcome_kind,d2_result_status,canonical_commit_id,conflict_id,quarantine_id,fencing_token,reason_codes,created_at) VALUES(${input.outcomeId},${input.jobId},${input.runId},${input.unitId},${input.candidateId},${input.retrievalAttemptId},${input.rawManifestId},${input.submissionId},${outcome.kind},${input.result.status},${commitId},${outcome.kind === "CONFLICT" ? outcome.conflictId : null},${outcome.kind === "CONFLICT" ? outcome.quarantineId : null},${input.fencingToken},${sql.array(outcome.kind === "PERMANENT_FAILURE" || outcome.kind === "QUARANTINED" || outcome.kind === "EMPTY" || outcome.kind === "UNSUPPORTED" || outcome.kind === "CANCELLED" || outcome.kind === "SKIPPED_BY_POLICY" ? [...outcome.reasonCodes] : [])},${input.createdAt})`; const next = outcome.kind === "COMMITTED" || outcome.kind === "DUPLICATE" ? "COMPLETED" : outcome.kind === "CONFLICT" || outcome.kind === "QUARANTINED" ? "QUARANTINED" : outcome.kind === "RETRYABLE_FAILURE" ? "RETRYABLE" : "FAILED"; await sql`UPDATE control.population_units SET current_state=${next},updated_at=${input.createdAt} WHERE unit_id=${input.unitId}`; await sql`INSERT INTO control.population_unit_events(event_id,unit_id,run_id,event_type,previous_state,next_state,fencing_token,actor_id,occurred_at,details) VALUES(${eventId("outcome",input.outcomeId)},${input.unitId},${input.runId},'UNIT_OUTCOME','PROCESSING',${next},${input.fencingToken},${input.ownerId},${input.createdAt},${sql.json({ outcomeId: input.outcomeId })})` }); return outcome },
    async scheduleRetry(i) { await client.sql`INSERT INTO control.retry_events(retry_event_id,job_id,run_id,unit_id,candidate_id,classification_id,retry_policy_id,retry_policy_version,retry_after,created_at) VALUES(${i.retryEventId},${i.jobId},${i.runId},${i.unitId},${i.candidateId},${i.classificationId},${i.policyId},${i.policyVersion},${i.retryAfter},${i.createdAt})` },
    async requestCancellation(jobId,eventIdentity,actorId,at) { await client.transaction(async (sql) => { await sql`UPDATE control.population_jobs SET current_state='CANCELLED',current_event_id=${eventIdentity},updated_at=${at} WHERE job_id=${jobId} AND current_state NOT IN ('SUCCEEDED','FAILED','CANCELLED','EXPIRED')`; await sql`UPDATE control.population_units SET cancellation_requested_at=${at},current_state=CASE WHEN current_state IN ('PENDING','RETRYABLE') THEN 'CANCELLED' ELSE current_state END,updated_at=${at} WHERE job_id=${jobId} AND current_state NOT IN ('COMPLETED','FAILED','QUARANTINED','CANCELLED')`; await sql`INSERT INTO control.population_job_events(event_id,job_id,event_type,previous_state,next_state,actor_id,occurred_at) VALUES(${eventIdentity},${jobId},'CANCELLATION_REQUESTED','RUNNING','CANCELLED',${actorId},${at}) ON CONFLICT DO NOTHING` }) },
    async aggregateJob(jobId,at) { const rows = await client.sql<{ readonly current_state: PopulationUnit["currentState"]; readonly required: boolean }[]>`SELECT current_state,required FROM control.population_units WHERE job_id=${jobId} ORDER BY unit_id`; const state = aggregateJobState(rows.map(r=>r.current_state),rows.map(r=>r.required)); await client.sql`UPDATE control.population_jobs SET current_state=${state},updated_at=${at} WHERE job_id=${jobId}`; return state },
    async writeWatermarkDecision(d) { await client.sql`INSERT INTO coverage.watermark_eligibility_decisions(decision_id,unit_id,dataset_id,provider_id,bounded_dimensions,outcome_ids,required_unit_policy_id,eligibility_result,blocking_reasons,policy_version_id,created_at) VALUES(${d.decisionId},${d.unitId},${d.datasetId},${d.providerId},${client.sql.json(d.dimensions)},${client.sql.array([...d.outcomeIds])},${d.requiredUnitPolicyId},${d.result},${client.sql.array([...d.blockingReasons])},${d.policyVersionId},${d.createdAt})` },
    async readResumableUnits(jobId) { const rows = await client.sql<{ readonly unit_id: string }[]>`SELECT unit_id FROM control.population_units WHERE job_id=${jobId} AND current_state IN ('PENDING','RETRYABLE') AND cancellation_requested_at IS NULL ORDER BY unit_id`; return rows.map(r=>r.unit_id) },
    async reconcileJob(jobId) { const rows = await client.sql<{ readonly current_state: string; readonly event_state: string | null }[]>`SELECT j.current_state::text current_state,(SELECT next_state::text FROM control.population_job_events e WHERE e.job_id=j.job_id ORDER BY occurred_at DESC,event_id DESC LIMIT 1) event_state FROM control.population_jobs j WHERE j.job_id=${jobId}`; const reasons = !rows[0] ? ["JOB_MISSING"] : rows[0].current_state !== rows[0].event_state ? ["JOB_STATE_EVENT_MISMATCH"] : []; return { consistent: reasons.length===0,reasons } },
    async reconcileUnit(unitId) { const rows = await client.sql<{ readonly current_state: string; readonly event_state: string | null }[]>`SELECT u.current_state::text current_state,(SELECT next_state::text FROM control.population_unit_events e WHERE e.unit_id=u.unit_id ORDER BY occurred_at DESC,event_id DESC LIMIT 1) event_state FROM control.population_units u WHERE u.unit_id=${unitId}`; const reasons = !rows[0] ? ["UNIT_MISSING"] : rows[0].current_state !== rows[0].event_state ? ["UNIT_STATE_EVENT_MISMATCH"] : []; return { consistent: reasons.length===0,reasons } },
  })
}
