import { canonicalChecksum,normalizeIdentifier,normalizeIsoTimestamp } from "@/lib/data-platform/contracts"
import type { ConsistencyResultInputReference } from "@/lib/data-platform/consistency"
import type { CoreEvidenceEntry,CoreEvidencePacket,CoreEvidencePacketStatus,EvidenceAssemblyProfile,EvidenceAssemblyRequest,EvidenceBusinessIdentity,EvidenceCandidate,EvidenceCandidateRole,EvidenceConclusionCode,EvidencePacketVersionIdentity,EvidenceRequirementInput } from "./assemblyContracts"

const orderedPolicies=(items:readonly {readonly policyId:string;readonly policyVersion:string}[])=>Object.freeze([...items].map(x=>({policyId:normalizeIdentifier(x.policyId),policyVersion:x.policyVersion})).sort((a,b)=>`${a.policyId}@${a.policyVersion}`.localeCompare(`${b.policyId}@${b.policyVersion}`)))
const orderedFacts=(items:readonly ConsistencyResultInputReference[])=>Object.freeze([...items].sort((a,b)=>`${a.roleId}:${a.canonicalRecordId}:${a.recordVersion}:${a.checksum}`.localeCompare(`${b.roleId}:${b.canonicalRecordId}:${b.recordVersion}:${b.checksum}`)))
const roleFor=(profile:EvidenceAssemblyProfile,ruleId:string,ruleVersion:string,outcome:string):EvidenceCandidateRole|null=>profile.roleRules.find(r=>normalizeIdentifier(r.ruleId)===normalizeIdentifier(ruleId)&&r.ruleVersion===ruleVersion&&r.outcomes.includes(outcome as never))?.role??null
const candidateMaterial=(request:EvidenceAssemblyRequest,result:EvidenceAssemblyRequest["selections"][number]["result"],role:EvidenceCandidateRole,dependencySnapshotId:string|null)=>({subject:{subjectId:normalizeIdentifier(request.subject.subjectId),subjectType:normalizeIdentifier(request.subject.subjectType)},topic:normalizeIdentifier(request.topic),role,resultIdentity:result.resultIdentity,resultId:result.resultId,resultChecksum:result.checksum,ruleId:normalizeIdentifier(result.ruleId),ruleVersion:result.ruleVersion,ruleSetId:normalizeIdentifier(result.ruleSetId),ruleSetVersion:result.ruleSetVersion,resultOutcome:result.outcome,resultSeverity:result.severity,timeScope:normalizeTime(request),exactFacts:orderedFacts(result.inputs),policies:orderedPolicies([...result.policyBindings.comparisonPolicyReferences,{policyId:result.policyBindings.temporalPolicyId,policyVersion:result.policyBindings.temporalPolicyVersion},{policyId:result.policyBindings.severityPolicyId,policyVersion:result.policyBindings.severityPolicyVersion}]),dependencySnapshotId,diagnosticCodes:[...new Set(result.diagnostics.map(d=>d.code))].sort(),assemblyPolicy:{id:normalizeIdentifier(request.profile.assemblyPolicyId),version:request.profile.assemblyPolicyVersion}})
const normalizeTime=(request:EvidenceAssemblyRequest)=>({eventTimeStart:normalizeIsoTimestamp(request.timeScope.eventTimeStart),eventTimeEnd:normalizeIsoTimestamp(request.timeScope.eventTimeEnd),knowledgeMode:request.timeScope.knowledgeMode,knowledgeTimeCutoff:normalizeIsoTimestamp(request.timeScope.knowledgeTimeCutoff)})
export function createEvidenceCandidate(request:EvidenceAssemblyRequest,selection:EvidenceAssemblyRequest["selections"][number]):EvidenceCandidate{
  const result=selection.result,role=roleFor(request.profile,result.ruleId,result.ruleVersion,result.outcome);if(!role)throw new Error("EVIDENCE_ROLE_POLICY_MISSING")
  if(result.eventTimeWindow.start!==normalizeIsoTimestamp(request.timeScope.eventTimeStart)||result.eventTimeWindow.end!==normalizeIsoTimestamp(request.timeScope.eventTimeEnd)||result.knowledgeMode!==request.timeScope.knowledgeMode||result.knowledgeTimeCutoff!==normalizeIsoTimestamp(request.timeScope.knowledgeTimeCutoff))throw new Error("EVIDENCE_TEMPORAL_BINDING_MISMATCH")
  if(request.timeScope.knowledgeMode==="AS_KNOWN_THEN"&&result.inputs.some(i=>Date.parse(i.knowledgeAvailableAt)>Date.parse(request.timeScope.knowledgeTimeCutoff)))throw new Error("EVIDENCE_FUTURE_KNOWLEDGE_BLOCKED")
  const material=candidateMaterial(request,result,role,selection.dependencySnapshotId),candidateIdentity=canonicalChecksum(material),candidateId="ecnd_"+candidateIdentity
  return Object.freeze({candidateId,candidateIdentity,subject:Object.freeze(material.subject),topic:material.topic,role,status:role==="BLOCKING"?"BLOCKED":"ELIGIBLE",resultId:result.resultId,resultIdentity:result.resultIdentity,resultChecksum:result.checksum,ruleId:material.ruleId,ruleVersion:result.ruleVersion,ruleSetId:material.ruleSetId,ruleSetVersion:result.ruleSetVersion,resultOutcome:result.outcome,resultSeverity:result.severity,timeScope:Object.freeze(material.timeScope),exactFactReferences:material.exactFacts,policyReferences:material.policies,dependencySnapshotId:selection.dependencySnapshotId,diagnosticCodes:Object.freeze(material.diagnosticCodes),checksum:canonicalChecksum({...material,candidateIdentity})})
}
export function normalizeEvidenceCandidates(request:EvidenceAssemblyRequest):readonly EvidenceCandidate[]{const byId=new Map<string,EvidenceCandidate>();for(const selection of request.selections){const c=createEvidenceCandidate(request,selection),prior=byId.get(c.candidateIdentity);if(prior&&prior.checksum!==c.checksum)throw new Error("EVIDENCE_CANDIDATE_CONFLICT");byId.set(c.candidateIdentity,prior??c)}return Object.freeze([...byId.values()].sort((a,b)=>a.candidateIdentity.localeCompare(b.candidateIdentity)))}
export function createEvidenceBusinessIdentity(request:EvidenceAssemblyRequest):EvidenceBusinessIdentity{const material={subject:{subjectId:normalizeIdentifier(request.subject.subjectId),subjectType:normalizeIdentifier(request.subject.subjectType)},topic:normalizeIdentifier(request.topic),timeScope:normalizeTime(request),profileId:normalizeIdentifier(request.profile.profileId),profileVersion:request.profile.profileVersion,schemaVersion:request.profile.schemaVersion},evidenceBusinessIdentity=canonicalChecksum(material);return Object.freeze({evidenceBusinessIdentity,packetId:"epkt_"+evidenceBusinessIdentity})}
const entry=(candidate:EvidenceCandidate):CoreEvidenceEntry=>Object.freeze({candidateId:candidate.candidateId,resultId:candidate.resultId,resultIdentity:candidate.resultIdentity,ruleId:candidate.ruleId,ruleVersion:candidate.ruleVersion,reasonCodes:Object.freeze(candidate.diagnosticCodes),timeScope:candidate.timeScope,policyReferences:candidate.policyReferences,diagnosticCodes:candidate.diagnosticCodes,checksum:canonicalChecksum({candidateId:candidate.candidateId,resultIdentity:candidate.resultIdentity,role:candidate.role,diagnostics:candidate.diagnosticCodes})})
const reqs=<K extends EvidenceRequirementInput["kind"]>(items:readonly EvidenceRequirementInput[],kind:K):readonly (EvidenceRequirementInput&{readonly kind:K})[]=>Object.freeze(items.filter((x):x is EvidenceRequirementInput&{readonly kind:K}=>x.kind===kind).sort((a,b)=>a.requirementId.localeCompare(b.requirementId)))
export function assembleCoreEvidencePacket(request:EvidenceAssemblyRequest):CoreEvidencePacket{
  if(Date.parse(request.timeScope.eventTimeEnd)<=Date.parse(request.timeScope.eventTimeStart))throw new Error("EVIDENCE_EVENT_WINDOW_INVALID")
  const candidates=normalizeEvidenceCandidates(request),identity=createEvidenceBusinessIdentity(request),supporting=Object.freeze(candidates.filter(c=>c.role==="SUPPORTING").map(entry)),conflicting=Object.freeze(candidates.filter(c=>c.role==="CONFLICTING").map(entry)),contextual=Object.freeze(candidates.filter(c=>c.role==="CONTEXTUAL").map(entry)),blocking=Object.freeze(request.requirements.filter(r=>r.kind==="BLOCKED"))
  const missing=reqs(request.requirements,"MISSING"),unsupported=reqs(request.requirements,"UNSUPPORTED"),inapplicable=reqs(request.requirements,"INAPPLICABLE"),candidateBlocks=candidates.filter(c=>c.role==="BLOCKING")
  const conclusionCode:EvidenceConclusionCode=inapplicable.length&&!candidates.length?"NOT_APPLICABLE":blocking.length||candidateBlocks.length?"EVIDENCE_BLOCKED":missing.length||unsupported.length?"EVIDENCE_INSUFFICIENT":supporting.length&&conflicting.length?"EVIDENCE_MIXED":conflicting.length?"EVIDENCE_CONFLICTS":supporting.length?"EVIDENCE_SUPPORTS":"EVIDENCE_INSUFFICIENT"
  const status:CoreEvidencePacketStatus=conclusionCode==="NOT_APPLICABLE"?"NOT_APPLICABLE":conclusionCode==="EVIDENCE_BLOCKED"?"BLOCKED":conclusionCode==="EVIDENCE_INSUFFICIENT"?"INSUFFICIENT":"ELIGIBLE"
  const resultReferences=Object.freeze(candidates.map(c=>Object.freeze({candidateId:c.candidateId,resultId:c.resultId,resultIdentity:c.resultIdentity,factReferences:c.exactFactReferences,checksum:canonicalChecksum({candidateId:c.candidateId,resultId:c.resultId,resultIdentity:c.resultIdentity,facts:c.exactFactReferences})})))
  const factReferences=orderedFacts(candidates.flatMap(c=>c.exactFactReferences).filter((fact,index,all)=>all.findIndex(x=>x.roleId===fact.roleId&&x.canonicalRecordId===fact.canonicalRecordId&&x.recordVersion===fact.recordVersion&&x.checksum===fact.checksum)===index))
  const lineage=Object.freeze([...candidates.flatMap(c=>[{lineageType:"PACKET_TO_CANDIDATE" as const,fromId:identity.packetId,toId:c.candidateId},{lineageType:"CANDIDATE_TO_RESULT" as const,fromId:c.candidateId,toId:c.resultId},...c.exactFactReferences.map(f=>({lineageType:"RESULT_TO_FACT" as const,fromId:c.resultId,toId:`${f.canonicalRecordId}:${f.recordVersion}`}))]),{lineageType:"PACKET_TO_PROFILE" as const,fromId:identity.packetId,toId:`${normalizeIdentifier(request.profile.profileId)}@${request.profile.profileVersion}`}].map(x=>Object.freeze({...x,checksum:canonicalChecksum(x)})).sort((a,b)=>a.checksum.localeCompare(b.checksum)))
  const base={...identity,subject:Object.freeze({subjectId:normalizeIdentifier(request.subject.subjectId),subjectType:normalizeIdentifier(request.subject.subjectType)}),topic:normalizeIdentifier(request.topic),timeScope:Object.freeze(normalizeTime(request)),profileId:normalizeIdentifier(request.profile.profileId),profileVersion:request.profile.profileVersion,assemblyPolicyId:normalizeIdentifier(request.profile.assemblyPolicyId),assemblyPolicyVersion:request.profile.assemblyPolicyVersion,selectionPolicyReferences:orderedPolicies(request.profile.selectionPolicyReferences),conclusionPolicyId:normalizeIdentifier(request.profile.conclusionPolicyId),conclusionPolicyVersion:request.profile.conclusionPolicyVersion,candidates,supportingEvidence:supporting,conflictingEvidence:conflicting,contextualEvidence:contextual,missingEvidence:missing,unsupportedEvidence:unsupported,inapplicableEvidence:inapplicable,blockingConditions:blocking,resultReferences,factReferences,lineageReferences:lineage,conclusionCode,uncertaintyReasonCodes:Object.freeze([...new Set([...request.requirements.map(r=>r.reasonCode),...(conflicting.length?["CONFLICTING_EVIDENCE_PRESENT"]:[])])].sort()),status,schemaVersion:request.profile.schemaVersion}
  const packetChecksum=canonicalChecksum(base),packetVersionIdentity=canonicalChecksum({businessIdentity:identity.evidenceBusinessIdentity,candidateIdentities:candidates.map(c=>c.candidateIdentity),resultIdentities:candidates.map(c=>c.resultIdentity).sort(),factVersions:factReferences.map(f=>({roleId:f.roleId,canonicalRecordId:f.canonicalRecordId,recordVersion:f.recordVersion,checksum:f.checksum})),assemblyPolicyVersion:request.profile.assemblyPolicyVersion,selectionPolicies:base.selectionPolicyReferences,schemaVersion:base.schemaVersion,packetChecksum}),version:EvidencePacketVersionIdentity={packetVersionIdentity,packetVersionId:"epvr_"+packetVersionIdentity}
  return Object.freeze({...base,...version,packetChecksum,createdAt:normalizeIsoTimestamp(request.createdAt)})
}
