import assert from "node:assert/strict"
import { canonicalChecksum } from "@/lib/data-platform/contracts"
import { createServingReplaySnapshot, verifyReplaySnapshot } from "@/lib/data-platform/mvp-serving"
import { inspectMvpServingIsolatedTarget } from "@/lib/data-platform/mvp-serving/safety"

const projection = Object.freeze({ projectionId:"p",projectionVersionId:"pv",projectionVersionIdentity:"pvi",projectionKind:"ReplayTimelineProjection" as const,subjectId:"BTCUSDT",eventTimeStart:"2026-07-15T00:00:00.000Z",eventTimeEnd:"2026-07-16T00:00:00.000Z",knowledgeTimeCutoff:"2026-07-16T00:00:00.000Z",dependencyDigest:"a".repeat(64),generatorId:"mvp-consumer-projection-generator" as const,generatorVersion:"1.0.0" as const,schemaVersion:"1.0.0" as const,structuredPayload:{},completeness:"COMPLETE" as const,limitations:Object.freeze([]),lifecycleState:"GENERATED" as const,consumerExposureState:"READY_FOR_CUTOVER" as const,supersedesProjectionVersionId:null,dependencies:Object.freeze([]),projectionChecksum:"b".repeat(64),createdAt:"2026-07-16T00:00:00.000Z" })
const base={status:"AVAILABLE" as const,modelVersion:"mvp-replay-sequence/1.0.0" as const,instrument:"BTCUSDT",eventTimeStart:projection.eventTimeStart,eventTimeEnd:projection.eventTimeEnd,sourceProjectionVersionId:projection.projectionVersionId,sourceProjectionChecksum:projection.projectionChecksum,marketState:"NEUTRAL",evidencePacketId:"ep",price:Object.freeze(Array.from({length:288},(_,i)=>({eventTime:new Date(Date.parse(projection.eventTimeStart)+i*300000).toISOString(),value:1,open:1,high:1,low:1,close:1,volume:0,sourceChecksum:"c".repeat(64)}))),openInterest:Object.freeze(Array.from({length:288},(_,i)=>({eventTime:new Date(Date.parse(projection.eventTimeStart)+i*300000).toISOString(),value:1,sourceChecksum:"d".repeat(64)}))),funding:Object.freeze([0,8,16].map((h)=>({eventTime:`2026-07-15T${String(h).padStart(2,"0")}:00:00.000Z`,value:0,providerId:"binance",sourceChecksum:"e".repeat(64)}))),flow:Object.freeze(Array.from({length:48},(_,i)=>({bucketId:`b${i}`,eventTime:new Date(Date.parse(projection.eventTimeStart)+i*1800000).toISOString(),bucketEnd:new Date(Date.parse(projection.eventTimeStart)+(i+1)*1800000).toISOString(),aggressiveBuyQuantity:"0",aggressiveSellQuantity:"0",imbalanceRatio:null,tradeCount:0}))),sequence:Object.freeze([]),sampleCounts:Object.freeze({price:288,openInterest:288,funding:3,flow:48}),limitations:Object.freeze([])}
const model=Object.freeze({...base,modelChecksum:canonicalChecksum(base)}),snapshot=createServingReplaySnapshot(projection,model)
assert.equal(verifyReplaySnapshot(snapshot),true)
assert.equal(createServingReplaySnapshot(projection,model).snapshotChecksum,snapshot.snapshotChecksum)
assert.notEqual(canonicalChecksum({...base,instrument:"ETHUSDT"}),model.modelChecksum)
assert.throws(()=>createServingReplaySnapshot(projection,{...model,sourceProjectionVersionId:"wrong"}),/SERVING_REPLAY_SOURCE_MISMATCH/)
assert.equal(inspectMvpServingIsolatedTarget("postgresql://review_role:secret@127.0.0.1:5432/quantterminal_mvp8h_canary_replay_test",{}, { database:"quantterminal_mvp8h_canary_replay_test",role:"review_role" }).safe,true)
assert.equal(inspectMvpServingIsolatedTarget("postgresql://review_role:secret@127.0.0.1:5432/quantterminal_mvp8h_other_test",{}, { database:"quantterminal_mvp8h_other_test",role:"review_role" }).safe,false)
process.stdout.write(JSON.stringify({status:"PASS",deterministic:true,checksum:snapshot.modelChecksum}))
