import React from "react"
import { MetricCard } from "@/components/evidence"
import { AvailabilityBadge, StatePanel } from "@/components/feedback"
import { Badge } from "@/components/ui/foundation"
import type { DerivativesIntelligenceViewModel } from "@/lib/markets-presentation/contracts"

function number(value: number | null) { return value === null ? "UNAVAILABLE" : value.toLocaleString() }
export function DerivativesIntelligenceSection({ model, realtimeDetail }: { readonly model: DerivativesIntelligenceViewModel; readonly realtimeDetail?: React.ReactNode }) {
  return <section aria-labelledby="derivatives-title" className="grid gap-4"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-semibold uppercase text-[var(--qt-color-evidence)]">Derivatives Intelligence</p><h2 id="derivatives-title" className="mt-1 text-lg font-semibold">Factual metrics and qualified interpretation</h2></div><AvailabilityBadge availability={model.availability} /></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{model.metrics.map((item) => <MetricCard key={item.id} metric={item} />)}</div><div className="grid gap-3 md:grid-cols-2">{model.venues.map((venue) => <article key={venue.id} className="grid gap-3 rounded-[var(--qt-radius-card)] border border-[var(--qt-color-border)] bg-[var(--qt-color-surface)] p-[var(--qt-space-4)]"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{venue.name}</h3><AvailabilityBadge availability={venue.availability} /></div><p className="text-sm">Funding: {number(venue.fundingRate)}</p><p className="text-sm">OI notional: {number(venue.openInterestNotional)}</p><p className="text-xs text-[var(--qt-color-text-muted)]">Source: {venue.source ?? "UNAVAILABLE"}</p>{venue.limitation ? <p className="text-xs text-[var(--qt-color-warning)]">{venue.limitation}</p> : null}</article>)}</div>{model.relationships.length ? <div className="grid gap-2 sm:grid-cols-2">{model.relationships.map((item) => <p key={item.label} className="rounded-[var(--qt-radius-card)] border border-[var(--qt-color-border)] p-3 text-sm">{item.label}: {item.value ?? "UNAVAILABLE"}</p>)}</div> : null}<div className="grid gap-3 md:grid-cols-3">{model.heuristics.map((item) => item.available && item.value ? <article key={item.id} className="grid gap-2 rounded-[var(--qt-radius-card)] border border-[var(--qt-color-warning)] bg-[var(--qt-color-surface)] p-3"><Badge tone="warning">{item.qualification.replaceAll("_", " ")}</Badge><h3 className="text-sm font-semibold">{item.label}: {item.value}</h3><p className="text-xs text-[var(--qt-color-text-muted)]">Basis: {item.basis}</p></article> : <StatePanel key={item.id} state="PARTIAL" title={`${item.label} UNAVAILABLE`} reason={item.basis} />)}</div><p className="text-xs text-[var(--qt-color-warning)]">{model.limitation}</p>{realtimeDetail ? <div className="grid gap-3">{realtimeDetail}</div> : null}</section>
}
