import React from "react"
import { MetricCard } from "@/components/evidence"
import { AvailabilityBadge, FreshnessIndicator, StatePanel } from "@/components/feedback"
import { Badge } from "@/components/ui/foundation"
import type { MarketsSummaryViewModel } from "@/lib/markets-presentation/contracts"

export function GlobalSummarySection({ model }: { readonly model: MarketsSummaryViewModel }) {
  return <section aria-labelledby="markets-summary-title" className="grid gap-4"><div><p className="text-xs font-semibold uppercase text-[var(--qt-color-evidence)]">Global Market Summary</p><h2 id="markets-summary-title" className="mt-1 text-lg font-semibold">Factual inputs and source readiness</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{model.metrics.map((item) => <MetricCard key={item.id} metric={item} />)}</div><div className="grid gap-3 lg:grid-cols-2"><article className="grid gap-3 rounded-[var(--qt-radius-card)] border border-[var(--qt-color-border)] bg-[var(--qt-color-surface)] p-[var(--qt-space-4)]"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">Source Readiness</h3><Badge tone={model.sourceReadiness.label === "AVAILABLE" ? "success" : model.sourceReadiness.label === "PARTIAL" ? "warning" : "neutral"}>{model.sourceReadiness.label}</Badge></div><p className="text-2xl font-semibold">{model.sourceReadiness.availableModules} / {model.sourceReadiness.totalModules}</p><p className="text-xs text-[var(--qt-color-text-muted)]">{model.sourceReadiness.basis}</p></article><StatePanel state={model.regime.lifecycle} title="Market Regime UNAVAILABLE" reason={model.regime.reason} /></div><article className="grid gap-3 rounded-[var(--qt-radius-card)] border border-[var(--qt-color-border)] bg-[var(--qt-color-surface)] p-[var(--qt-space-4)]"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">Inherited Dashboard Context</h3><AvailabilityBadge availability={model.inheritedContext.availability} /></div><div className="grid gap-2 sm:grid-cols-3"><p className="text-sm">Direction: {model.inheritedContext.direction ?? "UNAVAILABLE"}</p><p className="text-sm">Drivers: {model.inheritedContext.driverCount ?? "UNAVAILABLE"}</p><p className="text-sm">Evidence: {model.inheritedContext.evidenceCount ?? "UNAVAILABLE"}</p></div><FreshnessIndicator freshness={model.inheritedContext.freshness} /><p className="text-xs text-[var(--qt-color-warning)]">{model.inheritedContext.limitation}</p></article></section>
}
