import React from "react"
import { MetricCard } from "@/components/evidence"
import { AvailabilityBadge, FreshnessIndicator, ProvenanceLabel, StatePanel } from "@/components/feedback"
import { Badge } from "@/components/ui/foundation"
import type { SectorRotationViewModel } from "@/lib/markets-presentation/contracts"

export function SectorRotationSection({ model }: { readonly model: SectorRotationViewModel }) {
  return <section aria-labelledby="sector-rotation-title" className="grid gap-4"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-semibold uppercase text-[var(--qt-color-evidence)]">Sector Rotation</p><h2 id="sector-rotation-title" className="mt-1 text-lg font-semibold">Source-model rankings</h2></div><div className="flex gap-2"><AvailabilityBadge availability={model.availability} /><Badge tone="neutral">Coverage {model.coverage.state}</Badge></div></div>{model.sectors.length ? <div className="grid gap-3">{model.sectors.map((sector) => <article key={sector.id} className="grid gap-4 rounded-[var(--qt-radius-card)] border border-[var(--qt-color-border)] bg-[var(--qt-color-surface)] p-[var(--qt-space-4)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-[var(--qt-color-text-muted)]">Source rank #{sector.rank}</p><h3 className="mt-1 text-base font-semibold">{sector.sector}</h3></div><div className="flex flex-wrap gap-2"><Badge tone="info">Score {sector.score.toFixed(1)}</Badge><Badge tone="warning">MODEL CLASSIFICATION: {sector.modelClassification}</Badge></div></div><p className="text-xs text-[var(--qt-color-warning)]">{sector.classificationBasis}</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{sector.metrics.map((item) => <MetricCard key={item.id} metric={item} />)}</div><p className="text-sm text-[var(--qt-color-text-secondary)]">Supplied leaders: {sector.topSymbols.length ? sector.topSymbols.join(", ") : "UNAVAILABLE"}</p><ul className="grid gap-1 text-xs text-[var(--qt-color-text-muted)]">{sector.limitations.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div> : <StatePanel state={model.lifecycle} title="Sector Rotation" reason={model.availability.reason ?? model.limitation} />}<div className="flex flex-wrap gap-3"><FreshnessIndicator freshness={model.freshness} />{model.provenance ? <ProvenanceLabel provenance={model.provenance} /> : null}</div><p className="text-xs text-[var(--qt-color-warning)]">{model.limitation}</p></section>
}
