import type { InformationItem, InformationSource } from "./informationTypes"
import type { InformationSourceProvider } from "./informationSourceTypes"
import { informationSourceClassifications } from "./informationSourceTypes"

const NOW = "2026-06-08T00:00:00.000Z"

function source(provider: InformationSourceProvider): InformationSource {
  const classification = informationSourceClassifications.find((item) => item.provider === provider)
  return {
    id: `source-${provider}`,
    provider,
    category: classification?.category ?? "news",
    displayName: classification?.displayName ?? provider,
    verificationMode: classification?.verificationMode ?? "unverified",
    reputationScore: classification?.defaultReputationScore ?? 45,
  }
}

export interface InformationRepositoryQuery {
  symbol?: string
  provider?: InformationSourceProvider
  narrativeTag?: string
  limit?: number
}

export const mockInformationItems: InformationItem[] = [
  {
    id: "info-coinness-btc-etf-headline",
    source: source("coinness"),
    title: "Coinness flags renewed BTC ETF inflow momentum",
    summary: "Fast crypto news headline says ETF desk flows are being watched after a stronger inflow print.",
    symbol: "BTC",
    assetTags: ["BTC", "ETF"],
    narrativeTags: ["etf_flow", "institutional_demand"],
    topicTags: ["spot_etf", "flows", "bitcoin"],
    publishedAt: "2026-06-08T08:15:00.000Z",
    firstSeenAt: "2026-06-08T08:16:00.000Z",
    ingestedAt: NOW,
    status: "normalized",
    timeSensitivity: "hours",
    sourceUrl: "mock://coinness/btc-etf-headline",
    metadata: {
      mentions: 18,
      velocity: 42,
      spread: 36,
      crossPlatformPresence: 28,
      priceImpact: 52,
      volumeImpact: 60,
      volatilityImpact: 44,
      sentimentImpact: 58,
      noveltyState: "known",
      corroboration: 55,
      consistency: 72,
      historicalAccuracy: 66,
    },
  },
  {
    id: "info-x-viral-exchange-rumor",
    source: source("x"),
    title: "Viral X rumor claims major exchange listing is imminent",
    summary: "A high-engagement social post claims an exchange listing before any official confirmation.",
    symbol: "ALT",
    assetTags: ["ALT"],
    narrativeTags: ["exchange_listing", "rumor"],
    topicTags: ["listing", "social_viral", "unconfirmed"],
    publishedAt: "2026-06-08T09:05:00.000Z",
    firstSeenAt: "2026-06-08T09:05:30.000Z",
    ingestedAt: NOW,
    status: "normalized",
    timeSensitivity: "minutes",
    sourceUrl: "mock://x/exchange-listing-rumor",
    metadata: {
      mentions: 240,
      velocity: 92,
      spread: 86,
      crossPlatformPresence: 64,
      priceImpact: 48,
      volumeImpact: 72,
      volatilityImpact: 78,
      sentimentImpact: 62,
      noveltyState: "new",
      corroboration: 12,
      consistency: 34,
      historicalAccuracy: 38,
    },
  },
  {
    id: "info-reddit-discussion-spike",
    source: source("reddit"),
    title: "Reddit discussion spike debates ETH staking ETF odds",
    summary: "Community activity rises around whether staking will be included in future ETH ETF products.",
    symbol: "ETH",
    assetTags: ["ETH", "ETF"],
    narrativeTags: ["staking_etf", "crypto_policy"],
    topicTags: ["reddit", "discussion", "ethereum"],
    publishedAt: "2026-06-08T10:20:00.000Z",
    firstSeenAt: "2026-06-08T10:22:00.000Z",
    ingestedAt: NOW,
    status: "normalized",
    timeSensitivity: "days",
    sourceUrl: "mock://reddit/eth-staking-etf",
    metadata: {
      mentions: 128,
      velocity: 66,
      spread: 52,
      crossPlatformPresence: 38,
      priceImpact: 24,
      volumeImpact: 32,
      volatilityImpact: 28,
      sentimentImpact: 46,
      noveltyState: "known",
      corroboration: 28,
      consistency: 52,
      historicalAccuracy: 44,
    },
  },
  {
    id: "info-polymarket-probability-shift",
    source: source("polymarket"),
    title: "Polymarket odds shift toward BTC ETF inflow continuation",
    summary: "Prediction market probability moves higher on continued ETF inflow expectations.",
    symbol: "BTC",
    assetTags: ["BTC", "ETF"],
    narrativeTags: ["prediction_market", "etf_flow"],
    topicTags: ["polymarket", "odds", "flows"],
    publishedAt: "2026-06-08T11:00:00.000Z",
    firstSeenAt: "2026-06-08T11:00:00.000Z",
    ingestedAt: NOW,
    status: "normalized",
    timeSensitivity: "hours",
    sourceUrl: "mock://polymarket/btc-etf-inflow",
    metadata: {
      mentions: 42,
      velocity: 58,
      spread: 46,
      crossPlatformPresence: 42,
      priceImpact: 44,
      volumeImpact: 40,
      volatilityImpact: 36,
      sentimentImpact: 54,
      noveltyState: "known",
      corroboration: 64,
      consistency: 74,
      historicalAccuracy: 70,
      probabilityChange: 11,
    },
  },
  {
    id: "info-etf-flow-update",
    source: source("etf_flow"),
    title: "BTC ETF daily net flow update shows persistent demand",
    summary: "Flow tracker shows another positive net inflow day after a week of mixed demand.",
    symbol: "BTC",
    assetTags: ["BTC", "ETF"],
    narrativeTags: ["etf_flow", "institutional_demand"],
    topicTags: ["flows", "institutional", "spot_etf"],
    publishedAt: "2026-06-08T12:30:00.000Z",
    firstSeenAt: "2026-06-08T12:35:00.000Z",
    ingestedAt: NOW,
    status: "normalized",
    timeSensitivity: "days",
    sourceUrl: "mock://etf-flow/btc-daily-flow",
    metadata: {
      mentions: 34,
      velocity: 48,
      spread: 40,
      crossPlatformPresence: 34,
      priceImpact: 58,
      volumeImpact: 62,
      volatilityImpact: 34,
      sentimentImpact: 62,
      noveltyState: "known",
      corroboration: 76,
      consistency: 80,
      historicalAccuracy: 78,
    },
  },
  {
    id: "info-exchange-listing-announcement",
    source: source("exchange_announcement"),
    title: "Official exchange announcement confirms new perpetual listing",
    summary: "Exchange announcement confirms listing timing and market details for a new perpetual contract.",
    symbol: "ALT",
    assetTags: ["ALT"],
    narrativeTags: ["exchange_listing", "liquidity"],
    topicTags: ["official", "listing", "perpetual"],
    publishedAt: "2026-06-08T13:00:00.000Z",
    firstSeenAt: "2026-06-08T13:01:00.000Z",
    ingestedAt: NOW,
    status: "normalized",
    timeSensitivity: "hours",
    sourceUrl: "mock://exchange/listing-announcement",
    metadata: {
      mentions: 72,
      velocity: 70,
      spread: 62,
      crossPlatformPresence: 46,
      priceImpact: 66,
      volumeImpact: 82,
      volatilityImpact: 74,
      sentimentImpact: 68,
      noveltyState: "new",
      corroboration: 86,
      consistency: 88,
      historicalAccuracy: 84,
    },
  },
  {
    id: "info-macro-calendar-surprise",
    source: source("macro_calendar"),
    title: "Macro calendar surprise: CPI print lands above consensus",
    summary: "Inflation data surprises to the upside, shifting rate expectation and risk appetite narratives.",
    symbol: "BTC",
    assetTags: ["BTC", "ETH", "NASDAQ"],
    narrativeTags: ["macro", "cpi", "rates"],
    topicTags: ["macro_calendar", "inflation", "risk_assets"],
    publishedAt: "2026-06-08T14:00:00.000Z",
    firstSeenAt: "2026-06-08T14:00:00.000Z",
    ingestedAt: NOW,
    status: "normalized",
    timeSensitivity: "minutes",
    sourceUrl: "mock://macro/cpi-surprise",
    metadata: {
      mentions: 180,
      velocity: 88,
      spread: 82,
      crossPlatformPresence: 76,
      priceImpact: 74,
      volumeImpact: 70,
      volatilityImpact: 86,
      sentimentImpact: 78,
      noveltyState: "new",
      corroboration: 92,
      consistency: 90,
      historicalAccuracy: 86,
    },
  },
]

export function listMockInformationItems(query: InformationRepositoryQuery = {}) {
  return mockInformationItems
    .filter((item) => !query.symbol || item.assetTags.includes(query.symbol) || item.symbol === query.symbol)
    .filter((item) => !query.provider || item.source.provider === query.provider)
    .filter((item) => !query.narrativeTag || item.narrativeTags.includes(query.narrativeTag))
    .slice(0, query.limit ?? mockInformationItems.length)
}

export function getMockInformationItem(id: string) {
  return mockInformationItems.find((item) => item.id === id) ?? null
}

