import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import path from "node:path"
import { canonicalChecksum } from "@/lib/data-platform/contracts"
import {
  ConsistencyRuleRegistry, RuleEvaluationRuntime, analyzeImpact, createDependencyEdge, createDependencyNode,
  createDependencySnapshot, createRecomputePlan, createRecomputeRequest, reconcileConsistencyResult,
  reconcileConsistencyRun, reconcileDependency, selectConsistencyResult,
  type ConsistencyInputReference, type ConsistencyRunCompletionSummary, type ConsistencyRunTransitionCommand,
  type DependencyNode, type RuleMetadata,
} from "@/lib/data-platform/consistency"
import {
  ConsistencyDependencyStore, ConsistencyMigrationRunner, ConsistencyPostgresRuntime, ConsistencyResultStore,
  ConsistencyRunStore, D4_MIGRATION_ORDER, D4_MIGRATION_ROOT, discoverD4Migrations, resetD4Runtime, verifyEnvironment,
} from "@/lib/data-platform/consistency-evidence/postgres"
import { createResultFixture, RESULT_FIXTURE_CUTOFF, RESULT_FIXTURE_END, RESULT_FIXTURE_START, temporalFact } from "../results/fixtures"

const T0="2026-02-01T01:00:00.000Z",T1="2026-02-01T01:01:00.000Z",T2="2026-02-01T01:02:00.000Z",T3="2026-02-01T01:03:00.000Z"

async function main(){
  const env={D4_ISOLATED_POSTGRES_URL:process.env.D4_ISOLATED_POSTGRES_URL,D2_ISOLATED_POSTGRES_URL:process.env.D2_ISOLATED_POSTGRES_URL,D3_ISOLATED_POSTGRES_URL:process.env.D3_ISOLATED_POSTGRES_URL,DATABASE_URL:process.env.DATABASE_URL}
  const target=verifyEnvironment(env);console.log(JSON.stringify({host:target.host,port:target.port,database:target.database,sslMode:target.sslMode,safe:target.safe}))
  const owner=new ConsistencyPostgresRuntime({connectionString:env.D4_ISOLATED_POSTGRES_URL!,environment:env,roleIntent:"MIGRATION_OWNER",maxConnections:2,connectTimeoutSeconds:10,idleTimeoutSeconds:30,statementTimeoutMs:20_000,lockTimeoutMs:5_000,idleTransactionTimeoutMs:15_000,applicationName:"d4-phase2v-owner"})
  const worker=new ConsistencyPostgresRuntime({connectionString:env.D4_ISOLATED_POSTGRES_URL!,environment:env,roleIntent:"CONSISTENCY_WORKER",maxConnections:4,connectTimeoutSeconds:10,idleTimeoutSeconds:30,applicationName:"d4-phase2v-worker"})
  const verifier=new ConsistencyPostgresRuntime({connectionString:env.D4_ISOLATED_POSTGRES_URL!,environment:env,roleIntent:"READ_ONLY",maxConnections:1,connectTimeoutSeconds:10,idleTimeoutSeconds:30,applicationName:"d4-phase2v-verifier"})
  const checks:Array<[string,boolean,string?]>=[],check=(name:string,pass:boolean,detail?:string)=>checks.push([name,pass,detail]);let failureRoot:string|null=null
  try{
    const db=await owner.connect();console.log(JSON.stringify({postgresVersion:db.serverVersion}));check("isolated target",db.database==="quantterminal_d4_isolated"&&!db.d3PopulationSchemaPresent)
    const d2Before=await owner.sql.unsafe<{present:boolean}[]>("SELECT to_regclass('control.canonical_commits') IS NOT NULL present")
    await resetD4Runtime(owner,{explicitOptIn:"RESET_D4_ISOLATED_DATABASE",auditIdentity:"d4-phase2v-interrupted"})
    failureRoot=await mkdtemp(path.join(tmpdir(),"qt-d4-phase2v-"));await cp(D4_MIGRATION_ROOT,failureRoot,{recursive:true});const last=path.join(failureRoot,D4_MIGRATION_ORDER.at(-1)!);await writeFile(last,(await readFile(last,"utf8"))+"\nSELECT d4_phase2v_missing_function();\n","utf8")
    const interrupted=await new ConsistencyMigrationRunner(owner,failureRoot).apply("d4-phase2v-interrupted");check("interrupted migration fails closed",interrupted.at(-1)?.status==="FAILED")
    const interruptedState=await owner.sql.unsafe<{ledger:number;evidencePacket:string|null}[]>("SELECT (SELECT count(*)::int FROM d4_control.migration_ledger) ledger,to_regclass('evidence.core_packet_versions')::text \"evidencePacket\"")
    check("interrupted migration has no false ledger",interruptedState[0]?.ledger===D4_MIGRATION_ORDER.length-1&&!interruptedState[0]?.evidencePacket)
    await resetD4Runtime(owner,{explicitOptIn:"RESET_D4_ISOLATED_DATABASE",auditIdentity:"d4-phase2v-fresh"})
    const migrations=await new ConsistencyMigrationRunner(owner).apply("d4-phase2v");check("fresh migration chain",migrations.length===D4_MIGRATION_ORDER.length&&migrations.every(x=>x.status==="APPLIED"))
    const rerun=await new ConsistencyMigrationRunner(owner).apply("d4-phase2v");check("migration rerun stable",rerun.every(x=>x.status==="SKIPPED"))
    const artifacts=await discoverD4Migrations(),lastArtifact=artifacts.at(-1)!;await owner.sql.unsafe("UPDATE d4_control.migration_ledger SET migration_checksum=repeat('f',64) WHERE migration_id=$1",[lastArtifact.migrationId]);const drift=await new ConsistencyMigrationRunner(owner).apply("d4-phase2v");check("migration checksum drift rejected",drift.at(-1)?.status==="FAILED");await owner.sql.unsafe("UPDATE d4_control.migration_ledger SET migration_checksum=$2 WHERE migration_id=$1",[lastArtifact.migrationId,lastArtifact.checksum])
    const d2After=await owner.sql.unsafe<{present:boolean}[]>("SELECT to_regclass('control.canonical_commits') IS NOT NULL present");check("native reset preserves D2 foundation",Boolean(d2Before[0]?.present&&d2After[0]?.present))
    await seedGovernance(owner);await worker.connect();await verifier.connect()
    const workerSession=await worker.sql.unsafe<{role:string;statement:string;lock:string;idle:string}[]>("SELECT current_user role,current_setting('statement_timeout') statement,current_setting('lock_timeout') lock,current_setting('idle_in_transaction_session_timeout') idle")
    check("worker physical role",workerSession[0]?.role==="qt_d4_consistency_worker")
    check("bounded database timeouts",workerSession[0]?.statement==="15s"&&workerSession[0]?.lock==="5s"&&workerSession[0]?.idle==="15s")
    check("verifier physical role",(await verifier.sql.unsafe<{role:string}[]>("SELECT current_user role"))[0]?.role==="qt_d4_read_only")

    const factV1=temporalFact("result-a","left",1),other=temporalFact("result-b","right",1),v1Request=createResultFixture({inputs:[factV1,other]})
    const evaluated=evaluateFixture(factV1);check("bounded Rule evaluated",evaluated.status==="EVALUATED"&&evaluated.outcome==="CONSISTENT")
    const runStore=new ConsistencyRunStore(worker),resultStore=new ConsistencyResultStore(worker),dependencyStore=new ConsistencyDependencyStore(worker)
    const runRace=await Promise.all([runStore.create(v1Request.runSpecification),runStore.create(v1Request.runSpecification)]);check("concurrent Run dedupe",runRace.filter(x=>x.status==="CREATED").length===1&&runRace.filter(x=>x.status==="DUPLICATE").length===1,runRace.map(x=>x.status).join(","))
    const runConflict=await runStore.create({...v1Request.runSpecification,specificationChecksum:"f".repeat(64)});check("Run conflict distinct",runConflict.status==="CONFLICT")
    const registryBinding=await worker.sql.unsafe<{rule_set_id:string;definition_checksum:string}[]>("SELECT rule_set_id,definition_checksum FROM consistency.rule_sets WHERE rule_set_id=$1 AND rule_set_version=$2",[v1Request.runSpecification.ruleSetId,v1Request.runSpecification.ruleSetVersion]);check("Run registry binding",registryBinding[0]?.definition_checksum===v1Request.runSpecification.ruleRegistryChecksum,JSON.stringify({expectedId:v1Request.runSpecification.ruleSetId,expectedChecksum:v1Request.runSpecification.ruleRegistryChecksum,actual:registryBinding[0]??null}))
    const persistedBinding=await worker.sql.unsafe<{ok:boolean;rule_set_id:string;rule_set_version:string;rule_registry_checksum:string;policy_version_id:string;policy_exists:boolean}[]>("SELECT s.rule_set_id,s.rule_set_version,s.rule_registry_checksum,rs.policy_version_id,EXISTS(SELECT 1 FROM control.policy_versions pv WHERE pv.policy_version_id=rs.policy_version_id) policy_exists,(rs.definition_checksum=s.rule_registry_checksum AND rs.state='APPROVED' AND EXISTS(SELECT 1 FROM control.policy_versions pv WHERE pv.policy_version_id=rs.policy_version_id)) ok FROM consistency.run_specifications s JOIN consistency.rule_sets rs ON rs.rule_set_id=s.rule_set_id AND rs.rule_set_version=s.rule_set_version WHERE s.run_id=$1",[v1Request.runSpecification.runId]);check("persisted Run registry binding",Boolean(persistedBinding[0]?.ok),JSON.stringify(persistedBinding[0]??null))
    const start=command(v1Request.runSpecification,"RUNNING","start-v1",null),startRace=await Promise.all([runStore.transition(start),runStore.transition(start)]);check("concurrent Run start",startRace.filter(x=>x.status==="TRANSITIONED").length===1,startRace.map(x=>x.status+(x.status==="REJECTED"?":"+x.failure:"")).join(","))
    const resultRace=await Promise.all([resultStore.write(v1Request),resultStore.write(v1Request)]);check("concurrent Result dedupe",resultRace.filter(x=>x.status==="CREATED").length===1&&resultRace.filter(x=>x.status==="DUPLICATE").length===1)
    const v1Result=resultRace.find(x=>x.status==="CREATED")!;if(v1Result.status!=="CREATED")throw new Error("V1_RESULT_MISSING")
    const resultConflict=await resultStore.write({...v1Request,outcome:"INCONSISTENT"});check("Result conflict distinct",resultConflict.status==="CONFLICT")
    const complete=command(v1Request.runSpecification,"COMPLETED","complete-v1",summary(v1Request.runSpecification.runId));const terminalRace=await Promise.all([runStore.transition(complete),runStore.transition(complete)]);check("one Run terminal event",terminalRace.filter(x=>x.status==="TRANSITIONED").length===1,terminalRace.map(x=>x.status+(x.status==="REJECTED"?":"+x.failure:"")).join(","))
    check("Run event reconciliation",reconcileConsistencyRun(await runStore.read(v1Request.runSpecification.runId),await runStore.events(v1Request.runSpecification.runId)).consistent)
    const v1Lookup=await resultStore.lookup(v1Result.result.resultIdentity);check("Result reconciliation",v1Lookup.status==="FOUND"&&reconcileConsistencyResult(v1Lookup.result,v1Request,v1Lookup.runReferences,await resultStore.conflicts(v1Result.result.resultIdentity)).consistent)

    const oldGraph=graph(v1Result.result.resultId,"1"),oldSnapshot=createDependencySnapshot(oldGraph.nodes,oldGraph.edges,"phase2v-v1",true,[],T0);await dependencyStore.persistSnapshot(oldSnapshot)
    const factV2=temporalFact("result-a","left",2,T1),v2Request=createResultFixture({inputs:[factV2,other],knowledgeMode:"LATEST_CORRECTED",cutoff:T2}),v2Graph=graph(v1Result.result.resultId,"2"),v2Snapshot=createDependencySnapshot(v2Graph.nodes,v2Graph.edges,"phase2v-v2",true,[],T1);await dependencyStore.persistSnapshot(v2Snapshot)
    const impact=analyzeImpact({changedNode:v2Graph.fact,replacedNodeId:oldGraph.fact.nodeId,reason:"FACT_CORRECTED",snapshot:oldSnapshot,maxDepth:16,requestedAt:T1});check("correction impact deterministic",impact.traversal==="COMPLETE"&&impact.directlyAffectedNodeIds.length>0)
    const recompute=createRecomputeRequest(impact,{eventTimeStart:RESULT_FIXTURE_START,eventTimeEnd:RESULT_FIXTURE_END,knowledgeMode:"LATEST_CORRECTED",knowledgeTimeCutoff:T2,recomputePolicyVersion:"1",targetResultIds:[v1Result.result.resultId],targetSnapshotId:v2Snapshot.snapshotId,createdAt:T1}),plan=createRecomputePlan(recompute,v2Snapshot,impact,T1)
    const recomputeRace=await Promise.all([dependencyStore.persistRecompute(recompute,plan),dependencyStore.persistRecompute(recompute,plan)]);check("concurrent recompute dedupe",recomputeRace.filter(x=>x.status==="CREATED").length===1&&recomputeRace.filter(x=>x.status==="DUPLICATE").length===1)
    check("unaffected Rule skipped",plan.skippedNodeIds.length===0&&plan.steps.length===2)
    const first=plan.steps[0]!,initialLease=await dependencyStore.claimStep(first.stepId,"crashed-worker",T0,T1),reclaimed=await dependencyStore.claimStep(first.stepId,"recovery-worker",T2,T3)
    check("expired claim reclaimed with monotonic fence",initialLease.status==="CLAIMED"&&reclaimed.status==="CLAIMED"&&reclaimed.fencingToken===initialLease.fencingToken+1)
    check("stale worker heartbeat rejected",!(await dependencyStore.heartbeatStep(first.stepId,"crashed-worker",initialLease.fencingToken,T2,T3)))
    let staleCompletion=false;try{await dependencyStore.linkResultAndComplete({stepId:first.stepId,planId:plan.planId,snapshotId:v2Snapshot.snapshotId,resultId:v1Result.result.resultId,occurredAt:T2,workerId:"crashed-worker",fencingToken:initialLease.fencingToken})}catch{staleCompletion=true}check("stale worker completion rejected",staleCompletion)
    check("active worker heartbeat",await dependencyStore.heartbeatStep(first.stepId,"recovery-worker",reclaimed.fencingToken,T2,"2026-02-01T01:04:00.000Z"))
    const v2Run=await runStore.create(v2Request.runSpecification);check("V2 Run created",v2Run.status==="CREATED");const v2Write=await resultStore.write(v2Request);if(v2Write.status!=="CREATED")throw new Error("V2_RESULT_MISSING")
    check("V1 remains immutable after V2",(await resultStore.lookup(v1Result.result.resultIdentity)).status==="FOUND")
    check("V2 Result linked and completed",(await dependencyStore.linkResultAndComplete({stepId:first.stepId,planId:plan.planId,snapshotId:v2Snapshot.snapshotId,resultId:v2Write.result.resultId,occurredAt:T2,workerId:"recovery-worker",fencingToken:reclaimed.fencingToken}))==="COMPLETED")
    const historical=selectConsistencyResult({candidates:[{subjectId:"bounded-subject",result:v1Result.result},{subjectId:"bounded-subject",result:v2Write.result}],subjectId:"bounded-subject",eventTimeStart:RESULT_FIXTURE_START,eventTimeEnd:RESULT_FIXTURE_END,policyVersion:"1",knowledgeMode:"AS_KNOWN_THEN",knowledgeTimeCutoff:RESULT_FIXTURE_CUTOFF,preferredRuleVersion:"1.0.0",supersededResultIds:[],createdAt:T2})
    const current=selectConsistencyResult({candidates:[{subjectId:"bounded-subject",result:v1Result.result},{subjectId:"bounded-subject",result:v2Write.result}],subjectId:"bounded-subject",eventTimeStart:RESULT_FIXTURE_START,eventTimeEnd:RESULT_FIXTURE_END,policyVersion:"1",knowledgeMode:"LATEST_CORRECTED",knowledgeTimeCutoff:T2,preferredRuleVersion:"1.0.0",supersededResultIds:[v1Result.result.resultId],createdAt:T2})
    check("historical selection preserves V1",historical.selectedResultId===v1Result.result.resultId);check("current selection chooses V2",current.selectedResultId===v2Write.result.resultId)
    check("dependency reconciliation",reconcileDependency(v2Snapshot,plan).consistent)

    check("worker immutable update denied",await denied(worker,"UPDATE consistency.immutable_results SET outcome='PARTIAL' WHERE result_id=$1",[v1Result.result.resultId]))
    check("worker event delete denied",await denied(worker,"DELETE FROM consistency.run_events WHERE run_id=$1",[v1Request.runSpecification.runId]))
    check("worker schema alteration denied",await denied(worker,"ALTER TABLE consistency.run_events ADD COLUMN forbidden integer"))
    check("worker migration ledger denied",await denied(worker,"UPDATE d4_control.migration_ledger SET applied_by='forbidden'"))
    check("worker Evidence write denied",await denied(worker,"INSERT INTO evidence.candidates(candidate_id,profile_id,subject_id,event_window_start,event_window_end,knowledge_mode,knowledge_time_cutoff,rule_set_id,rule_set_version,consistency_run_id,input_set_identity,candidate_checksum,created_at) VALUES('x','x','x',now(),now()+interval '1 second','AS_KNOWN_THEN',now(),'x','1','x','x',repeat('a',64),now())"))
    check("verifier bounded read succeeds",(await verifier.sql.unsafe<{count:number}[]>("SELECT count(*)::int count FROM consistency.immutable_results"))[0]!.count>=2)
    check("verifier insert denied",await denied(verifier,"INSERT INTO consistency.run_creation_conflicts VALUES('x','x',repeat('a',64),repeat('b',64),now())"))
    check("verifier mutation function denied",await denied(verifier,"SELECT consistency.claim_recompute_step('x','x',now(),now()+interval '1 minute')"))

    let corruptionDetected=false;try{await owner.transaction(async sql=>{await sql.unsafe("ALTER TABLE consistency.dependency_nodes DISABLE TRIGGER dependency_nodes_no_mutation");await sql.unsafe("UPDATE consistency.dependency_nodes SET node_checksum=repeat('f',64) WHERE node_id=$1",[v2Graph.fact.nodeId]);const row=await sql.unsafe<{mismatch:boolean}[]>("SELECT node_checksum<>$2 mismatch FROM consistency.dependency_nodes WHERE node_id=$1",[v2Graph.fact.nodeId,v2Graph.fact.checksum]);corruptionDetected=Boolean(row[0]?.mismatch);throw new Error("ROLLBACK_CORRUPTION")})}catch{}check("persisted corruption detected and rolled back",corruptionDetected&&(await owner.sql.unsafe<{checksum:string}[]>("SELECT node_checksum checksum FROM consistency.dependency_nodes WHERE node_id=$1",[v2Graph.fact.nodeId]))[0]?.checksum===v2Graph.fact.checksum)
    const persisted=await owner.sql.unsafe<{orphan:number;falseComplete:number;leaseMismatch:number}[]>("SELECT (SELECT count(*)::int FROM consistency.dependency_edges e LEFT JOIN consistency.dependency_nodes f ON f.node_id=e.from_node_id LEFT JOIN consistency.dependency_nodes t ON t.node_id=e.to_node_id WHERE f.node_id IS NULL OR t.node_id IS NULL) orphan,(SELECT count(*)::int FROM consistency.recompute_step_events e WHERE e.outcome='COMPLETED' AND NOT EXISTS(SELECT 1 FROM consistency.result_dependency_links l WHERE l.step_id=e.step_id)) \"falseComplete\",(SELECT count(*)::int FROM consistency.recompute_step_lease_state s WHERE s.lease_state='COMPLETED' AND NOT EXISTS(SELECT 1 FROM consistency.recompute_step_events e WHERE e.step_id=s.step_id AND e.outcome='COMPLETED')) \"leaseMismatch\"")
    check("persisted graph and execution reconciliation",persisted[0]?.orphan===0&&persisted[0]?.falseComplete===0&&persisted[0]?.leaseMismatch===0)
    const plans=await explainPlans(owner,v1Result.result.resultIdentity);check("bounded query indexes eligible",plans.every(plan=>/Index Scan|Index Only Scan|Bitmap/.test(plan)),plans.join(" | "))
    const ledger=await verifier.sql.unsafe<{count:number}[]>("SELECT count(*)::int count FROM d4_control.migration_ledger");check("migration ledger complete",ledger[0]?.count===D4_MIGRATION_ORDER.length)

    const failures=checks.filter(([,pass])=>!pass);console.log(`D4 PHASE 2V INTEGRATED SUITE: ${failures.length?"FAIL":"PASS"}`);for(const[name,pass,detail]of checks)console.log(`[${pass?"PASS":"FAIL"}] ${name}${detail?": "+detail:""}`);if(failures.length)process.exitCode=1
  }finally{await verifier.shutdown();await worker.shutdown();await owner.shutdown();if(failureRoot)await rm(failureRoot,{recursive:true,force:true})}
}

function evaluateFixture(input:ReturnType<typeof temporalFact>){const metadata:RuleMetadata={ruleId:"result-rule",semanticVersion:"1.0.0",compatibilityVersion:"1",owner:"D4_CONSISTENCY",category:"DATASET_AGREEMENT",activationState:"ACTIVE",createdAt:"2026-01-01T00:00:00.000Z",activation:{activeFrom:"2026-01-01T00:00:00.000Z",activeUntil:null},supersededBy:null,deprecation:null};const canonicalInput=toConsistencyInput(input),context={datasetIdentity:"funding",canonicalReference:canonicalInput.fact,knowledgeTime:RESULT_FIXTURE_CUTOFF,evaluationTime:RESULT_FIXTURE_END,compatibilityVersion:"1",orderedInputs:[canonicalInput]};return new RuleEvaluationRuntime(new ConsistencyRuleRegistry([metadata]),new Map([["result-rule@1.0.0",()=>({outcome:"CONSISTENT" as const,confidenceComponents:[{componentId:"fixture",status:"SATISFIED" as const,basisCodes:["EXACT_FACT_VERSION"]}],diagnostics:[]})]]),{monotonicMilliseconds:()=>1}).execute({executionId:"phase2v-evaluation",rule:{ruleId:"result-rule",semanticVersion:"1.0.0"},context})}
function toConsistencyInput(input:ReturnType<typeof temporalFact>):ConsistencyInputReference{return{roleId:input.roleId,fact:input.fact,physicalFactId:`${input.fact.canonicalRecordId}:${input.fact.recordVersion}`,datasetId:input.fact.datasetId,providerId:input.providerId,effectiveAt:input.effectiveAt,observedAt:input.observedAt,knowledgeAvailableAt:input.knowledgeAvailableAt!,publicationState:input.publicationState,checksum:input.checksum,governance:{datasetRegistrySnapshotId:"dataset-snapshot",providerRegistrySnapshotId:"provider-snapshot",providerCertificationSnapshotId:"provider-snapshot",policyVersionId:"temporal-policy",schemaVersion:"1",normalizationVersion:"1"},lineageNodeId:`lineage:${input.fact.canonicalRecordId}:${input.fact.recordVersion}`}}
function graph(resultId:string,version:string){const node=(kind:DependencyNode["kind"],objectId:string,objectVersion:string)=>createDependencyNode({kind,objectId,objectVersion,metadata:[],createdAt:T0}),fact=node("CANONICAL_FACT_VERSION","result-a",version),ruleA=node("RULE_VERSION","result-rule","1.0.0"),ruleB=node("RULE_VERSION","dependent-rule","1.0.0"),policy=node("POLICY_VERSION","temporal-policy","1"),alignment=node("TEMPORAL_ALIGNMENT","alignment-phase2v",version),result=node("CONSISTENCY_RESULT",resultId,"1"),nodes=[fact,ruleA,ruleB,policy,alignment,result],map=new Map(nodes.map(x=>[x.nodeId,x])),edge=(kind:Parameters<typeof createDependencyEdge>[0]["kind"],from:string,to:string)=>createDependencyEdge({kind,fromNodeId:from,toNodeId:to,policyVersion:"1",createdAt:T0},map);return{fact,nodes,edges:[edge("FACT_INPUT_TO_RULE",fact.nodeId,ruleA.nodeId),edge("RULE_DEPENDS_ON_RULE",ruleA.nodeId,ruleB.nodeId),edge("POLICY_GOVERNS_RULE",policy.nodeId,ruleA.nodeId),edge("FACT_USED_BY_ALIGNMENT",fact.nodeId,alignment.nodeId),edge("ALIGNMENT_USED_BY_RESULT",alignment.nodeId,result.nodeId),edge("RULE_PRODUCED_RESULT",ruleA.nodeId,result.nodeId)]}}
function command(spec:ReturnType<typeof createResultFixture>["runSpecification"],nextState:ConsistencyRunTransitionCommand["nextState"],id:string,completionSummary:ConsistencyRunCompletionSummary|null):ConsistencyRunTransitionCommand{return{commandId:id,runId:spec.runId,specificationChecksum:spec.specificationChecksum,nextState,actorType:"COORDINATOR",actorId:"phase2v",occurredAt:T0,policyVersionReferences:["1"],reasonCodes:[],details:[],completionSummary}}
function summary(runId:string):ConsistencyRunCompletionSummary{const base={summaryId:"summary_"+canonicalChecksum({runId}),runId,requiredRuleCount:1,completedRuleCount:1,consistentResultCount:1,inconsistentResultCount:0,blockedResultCount:0,failedEvaluationCount:0,unresolvedCount:0,terminalState:"COMPLETED" as const,reasonCodes:[] as readonly string[]};return{...base,summaryChecksum:canonicalChecksum(base)}}
async function seedGovernance(owner:ConsistencyPostgresRuntime){for(const id of["result-policy","temporal-policy","comparison-policy","severity-policy"]as const)await owner.sql.unsafe("INSERT INTO control.policy_versions(policy_version_id,dataset_id,policy_version,content_checksum,canonical_content,effective_at,created_at) VALUES($1,$2,'1',$3,$4::text::jsonb,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z') ON CONFLICT DO NOTHING",[id,"d4-phase2v-"+id,canonicalChecksum({phase:"d4-phase2v",id}),JSON.stringify({id})]);await owner.sql.unsafe("INSERT INTO consistency.rule_sets VALUES('RESULT-RULES','1.0.0','result-policy','APPROVED',repeat('a',64),'2026-01-01T00:00:00Z')");for(const id of ["result-rule","dependent-rule"])await owner.sql.unsafe("INSERT INTO consistency.rules VALUES($1,'1.0.0','RESULT-RULES','1.0.0','DATASET_AGREEMENT','FACTUAL','1','result-policy','BLOCKING',repeat($2,64),'2026-01-01T00:00:00Z')",[id,id==="result-rule"?"b":"c"])}
async function denied(runtime:ConsistencyPostgresRuntime,sql:string,parameters:readonly unknown[]=[]){try{await runtime.sql.unsafe(sql,parameters as never[]);return false}catch{return true}}
async function explainPlans(owner:ConsistencyPostgresRuntime,resultIdentity:string){const queries=[["SELECT * FROM consistency.immutable_results WHERE result_identity=$1",[resultIdentity]],["SELECT * FROM consistency.result_input_references WHERE canonical_record_id=$1 AND record_version=$2",["result-a",1]],["SELECT * FROM consistency.run_events WHERE run_id=$1 ORDER BY event_sequence",["missing"]],["SELECT * FROM consistency.dependency_edges WHERE from_node_id=$1 ORDER BY to_node_id",["missing"]],["SELECT * FROM consistency.recompute_requests_v2 WHERE request_identity=$1",["missing"]],["SELECT * FROM consistency.recompute_step_lease_state WHERE lease_state='ACTIVE' AND expires_at<=now() ORDER BY expires_at,step_id",[]],["SELECT * FROM consistency.immutable_results WHERE knowledge_mode=$1 AND knowledge_time_cutoff<=$2 ORDER BY knowledge_time_cutoff DESC,result_id",["AS_KNOWN_THEN",RESULT_FIXTURE_CUTOFF]] ]as const;const plans:string[]=[];await owner.transaction(async sql=>{await sql.unsafe("SET LOCAL enable_seqscan=off");for(const[q,p]of queries){const rows=await sql.unsafe<{"QUERY PLAN":string}[]>("EXPLAIN "+q,[...p]);plans.push(rows.map(x=>x["QUERY PLAN"]).join(" "))}});return plans}
void main().catch((error:unknown)=>{console.error(error instanceof Error?error.message:error);process.exitCode=1})
