import { canonicalChecksum } from "@/lib/data-platform/contracts"
import { assembleCoreEvidencePacket,reconcileCoreEvidencePacket,type CoreEvidencePacket,type EvidenceAssemblyRequest } from "@/lib/data-platform/evidence-platform"
import { ConsistencyMigrationRunner,ConsistencyPostgresRuntime,ConsistencyResultStore,ConsistencyRunStore,CoreEvidenceStore,resetD4Runtime,type EvidenceStoreFailurePoint } from "@/lib/data-platform/consistency-evidence/postgres"
import { evidenceProfile,evidenceRequest,evidenceResultRequests } from "./fixtures"

const checks:Array<readonly [string,boolean,string?]>=[]
const check=(name:string,pass:boolean,detail?:string)=>checks.push([name,pass,detail])

async function main(){
  const env={D4_ISOLATED_POSTGRES_URL:process.env.D4_ISOLATED_POSTGRES_URL,D2_ISOLATED_POSTGRES_URL:process.env.D2_ISOLATED_POSTGRES_URL,D3_ISOLATED_POSTGRES_URL:process.env.D3_ISOLATED_POSTGRES_URL,DATABASE_URL:process.env.DATABASE_URL}
  const owner=runtime(env,"MIGRATION_OWNER","d4-phase3a-owner",2),worker=runtime(env,"CONSISTENCY_WORKER","d4-phase3a-result-worker",2),assembler=runtime(env,"EVIDENCE_ASSEMBLER","d4-phase3a-assembler",4),verifier=runtime(env,"READ_ONLY","d4-phase3a-verifier",1)
  try{
    const database=await owner.connect();check("isolated D4 target",database.database==="quantterminal_d4_isolated"&&!database.d3PopulationSchemaPresent)
    await resetD4Runtime(owner,{explicitOptIn:"RESET_D4_ISOLATED_DATABASE",auditIdentity:"d4-phase3a"})
    const migrations=await new ConsistencyMigrationRunner(owner).apply("d4-phase3a");check("fresh migration chain",migrations.every(item=>item.status==="APPLIED"))
    await seedGovernance(owner);await seedProfile(owner);await worker.connect();await assembler.connect();await verifier.connect()
    check("evidence assembler physical role",(await assembler.sql.unsafe<{role:string}[]>("SELECT current_user role"))[0]?.role==="qt_d4_evidence_assembler")
    await persistResults(worker,evidenceResultRequests({includeConflict:true}))

    const request=evidenceRequest({includeConflict:true}),store=new CoreEvidenceStore(assembler)
    const race=await Promise.all([store.assemble(request),store.assemble(request)]),created=race.find(item=>item.status==="CREATED"),reused=race.find(item=>item.status==="REUSED")
    check("concurrent identical assembly",Boolean(created&&reused),race.map(item=>item.status).join(","))
    if(!created||created.status!=="CREATED")throw new Error("EVIDENCE_PACKET_NOT_CREATED")
    const packet=created.packet
    check("supporting and conflicting remain distinct",packet.supportingEvidence.length===1&&packet.conflictingEvidence.length===1&&packet.conclusionCode==="EVIDENCE_MIXED")
    check("exact Result and Fact references persisted",(await counts(verifier,packet.packetVersionId)).results===2&&(await counts(verifier,packet.packetVersionId)).facts===4)
    const duplicate=await store.writePacket(packet,canonicalChecksum(request.profile));check("write duplicate distinct from reuse",duplicate.status==="DUPLICATE")
    const conflictingPacket={...packet,packetChecksum:canonicalChecksum({packetChecksum:packet.packetChecksum,conflict:true})} satisfies CoreEvidencePacket
    const conflictRace=await Promise.all([store.writePacket(conflictingPacket,canonicalChecksum(request.profile)),store.writePacket(conflictingPacket,canonicalChecksum(request.profile))])
    check("immutable packet conflict",conflictRace.every(item=>item.status==="CONFLICT")&&(await store.conflicts(packet.packetVersionIdentity)).length===1)

    const correctionRequest=evidenceRequest({version:2});await persistResults(worker,evidenceResultRequests({version:2}))
    const correction=await store.assemble(correctionRequest);check("correction creates distinct immutable packet version",correction.status==="CREATED"&&correction.packet.packetVersionIdentity!==packet.packetVersionIdentity&&correction.packet.packetId===packet.packetId)
    check("historical packet remains immutable",(await verifier.sql.unsafe<{count:number}[]>("SELECT count(*)::int count FROM evidence.core_packet_versions WHERE packet_version_id=$1",[packet.packetVersionId]))[0]?.count===1)

    await certifyFailureBoundaries(assembler,verifier,request)
    const unknownStore=new CoreEvidenceStore(assembler,{fail(point){if(point==="AFTER_COMMIT_UNKNOWN")throw new Error("SIMULATED_UNKNOWN_COMMIT")}}),unknownRequest={...request,topic:"UNKNOWN_OUTCOME"}
    const unknown=await unknownStore.assemble(unknownRequest);check("unknown commit reconciled by identity and checksum",unknown.status==="DUPLICATE"&&unknown.reconciledUnknownOutcome,unknown.status)

    const reconciliation=reconcileCoreEvidencePacket(packet,request);check("packet reconciliation",reconciliation.consistent&&reconciliation.traversalComplete)
    const persisted=await verifier.sql.unsafe<{orphanCandidates:number;orphanResults:number;orphanFacts:number}[]>("SELECT (SELECT count(*)::int FROM evidence.core_packet_candidates c LEFT JOIN evidence.core_packet_versions p ON p.packet_version_id=c.packet_version_id WHERE p.packet_version_id IS NULL) \"orphanCandidates\",(SELECT count(*)::int FROM evidence.core_packet_result_references r LEFT JOIN consistency.immutable_results i ON i.result_id=r.result_id WHERE i.result_id IS NULL) \"orphanResults\",(SELECT count(*)::int FROM evidence.core_packet_fact_references f LEFT JOIN evidence.core_packet_versions p ON p.packet_version_id=f.packet_version_id WHERE p.packet_version_id IS NULL) \"orphanFacts\"")
    check("persisted Evidence reconciliation",persisted[0]?.orphanCandidates===0&&persisted[0]?.orphanResults===0&&persisted[0]?.orphanFacts===0)
    await certifyPrivileges(assembler,verifier,check)
    const plans=await explain(verifier,packet);check("bounded Evidence indexes eligible",plans.every(plan=>/Index|Bitmap/.test(plan)),plans.join(" | "))
  }finally{await Promise.allSettled([verifier.disconnect(),assembler.disconnect(),worker.disconnect(),owner.disconnect()])}
  const failed=checks.filter(([,pass])=>!pass);console.log(`D4 PHASE 3A POSTGRES SUITE: ${failed.length?"FAIL":"PASS"}`);for(const[name,pass,detail]of checks)console.log(`[${pass?"PASS":"FAIL"}] ${name}${detail?`: ${detail}`:""}`);if(failed.length)process.exitCode=1
}

function runtime(env:Record<string,string|undefined>,role:"MIGRATION_OWNER"|"CONSISTENCY_WORKER"|"EVIDENCE_ASSEMBLER"|"READ_ONLY",name:string,maxConnections:number){return new ConsistencyPostgresRuntime({connectionString:env.D4_ISOLATED_POSTGRES_URL!,environment:env,roleIntent:role,maxConnections,connectTimeoutSeconds:10,idleTimeoutSeconds:30,statementTimeoutMs:20_000,lockTimeoutMs:5_000,idleTransactionTimeoutMs:15_000,applicationName:name})}
async function seedGovernance(owner:ConsistencyPostgresRuntime){for(const id of["result-policy","temporal-policy","comparison-policy","severity-policy"]as const)await owner.sql.unsafe("INSERT INTO control.policy_versions(policy_version_id,dataset_id,policy_version,content_checksum,canonical_content,effective_at,created_at) VALUES($1,$2,'1',$3,$4::text::jsonb,'2026-01-01T00:00:00Z','2026-01-01T00:00:00Z') ON CONFLICT DO NOTHING",[id,"d4-phase3a-"+id,canonicalChecksum({phase:"d4-phase3a",id}),JSON.stringify({id})]);await owner.sql.unsafe("INSERT INTO consistency.rule_sets VALUES('RESULT-RULES','1.0.0','result-policy','APPROVED',repeat('a',64),'2026-01-01T00:00:00Z')");await owner.sql.unsafe("INSERT INTO consistency.rules VALUES('result-rule','1.0.0','RESULT-RULES','1.0.0','DATASET_AGREEMENT','FACTUAL','1','result-policy','BLOCKING',repeat('b',64),'2026-01-01T00:00:00Z')")}
async function seedProfile(owner:ConsistencyPostgresRuntime){await owner.sql.unsafe("INSERT INTO evidence.core_assembly_profiles VALUES($1,$2,$3,$4,$5,$6::text::jsonb,$7,$8,$9::text::jsonb,$10,$11,$12,$13)",["CORE-MARKET-EVIDENCE",evidenceProfile.profileVersion,evidenceProfile.schemaVersion,"CORE-ASSEMBLY",evidenceProfile.assemblyPolicyVersion,JSON.stringify(evidenceProfile.selectionPolicyReferences),"BOUNDED-CONCLUSION",evidenceProfile.conclusionPolicyVersion,JSON.stringify(evidenceProfile.roleRules),evidenceProfile.requiredRoles,evidenceProfile.optionalRoles,canonicalChecksum(evidenceProfile),"2026-02-01T01:00:00.000Z"])}
async function persistResults(runtime:ConsistencyPostgresRuntime,requests:ReturnType<typeof evidenceResultRequests>){const runs=new ConsistencyRunStore(runtime),results=new ConsistencyResultStore(runtime);for(const request of requests){const run=await runs.create(request.runSpecification);if(!["CREATED","DUPLICATE"].includes(run.status))throw new Error(`RUN_SEED_${run.status}`);const result=await results.write(request);if(!["CREATED","DUPLICATE"].includes(result.status))throw new Error(`RESULT_SEED_${result.status}`)}}
async function counts(runtime:ConsistencyPostgresRuntime,packetVersionId:string){const rows=await runtime.sql.unsafe<{results:number;facts:number}[]>("SELECT (SELECT count(*)::int FROM evidence.core_packet_result_references WHERE packet_version_id=$1) results,(SELECT count(*)::int FROM evidence.core_packet_fact_references WHERE packet_version_id=$1) facts",[packetVersionId]);return rows[0]!}
async function certifyFailureBoundaries(assembler:ConsistencyPostgresRuntime,verifier:ConsistencyPostgresRuntime,base:EvidenceAssemblyRequest){const points:readonly EvidenceStoreFailurePoint[]=["AFTER_PACKET_ROW","AFTER_SUPPORTING_LINK","AFTER_CONFLICTING_LINK","AFTER_RESULT_REFERENCE","AFTER_REQUIREMENT_LINK","AFTER_LINEAGE","AFTER_CHECKSUM","BEFORE_COMMIT"];for(const point of points){const request={...base,topic:`FAIL_${point}`,requirements:point==="AFTER_REQUIREMENT_LINK"?[{requirementId:"required-flow",kind:"MISSING" as const,datasetId:"flow",reasonCode:"NOT_AVAILABLE",policyId:"assembly",policyVersion:"1"}]:base.requirements},packet=assembleCoreEvidencePacket(request),store=new CoreEvidenceStore(assembler,{fail(hit){if(hit===point)throw new Error(`SIMULATED_${point}`)}}),outcome=await store.assemble(request),rows=await verifier.sql.unsafe<{count:number}[]>("SELECT count(*)::int count FROM evidence.core_packet_versions WHERE packet_version_identity=$1",[packet.packetVersionIdentity]);check(`rollback ${point}`,outcome.status==="RETRYABLE_FAILURE"&&rows[0]?.count===0)}}
async function certifyPrivileges(assembler:ConsistencyPostgresRuntime,verifier:ConsistencyPostgresRuntime,record:(name:string,pass:boolean,detail?:string)=>void){for(const[name,runtime,sql]of[["assembler immutable update denied",assembler,"UPDATE evidence.core_packet_versions SET packet_status='BLOCKED'"],["assembler immutable delete denied",assembler,"DELETE FROM evidence.core_packet_versions"],["assembler schema alteration denied",assembler,"ALTER TABLE evidence.core_packet_versions ADD COLUMN forbidden text"],["assembler migration ledger denied",assembler,"DELETE FROM d4_control.migration_ledger"],["verifier insert denied",verifier,"INSERT INTO evidence.core_packet_identities(packet_id,evidence_business_identity,subject_id,subject_type,topic,event_time_start,event_time_end,knowledge_mode,knowledge_time_cutoff,profile_id,profile_version,schema_version,created_at) VALUES('x',repeat('a',64),'x','x','x',now(),now()+interval '1 second','AS_KNOWN_THEN',now(),'CORE-MARKET-EVIDENCE','1.0.0','1',now())"]]as const){let denied=false;try{await runtime.sql.unsafe(sql)}catch{denied=true}record(name,denied)}record("verifier bounded Evidence read",(await verifier.sql.unsafe<{count:number}[]>("SELECT count(*)::int count FROM evidence.core_packet_versions"))[0]!.count>0)}
async function explain(verifier:ConsistencyPostgresRuntime,packet:CoreEvidencePacket){const plans:string[]=[];await verifier.transaction(async sql=>{await sql.unsafe("SET LOCAL enable_seqscan=off");plans.push((await sql.unsafe<{"QUERY PLAN":string}[]>("EXPLAIN SELECT * FROM evidence.core_packet_versions WHERE packet_version_identity=$1",[packet.packetVersionIdentity])).map(row=>row["QUERY PLAN"]).join(" "));plans.push((await sql.unsafe<{"QUERY PLAN":string}[]>("EXPLAIN SELECT * FROM evidence.core_packet_fact_references WHERE canonical_record_id=$1 AND record_version=$2",[packet.factReferences[0]!.canonicalRecordId,packet.factReferences[0]!.recordVersion])).map(row=>row["QUERY PLAN"]).join(" "));plans.push((await sql.unsafe<{"QUERY PLAN":string}[]>("EXPLAIN SELECT * FROM evidence.core_packet_conflicts WHERE packet_version_identity=$1 ORDER BY detected_at,conflict_id",[packet.packetVersionIdentity])).map(row=>row["QUERY PLAN"]).join(" "))});return plans}

main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exitCode=1})
