"use client"

import dynamic from "next/dynamic"
import Link from "next/link"
import { useRouter, useSearchParams } from "next/navigation"
import { useEffect, useMemo, useState } from "react"

import useMarketSocket from "@/hooks/useMarketSocket"
import { useMarketStore } from "@/stores/useMarketStore"

export type MvpView = "dashboard" | "markets" | "scanner" | "trade" | "replay" | "research"
type RecordValue = Record<string, unknown>
type ProjectionResponse = { status?: string; reason?: string; projections?: unknown; data?: RecordValue; payload?: RecordValue; [key: string]: unknown }

const Legacy = {
  dashboard: dynamic(() => import("@/components/DashboardLayout")),
  markets: dynamic(() => import("@/components/markets/MarketsPage")),
  scanner: dynamic(() => import("@/components/scanner/ScannerPage")),
  trade: dynamic(() => import("@/components/trade/TradePage")),
  replay: dynamic(() => import("@/components/replay/ReplayV1Page")),
  research: dynamic(() => import("@/components/research/ResearchPage")),
}

const labels: Record<MvpView, string> = { dashboard: "Dashboard", markets: "Markets", scanner: "Scanner", trade: "Trade", replay: "Replay", research: "Research" }
const routes: Record<MvpView, string> = { dashboard: "/dashboard", markets: "/markets", scanner: "/scanner", trade: "/trade", replay: "/replay", research: "/research" }
const preservedKeys = ["instrument", "symbol", "start", "end", "candidate", "candidateId", "evidence", "evidenceId", "projection", "projectionId"]

function asRecord(value: unknown): RecordValue { return value && typeof value === "object" && !Array.isArray(value) ? value as RecordValue : {} }
function asList(value: unknown): unknown[] { return Array.isArray(value) ? value : [] }
function text(value: unknown, fallback = "UNAVAILABLE") { return typeof value === "string" || typeof value === "number" ? String(value) : fallback }
function value(payload: RecordValue, key: string, fallback = "UNAVAILABLE") { return text(payload[key], fallback) }
function codes(value: unknown): string[] { return asList(value).map((item) => text(item, "")).filter(Boolean) }

export function MvpCutoverLoadingShell({ view }: { view: MvpView }) {
  return <main className="min-h-screen bg-black px-3 py-3 text-white lg:px-4"><div className="mx-auto max-w-[1800px] rounded border border-cyan-300/20 bg-zinc-950 px-4 py-3 text-[10px] font-black uppercase tracking-[0.14em] text-cyan-100">Loading governed {labels[view]} projection...</div></main>
}

function LiveOverlay({ instrument }: { instrument: string }) {
  useMarketSocket()
  const ticker = useMarketStore((state) => state.tickers[instrument])
  const observedAt = ticker?.timestamp ? new Date(ticker.timestamp).toISOString() : null
  const freshness = ticker?.timestamp && Date.now() - ticker.timestamp < 30_000 ? "CURRENT" : ticker ? "STALE" : "SOURCE_UNAVAILABLE"
  return <section className="rounded border border-amber-300/25 bg-amber-300/5 px-3 py-2 text-[10px]"><span className="font-black uppercase tracking-[0.12em] text-amber-200">Live overlay - Binance realtime</span><span className="ml-3 text-zinc-300">{ticker ? `${ticker.symbol} ${ticker.price} | ${ticker.change24h}%` : "UNAVAILABLE - ticker not received"}</span><span className="ml-3 text-zinc-500">Observed {observedAt ?? "UNAVAILABLE"} | {freshness} | newer quotes do not alter governed Evidence</span></section>
}

function Status({ kind, reason }: { kind: "READ ERROR" | "MISSING" | "BLOCKED" | "UNAVAILABLE"; reason?: string }) {
  return <main className="min-h-screen bg-black px-3 py-3 text-white lg:px-4"><div className="mx-auto max-w-[1800px] rounded border border-amber-300/25 bg-zinc-950 p-4"><p className="text-xs font-black uppercase tracking-[0.14em] text-amber-200">{kind}</p><p className="mt-2 text-sm text-zinc-300">{reason || "Governed projection is unavailable."}</p></div></main>
}

function Items({ title, values }: { title: string; values: unknown }) {
  const items = codes(values)
  return <section className="rounded border border-zinc-800 bg-zinc-950/70 p-3"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-zinc-400">{title}</h2>{items.length ? <ul className="mt-2 space-y-1 text-xs text-zinc-200">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-xs text-zinc-500">UNAVAILABLE</p>}</section>
}

function Dashboard({ payload, href }: { payload: RecordValue; href: (view: MvpView, extra?: Record<string, string>) => string }) {
  const states = asList(payload.instrumentStates)
  return <div className="grid gap-3 lg:grid-cols-3"><section className="rounded border border-cyan-300/20 bg-zinc-950 p-4 lg:col-span-2"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-cyan-100">Market direction</h2><p className="mt-2 text-lg font-semibold">Mixed states preserved; no categorical average</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{states.map((item, index) => { const row = asRecord(item), instrument = value(row, "instrument", String(index)), evidence = value(row, "evidencePacketId", ""); return <div className="rounded border border-zinc-800 p-2 text-xs" key={`${instrument}-${index}`}><div>{instrument} | {value(row, "state")} | Confidence {value(row, "confidence")}</div><div className="mt-2 flex gap-3 text-cyan-100"><Link href={href("markets", { instrument })}>Markets</Link><Link href={href("research", { instrument, evidence })}>Evidence</Link><Link href={href("replay", { instrument })}>Replay</Link></div></div> })}</div></section><Items title="Why / primary drivers" values={payload.primaryDrivers} /><Items title="Risk / counter evidence" values={payload.primaryRisks} /><Items title="Coverage" values={asList(payload.coverageSummary).map((item) => JSON.stringify(item))} /></div>
}
function Markets({ projections, href }: { projections: unknown[]; href: (view: MvpView, extra?: Record<string, string>) => string }) { const summaries = projections.map(asRecord).filter((item) => item.projectionKind === "InstrumentMarketSummaryProjection"); return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{summaries.map((projection) => { const payload = asRecord(projection.payload), instrument = value(projection, "subjectId"), evidence = value(payload, "evidencePacketId", ""); return <section key={value(projection, "projectionVersionId")} className="rounded border border-zinc-800 bg-zinc-950/70 p-3"><h2 className="text-sm font-black text-cyan-100">{instrument} | {value(payload, "marketState")}</h2><p className="mt-2 text-xs text-zinc-200">Governed price {text(asRecord(payload.latestGovernedPrice).close)} | change {text(asRecord(payload.latestGovernedPrice).boundedPriceChangePct)}%</p><p className="mt-1 text-xs text-zinc-400">OI {text(asRecord(payload.openInterest).changePct)}% | Funding {text(asRecord(payload.funding).latestProviderEventRate)} | Flow {text(asRecord(payload.aggressiveFlow).imbalanceRatio)}</p><p className="mt-1 text-[10px] text-zinc-500">Confidence {text(asRecord(payload.confidence).classification)} | {value(projection, "eventTimeEnd")}</p><div className="mt-2 flex gap-3 text-xs text-cyan-100"><Link href={href("research", { instrument, evidence })}>Evidence</Link><Link href={href("replay", { instrument, start: value(projection, "eventTimeStart"), end: value(projection, "eventTimeEnd") })}>Replay</Link><Link href={href("scanner", { instrument })}>Scanner</Link></div></section> })}</div> }
function Metric({ title, data }: { title: string; data: unknown }) { const fields = asRecord(data); return <section className="rounded border border-zinc-800 bg-zinc-950/70 p-3"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-zinc-400">{title}</h2><p className="mt-2 break-words text-sm text-zinc-100">{Object.keys(fields).length ? Object.entries(fields).map(([key, item]) => `${key}: ${text(item)}`).join(" | ") : text(data)}</p></section> }
function Scanner({ payload, href }: { payload: RecordValue; href: (view: MvpView, extra?: Record<string, string>) => string }) { const candidates = asList(payload.candidates); return <section className="rounded border border-zinc-800 bg-zinc-950/70 p-3"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-cyan-100">Ranked investigation queue</h2><p className="mt-1 text-xs text-amber-200">Rank is investigation priority under comparable coverage - not expected profit.</p><div className="mt-3 space-y-2">{candidates.length ? candidates.map((item, index) => { const c = asRecord(item); const candidate = value(c, "candidateId", ""); return <div className="rounded border border-zinc-800 p-3 text-xs" key={candidate || index}><div className="font-semibold">#{value(c, "rank")} | {value(c, "instrument")} | {value(c, "assessmentState")}</div><p className="mt-1 text-zinc-400">{codes(c.ruleReasonCodes).join(" | ") || "REASON CODES UNAVAILABLE"}</p><p className="mt-1 text-zinc-500">Comparable coverage: {value(c, "coverageComparable")} | Evidence: {value(c, "evidenceStrength")} | {value(c, "exclusionReason", "eligible")}</p><div className="mt-2 flex gap-3"><Link href={href("trade", { candidate, instrument: value(c, "instrument", ""), evidence: value(c, "evidencePacketId", "") })}>Trade context</Link><Link href={href("research", { instrument: value(c, "instrument", ""), evidence: value(c, "evidencePacketId", "") })}>Evidence</Link></div></div> }) : <p className="text-sm text-zinc-400">NO COMPARABLE CANDIDATES</p>}</div></section> }
function Replay({ payload, cursor, onCursor }: { payload: RecordValue; cursor: number; onCursor: (next: number) => void }) { const lanes = asRecord(payload.lanes); const funding = asList(lanes.fundingEvents); return <div className="grid gap-3 lg:grid-cols-2"><section className="rounded border border-cyan-300/20 bg-zinc-950 p-3"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-cyan-100">Bounded replay controls</h2><input aria-label="Replay cursor" className="mt-3 w-full accent-cyan-300" type="range" min="0" max="100" value={cursor} onChange={(event) => onCursor(Number(event.target.value))} /><p className="mt-1 text-xs text-zinc-400">Cursor {cursor}% | bounded projection window only</p></section><Metric title="Price lane" data={lanes.ohlcv} /><Metric title="Open interest lane" data={lanes.openInterest} /><section className="rounded border border-zinc-800 bg-zinc-950/70 p-3"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-zinc-400">Funding - provider-native markers</h2>{funding.length ? funding.map((event, index) => <p className="mt-2 text-sm" key={index}>{JSON.stringify(event)}</p>) : <p className="mt-2 text-sm text-zinc-500">NO FUNDING MARKER</p>}<p className="mt-2 text-[10px] text-zinc-500">No synthetic five-minute funding points.</p></section><Metric title="Aggressive trade summary" data={lanes.aggTradesSummary} /><Items title="Unavailable lanes" values={payload.unavailableLanes} /></div> }
function Research({ payload }: { payload: RecordValue }) { return <div className="grid gap-3 lg:grid-cols-2"><Metric title="Conclusion" data={payload.conclusion} /><Metric title="Verified facts" data={payload.verifiedFacts} /><Metric title="Structured interpretation" data={payload.interpretation} /><Items title="Supporting evidence" values={payload.supportingEvidence} /><Items title="Counter evidence" values={payload.counterEvidence} /><Metric title="Confidence components" data={payload.confidence} /><Metric title="Lineage" data={payload.sourceLineage} /><Metric title="Version metadata" data={{ packetId: payload.packetId, packetVersionId: payload.packetVersionId, supersessionStatus: payload.supersessionStatus, recomputeIdentity: payload.recomputeIdentity }} /></div> }
function Trade({ payload, href }: { payload: RecordValue; href: (view: MvpView, extra?: Record<string, string>) => string }) { const instrument = value(payload, "selectedInstrument"), window = asList(payload.relatedReplayWindow).map(String); return <div className="grid gap-3 lg:grid-cols-2"><section className="rounded border border-amber-300/25 bg-amber-300/5 p-3"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-amber-200">No-action decision context</h2><p className="mt-2 text-sm">{value(payload, "actionState", "CONTEXT_ONLY_NO_ACTION")}</p><p className="mt-1 text-xs text-zinc-400">No orders, sizing, entries, exits, or execution instructions.</p></section><Metric title="Selected candidate" data={{ instrument, candidate: payload.sourceCandidateIdentity, marketState: payload.marketState }} /><Items title="Supporting facts" values={payload.supportingFacts} /><Items title="Counter evidence" values={payload.counterEvidence} /><Items title="Risk factors" values={payload.riskFactors} /><Metric title="Observable invalidation conditions" data={payload.invalidationConditions} /><Metric title="Confidence components" data={payload.confidence} /><Metric title="Coverage" data={payload.coverage} /><Items title="Limitations" values={payload.sourceLimitations} /><div className="rounded border border-zinc-800 bg-zinc-950 p-3 text-xs text-cyan-100"><Link href={href("research", { instrument, evidence: codes(payload.evidencePacketIds)[0] ?? "" })}>Supporting Evidence</Link><span className="mx-2">|</span><Link href={href("replay", { instrument, start: window[0] ?? "", end: window[1] ?? "" })}>Related Replay</Link></div></div> }

function SharedStatus({ projections }: { projections: unknown[] }) { const rows = projections.map(asRecord), coverage = rows.filter((row) => row.projectionKind === "CoverageDataStatusProjection"), lineage = rows.filter((row) => row.projectionKind === "SourceLineageSummaryProjection"), annotations = rows.filter((row) => row.projectionKind === "EventAnnotationProjection"); return <section className="rounded border border-zinc-800 bg-zinc-950/70 p-3"><h2 className="text-[10px] font-black uppercase tracking-[0.12em] text-zinc-400">Coverage, lineage, and limitations</h2><p className="mt-2 text-xs text-zinc-300">Coverage projections {coverage.length} | lineage summaries {lineage.length} | event annotations {annotations.length}</p><div className="mt-2 flex flex-wrap gap-2">{coverage.slice(0, 24).map((row) => <span className="rounded border border-zinc-800 px-2 py-1 text-[9px] text-zinc-400" key={value(row, "projectionVersionId")}>{value(row, "subjectId")} {text(asRecord(row.payload).completenessClassification, "AVAILABLE")}</span>)}</div><p className="mt-2 text-[10px] text-zinc-500">Every displayed value is as-of its Projection Event Time. Optional liquidation, historical Order Book, and news enrichment remain explicitly limited or unavailable.</p></section> }

export default function MvpCutoverPage({ view }: { view: MvpView }) {
  const params = useSearchParams()
  const router = useRouter()
  const [state, setState] = useState<{ phase: "loading" | "ready" | "error"; response?: ProjectionResponse; reason?: string }>({ phase: "loading" })
  const query = params.toString(), instrument = params.get("instrument") || params.get("symbol") || "BTCUSDT", [cursor, setCursor] = useState(0)
  useEffect(() => { const controller = new AbortController(), request = new URLSearchParams(params); request.set("view", view); if (!request.get("instrument") && request.get("symbol")) request.set("instrument", request.get("symbol")!); if (!request.get("candidate") && request.get("candidateId")) request.set("candidate", request.get("candidateId")!); setState({ phase: "loading" }); fetch(`/api/mvp/projections?${request.toString()}`, { signal: controller.signal, headers: { Accept: "application/json" } }).then(async (response) => { let body: ProjectionResponse; try { body = await response.json() } catch { throw new Error("Projection response was not JSON.") }; if (!response.ok && body.status !== "ROLLBACK_ACTIVE") throw new Error(text(body.reason, `Projection read failed (${response.status}).`)); setState({ phase: "ready", response: body }) }).catch((error: unknown) => { if ((error as { name?: string }).name !== "AbortError") setState({ phase: "error", reason: error instanceof Error ? error.message : "Projection read failed." }) }); return () => controller.abort() }, [view, query, params])
  const href = useMemo(() => (target: MvpView, extra: Record<string, string> = {}) => { const next = new URLSearchParams(); preservedKeys.forEach((key) => { const current = params.get(key); if (current) next.set(key, current) }); Object.entries(extra).forEach(([key, current]) => { if (current) next.set(key, current) }); return `${routes[target]}?${next.toString()}` }, [params])
  if (state.phase === "loading") return <MvpCutoverLoadingShell view={view} />
  if (state.phase === "error") return <Status kind="READ ERROR" reason={state.reason} />
  const response = state.response!, status = text(response.status, "READY")
  if (status === "ROLLBACK_ACTIVE") { const LegacyPage = Legacy[view]; return <LegacyPage /> }
  if (["MISSING", "PROJECTION_MISSING", "NOT_FOUND"].includes(status)) return <Status kind="MISSING" reason={text(response.reason)} />
  if (["BLOCKED", "SOURCE_BLOCKED", "WITHHELD", "PROJECTION_WITHHELD", "CUTOVER_NOT_AUTHORIZED"].includes(status)) return <Status kind="BLOCKED" reason={text(response.reason)} />
  if (status !== "READY" && status !== "AVAILABLE" && status !== "SUCCESS") return <Status kind="UNAVAILABLE" reason={text(response.reason, status)} />
  const primaryKinds: Record<MvpView, string> = { dashboard: "DashboardMarketStateProjection", markets: "InstrumentMarketSummaryProjection", scanner: "ScannerCandidateProjection", trade: "TradeDecisionContextProjection", replay: "ReplayTimelineProjection", research: "ResearchEvidenceProjection" }
  const projections = asList(response.projections), primary = asRecord(projections.find((item) => asRecord(item).projectionKind === primaryKinds[view]) ?? response.data ?? response.payload)
  const payload = { ...asRecord(primary.payload), eventTimeStart: primary.eventTimeStart, eventTimeEnd: primary.eventTimeEnd, knowledgeTimeCutoff: primary.knowledgeTimeCutoff, projectionVersionId: primary.projectionVersionId, limitations: primary.limitations }
  const body = view === "dashboard" ? <Dashboard payload={payload} href={href} /> : view === "markets" ? <Markets projections={projections} href={href} /> : view === "scanner" ? <Scanner payload={payload} href={href} /> : view === "trade" ? <Trade payload={payload} href={href} /> : view === "replay" ? <Replay payload={payload} cursor={cursor} onCursor={setCursor} /> : <Research payload={payload} />
  const selectInstrument = (nextInstrument: string) => { const next = new URLSearchParams(params); next.set("instrument", nextInstrument); next.delete("symbol"); next.delete("candidate"); next.delete("projection"); router.push(`${routes[view]}?${next.toString()}`) }
  return <main className="min-h-screen bg-black px-3 py-3 text-white lg:px-4"><div className="mx-auto max-w-[1800px] space-y-3"><header className="flex flex-wrap items-center justify-between gap-2 rounded border border-zinc-800 bg-zinc-950 px-3 py-2"><div><h1 className="text-sm font-black uppercase tracking-[0.14em]">{labels[view]} | governed projection</h1><p className="mt-1 text-[10px] text-zinc-500">Instrument {instrument} | Event {value(payload, "eventTimeStart", params.get("start") || "UNAVAILABLE")} | Knowledge {value(payload, "knowledgeTimeCutoff")}</p></div>{!["dashboard", "markets", "scanner"].includes(view) ? <select aria-label="Governed instrument" value={instrument} onChange={(event) => selectInstrument(event.target.value)} className="rounded border border-zinc-700 bg-black px-2 py-1 text-xs">{["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "DOGEUSDT"].map((symbol) => <option key={symbol}>{symbol}</option>)}</select> : null}<nav className="flex flex-wrap gap-3 text-[10px] font-black uppercase tracking-[0.1em] text-cyan-100">{(["dashboard", "markets", "scanner", "trade", "replay", "research"] as MvpView[]).filter((item) => item !== view).map((item) => <Link key={item} href={href(item)}>{labels[item]}</Link>)}</nav></header>{["dashboard", "markets", "trade"].includes(view) ? <LiveOverlay instrument={instrument} /> : null}{body}<SharedStatus projections={projections} /></div></main>
}
