import type { PatternRecord, PatternStatus } from "@/lib/pattern-runtime"
import type { SignalDirection } from "@/lib/signal-evaluation"

export const LEARNING_SCHEMA_VERSION = 1 as const

export const LEARNING_STATUSES = [
  "DRAFT",
  "CANDIDATE",
  "VALIDATED",
  "REJECTED",
  "SUPERSEDED",
  "ARCHIVED",
] as const

export type LearningStatus = typeof LEARNING_STATUSES[number]

export interface LearningDateRange {
  readonly from: string
  readonly to: string
}

export interface LearningScope {
  readonly symbol: string | null
  readonly timeframe: string | null
  readonly direction: SignalDirection | null
  readonly dateRange: LearningDateRange | null
}

export interface LearningIdentity {
  readonly learningId: string
  readonly learningVersion: number
  readonly scope: LearningScope
  readonly patternSetHash: string
}

export interface LearningEvidence {
  readonly pattern: PatternRecord
}

export interface LearningConclusion {
  readonly summary: string
  readonly applicableConditions: readonly string[]
  readonly failureConditions: readonly string[]
  readonly supportingPatternIds: readonly string[]
  readonly conflictingPatternIds: readonly string[]
  readonly sampleSize: number
  readonly observedWinRate: number
  readonly averageReturnPercent: number
  readonly riskNotes: readonly string[]
}

export interface LearningRecord {
  readonly schemaVersion: typeof LEARNING_SCHEMA_VERSION
  readonly identity: LearningIdentity
  readonly status: LearningStatus
  readonly createdAt: string
  readonly evidence: readonly LearningEvidence[]
  /** Caller-supplied conclusion; never generated by this runtime. */
  readonly conclusion: LearningConclusion
}

export interface LearningQuery {
  readonly symbol?: string
  readonly timeframe?: string
  readonly direction?: SignalDirection
  readonly learningStatus?: LearningStatus
  readonly minimumSampleSize?: number
  readonly patternId?: string
  readonly dateRange?: LearningDateRange
}

export type LearningErrorCode =
  | "duplicate_learning_identity"
  | "duplicate_pattern_reference"
  | "identity_mismatch"
  | "immutable_conclusion_conflict"
  | "invalid_conclusion"
  | "invalid_lifecycle"
  | "invalid_pattern_reference"
  | "invalid_query"
  | "invalid_sample_metric"
  | "invalid_scope"
  | "invalid_timestamp"
  | "invalid_version"
  | "malformed_input"
  | "malformed_json"
  | "missing_learning_identity"
  | "missing_pattern_reference"
  | "serialization_failure"
  | "unsupported_schema_version"
  | "version_required"

export interface LearningError {
  readonly code: LearningErrorCode
  readonly message: string
  readonly field?: string
  readonly cause?: unknown
}

export type LearningResult<T> =
  | { readonly success: true; readonly value: T }
  | { readonly success: false; readonly errors: readonly LearningError[] }

export type LearningValidationResult = LearningResult<LearningRecord>

export interface CreateLearningInput {
  readonly learningVersion: number
  readonly scope: LearningScope
  readonly createdAt: string
  readonly patterns: readonly PatternRecord[]
  readonly conclusion: LearningConclusion
  readonly existingLearningIds?: ReadonlySet<string>
}

export interface LearningPatternSummary {
  readonly patternId: string
  readonly patternVersion: number
  readonly patternStatus: PatternStatus
  readonly sampleSize: number
}
