import type { ConsistencyKnowledgeMode } from "./runContracts"
import type { ConsistencyResult } from "./resultContracts"

export type DependencyNodeKind = "CANONICAL_FACT_VERSION" | "RULE_VERSION" | "RULESET_VERSION" | "TEMPORAL_ALIGNMENT" | "CONSISTENCY_RESULT" | "POLICY_VERSION"
export interface DependencyNodeIdentity { readonly nodeId: string; readonly kind: DependencyNodeKind; readonly objectId: string; readonly objectVersion: string; readonly checksum: string }
export interface DependencyNode extends DependencyNodeIdentity { readonly createdAt: string; readonly metadata: readonly { readonly key: string; readonly value: string }[] }
export type DependencyEdgeKind = "FACT_INPUT_TO_RULE" | "RULE_DEPENDS_ON_RULE" | "POLICY_GOVERNS_RULE" | "FACT_USED_BY_ALIGNMENT" | "ALIGNMENT_USED_BY_RESULT" | "RULE_PRODUCED_RESULT" | "FACT_USED_BY_RESULT" | "RESULT_DERIVED_FROM_RESULT" | "RESULT_SUPERSEDES_RESULT"
export interface DependencyEdge { readonly edgeId: string; readonly kind: DependencyEdgeKind; readonly fromNodeId: string; readonly toNodeId: string; readonly policyVersion: string; readonly checksum: string; readonly createdAt: string }
export interface DependencyGraphSnapshot { readonly snapshotId: string; readonly schemaVersion: string; readonly nodes: readonly DependencyNode[]; readonly edges: readonly DependencyEdge[]; readonly complete: boolean; readonly missingNodeIds: readonly string[]; readonly checksum: string; readonly createdAt: string }
export type ImpactReason = "FACT_CORRECTED" | "FACT_BECAME_AVAILABLE" | "RULE_VERSION_CHANGED" | "POLICY_VERSION_CHANGED" | "DEPENDENCY_CHANGED"
export interface ImpactAnalysisRequest { readonly changedNode: DependencyNodeIdentity; readonly replacedNodeId: string | null; readonly reason: ImpactReason; readonly snapshot: DependencyGraphSnapshot; readonly maxDepth: number; readonly requestedAt: string }
export interface ImpactAnalysisResult { readonly impactId: string; readonly changedNodeId: string; readonly directlyAffectedNodeIds: readonly string[]; readonly transitivelyAffectedNodeIds: readonly string[]; readonly unaffectedNodeIds: readonly string[]; readonly reasons: readonly ImpactReason[]; readonly snapshotId: string; readonly traversal: "COMPLETE" | "INCOMPLETE" | "CYCLE"; readonly checksum: string }
export interface RecomputeRequestIdentity { readonly requestId: string; readonly requestIdentity: string }
export interface RecomputeRequest extends RecomputeRequestIdentity { readonly triggeringNodeId: string; readonly impactId: string; readonly snapshotId: string; readonly eventTimeStart: string; readonly eventTimeEnd: string; readonly knowledgeMode: ConsistencyKnowledgeMode; readonly knowledgeTimeCutoff: string; readonly recomputePolicyVersion: string; readonly targetResultIds: readonly string[]; readonly checksum: string; readonly createdAt: string }
export type RecomputeCreateOutcome = { readonly status: "CREATED" | "DUPLICATE"; readonly request: RecomputeRequest; readonly plan: RecomputePlan } | { readonly status: "CONFLICT"; readonly requestId: string } | { readonly status: "NO_IMPACT" | "BLOCKED_INCOMPLETE_GRAPH" | "BLOCKED_CYCLE" | "BLOCKED_INVALID_DEPENDENCY"; readonly impactId: string }
export type DependencyWriteOutcome = { readonly status: "CREATED" | "DUPLICATE"; readonly edge: DependencyEdge } | { readonly status: "CONFLICT"; readonly edgeId: string }
export type DependencySnapshotWriteOutcome = { readonly status: "CREATED" | "DUPLICATE"; readonly snapshot: DependencyGraphSnapshot } | { readonly status: "CONFLICT"; readonly snapshotId: string }
export interface RecomputePlanStep { readonly stepId: string; readonly ordinal: number; readonly ruleNodeId: string; readonly dependencyStepIds: readonly string[]; readonly exactFactNodeIds: readonly string[]; readonly policyNodeIds: readonly string[]; readonly priorResultNodeIds: readonly string[]; readonly checksum: string }
export interface RecomputePlan { readonly planId: string; readonly requestId: string; readonly snapshotId: string; readonly steps: readonly RecomputePlanStep[]; readonly skippedNodeIds: readonly string[]; readonly blockingReasons: readonly string[]; readonly checksum: string; readonly createdAt: string }
export type RecomputeExecutionOutcome = "CLAIMED" | "DUPLICATE_CLAIM" | "COMPLETED" | "FAILED" | "CANCELLED" | "BLOCKED_DEPENDENCY"
export interface RecomputeLeaseClaimOutcome { readonly status: "CLAIMED" | "DUPLICATE_CLAIM"; readonly fencingToken: number }
export interface ResultSelectionDecision { readonly decisionId: string; readonly selectedResultId: string | null; readonly rejectedResultIds: readonly string[]; readonly reasonCodes: readonly string[]; readonly policyVersion: string; readonly knowledgeMode: ConsistencyKnowledgeMode; readonly knowledgeTimeCutoff: string; readonly checksum: string; readonly createdAt: string }
export interface DependencyReconciliationResult { readonly consistent: boolean; readonly reasonCodes: readonly ("NODE_IDENTITY_MISMATCH" | "EDGE_IDENTITY_MISMATCH" | "MISSING_ENDPOINT" | "CYCLE_DETECTED" | "SNAPSHOT_CHECKSUM_MISMATCH" | "PLAN_CHECKSUM_MISMATCH" | "STEP_IMPACT_MISMATCH" | "RESULT_LINK_MISMATCH" | "SELECTION_MISMATCH")[]; readonly affectedIdentities: readonly string[]; readonly traversal: "COMPLETE" | "INCOMPLETE" | "CYCLE" }
export interface ResultSelectionCandidate { readonly subjectId: string; readonly result: ConsistencyResult }
export interface ResultSelectionRequest { readonly candidates: readonly ResultSelectionCandidate[]; readonly subjectId: string; readonly eventTimeStart: string; readonly eventTimeEnd: string; readonly policyVersion: string; readonly knowledgeMode: ConsistencyKnowledgeMode; readonly knowledgeTimeCutoff: string; readonly preferredRuleVersion: string | null; readonly supersededResultIds: readonly string[]; readonly createdAt: string }
