import { temporalAlignmentIdentity, temporalOutcomeChecksum } from "./temporalIdentity"
import { canonicalChecksum } from "@/lib/data-platform/contracts"
import type { AvailableTemporalAlignmentInput, NoLookaheadDecision, TemporalAlignmentDiagnostic, TemporalAlignmentInput, TemporalAlignmentOutcome, TemporalAlignmentRequest, TemporalAlignmentStatus, TemporalFailureReason, TemporalRejectedReference } from "./temporalContracts"
export type TemporalFailurePoint="AFTER_INPUT_LOADING"|"AFTER_KNOWLEDGE_FILTER"|"AFTER_EVENT_FILTER"|"AFTER_TIE_BREAK"|"AFTER_SELECTION"|"AFTER_CHECKSUM"
export interface TemporalFaultInjector{readonly fail:(point:TemporalFailurePoint)=>void}
const time=(v:string)=>{if(!v.endsWith("Z"))throw new Error("TEMPORAL_TIMESTAMP_NOT_UTC");const n=Date.parse(v);if(!Number.isFinite(n))throw new Error("TEMPORAL_TIMESTAMP_INVALID");return n}
function point(i:AvailableTemporalAlignmentInput){return time(i.effectiveAt??i.observedAt)}
function refOrder(a:AvailableTemporalAlignmentInput,b:AvailableTemporalAlignmentInput){return a.fact.canonicalRecordId.localeCompare(b.fact.canonicalRecordId)||b.fact.recordVersion-a.fact.recordVersion}
export class TemporalAlignmentRuntime{
 constructor(private readonly faults?:TemporalFaultInjector){}
 align(request:TemporalAlignmentRequest):TemporalAlignmentOutcome{
  request=structuredClone(request)
  this.verifyRun(request);this.faults?.fail("AFTER_INPUT_LOADING");const rejected:TemporalRejectedReference[]=[];const decisions:NoLookaheadDecision[]=[];let available:AvailableTemporalAlignmentInput[]=[]
  for(const input of request.inputs){if(input.availability!=="AVAILABLE"){const reason:TemporalFailureReason=input.availability==="MISSING"?(request.policy.missingBehavior==="BLOCK"?"MISSING":"INAPPLICABLE"):input.availability==="UNSUPPORTED"?(request.policy.unsupportedBehavior==="BLOCK"?"UNSUPPORTED":"INAPPLICABLE"):"INAPPLICABLE";rejected.push({input,reason});continue}if(!request.policy.eligiblePublicationStates.includes(input.publicationState)){rejected.push({input,reason:"INVALID"});continue}const decision=this.knowledge(input,request);decisions.push(decision);if(!decision.eligible){rejected.push({input,reason:decision.reason==="KNOWLEDGE_TIME_UNKNOWN"?"INVALID":"FUTURE_KNOWLEDGE"});continue}available.push(input)}
  this.faults?.fail("AFTER_KNOWLEDGE_FILTER");available=this.selectVersions(available,request);let selected=this.eventSelect(available,request,rejected);this.faults?.fail("AFTER_EVENT_FILTER");selected=[...selected].sort(refOrder);this.faults?.fail("AFTER_TIE_BREAK");this.faults?.fail("AFTER_SELECTION")
  const reasons=Object.freeze([...new Set(rejected.map(x=>x.reason))]);const selectedRoles=new Set(selected.map(input=>input.roleId));const unresolvedFuture=rejected.some(item=>item.reason==="FUTURE_KNOWLEDGE"&&!selectedRoles.has(item.input.roleId));const unresolvedInvalid=rejected.some(item=>item.reason==="INVALID"&&!selectedRoles.has(item.input.roleId));const status:TemporalAlignmentStatus=reasons.includes("MISSING")?"BLOCKED_MISSING_INPUT":reasons.includes("UNSUPPORTED")?"BLOCKED_UNSUPPORTED_INPUT":unresolvedFuture?"BLOCKED_FUTURE_KNOWLEDGE":unresolvedInvalid?"BLOCKED_INVALID_INPUT":selected.length?"MATCHED":reasons.includes("INAPPLICABLE")?"INAPPLICABLE":"NOT_MATCHED"
  const diagnostics=Object.freeze(selected.map(input=>this.diagnostic(input,request)));const alignmentId=temporalAlignmentIdentity(request);const material={alignmentId,mode:request.policy.mode,selectedInputs:Object.freeze(selected),rejectedInputs:Object.freeze(rejected),status,blocking:status.startsWith("BLOCKED_"),reasonCodes:reasons,eventTimeWindow:Object.freeze({...request.eventTimeWindow}),knowledgeTime:Object.freeze({...request.knowledgeTime}),policy:Object.freeze({...request.policy}),noLookaheadDecisions:Object.freeze(decisions),diagnostics,runId:request.runSpecification.runId,runSpecificationChecksum:request.runSpecification.specificationChecksum};const checksum=temporalOutcomeChecksum(material);this.faults?.fail("AFTER_CHECKSUM");return Object.freeze({...material,checksum,createdAt:request.createdAt})
 }
 private verifyRun(r:TemporalAlignmentRequest){const s=r.runSpecification;const start=time(r.eventTimeWindow.start),end=time(r.eventTimeWindow.end);time(r.knowledgeTime.cutoff);if(end<=start)throw new Error("TEMPORAL_EVENT_WINDOW_INVALID");if(s.eventTimeStart!==r.eventTimeWindow.start||s.eventTimeEnd!==r.eventTimeWindow.end||s.knowledgeMode!==r.knowledgeTime.mode||s.knowledgeTimeCutoff!==r.knowledgeTime.cutoff||s.policyBindings.temporalPolicyId!==r.policy.policyId||s.policyBindings.temporalPolicyVersion!==r.policy.policyVersion)throw new Error("RUN_TEMPORAL_BINDING_MISMATCH");if(r.policy.interpolationAllowed||r.policy.forwardFillAllowed)throw new Error("IMPLICIT_TEMPORAL_TRANSFORM_FORBIDDEN");const available=r.inputs.filter((input):input is AvailableTemporalAlignmentInput=>input.availability==="AVAILABLE");if(available.length===r.inputs.length){const material=available.map(input=>({roleId:input.roleId,canonicalRecordId:input.fact.canonicalRecordId,recordVersion:input.fact.recordVersion,checksum:input.checksum})).sort((a,b)=>canonicalChecksum(a).localeCompare(canonicalChecksum(b)));if("cin_"+canonicalChecksum(material)!==s.inputSetIdentity)throw new Error("RUN_INPUT_SET_MISMATCH")}}
 private knowledge(i:AvailableTemporalAlignmentInput,r:TemporalAlignmentRequest):NoLookaheadDecision{if(r.knowledgeTime.mode!=="AS_KNOWN_THEN")return {fact:i.fact,eligible:true,reason:"MODE_PERMITS_LATER_KNOWLEDGE",knowledgeOffsetMs:i.knowledgeAvailableAt?time(i.knowledgeAvailableAt)-time(r.knowledgeTime.cutoff):null};if(!i.knowledgeAvailableAt)return {fact:i.fact,eligible:false,reason:"KNOWLEDGE_TIME_UNKNOWN",knowledgeOffsetMs:null};const offset=time(i.knowledgeAvailableAt)-time(r.knowledgeTime.cutoff);return {fact:i.fact,eligible:offset<=0,reason:offset<=0?"KNOWN_BY_CUTOFF":"FUTURE_KNOWLEDGE",knowledgeOffsetMs:offset}}
 private selectVersions(inputs:AvailableTemporalAlignmentInput[],r:TemporalAlignmentRequest){const groups=new Map<string,AvailableTemporalAlignmentInput[]>();for(const i of inputs){const key=i.roleId+":"+i.fact.canonicalRecordId;const g=groups.get(key)??[];g.push(i);groups.set(key,g)}return [...groups.values()].map(g=>[...g].sort((a,b)=>b.fact.recordVersion-a.fact.recordVersion||refOrder(a,b))[0]!).filter(Boolean)}
 private eventSelect(inputs:AvailableTemporalAlignmentInput[],r:TemporalAlignmentRequest,rejected:TemporalRejectedReference[]){const start=time(r.eventTimeWindow.start),end=time(r.eventTimeWindow.end),target=time(r.targetEventTime??r.eventTimeWindow.end);const reject=(i:AvailableTemporalAlignmentInput,reason:TemporalFailureReason)=>rejected.push({input:i,reason});if(r.policy.mode==="EXACT_TIMESTAMP"){const m=inputs.filter(i=>{const ok=point(i)===target;if(!ok)reject(i,"OUTSIDE_EVENT_WINDOW");return ok});return this.tie(m,r)}if(r.policy.mode==="WINDOW_CONTAINMENT"){return inputs.filter(i=>{const a=i.intervalStart?time(i.intervalStart):point(i),b=i.intervalEnd?time(i.intervalEnd):a;const isPoint=a===b;const ok=a>=start&&(isPoint?(r.policy.boundary==="BOTH_INCLUSIVE"?b<=end:b<end):b<=end);if(!ok)reject(i,"OUTSIDE_EVENT_WINDOW");return ok})}if(r.policy.mode==="INTERVAL_OVERLAP"){return inputs.filter(i=>{if(!i.intervalStart||!i.intervalEnd){reject(i,"INVALID");return false}const a=time(i.intervalStart),b=time(i.intervalEnd),ok=r.policy.boundary==="BOTH_INCLUSIVE"?a<=end&&b>=start:a<end&&b>start;if(!ok)reject(i,"OUTSIDE_EVENT_WINDOW");return ok})}if(r.policy.mode==="EVENT_TO_WINDOW"){const m=inputs.filter(i=>{const t=point(i),ok=t>=start&&(r.policy.boundary==="BOTH_INCLUSIVE"?t<=end:t<end);if(!ok)reject(i,"OUTSIDE_EVENT_WINDOW");return ok});return r.policy.allowMultipleWindowMappings?m:this.tie(m,r)}if(r.policy.mode==="NEAREST_PRIOR"||r.policy.mode==="AS_OF"){const m=inputs.filter(i=>{const d=target-point(i),ok=d>=0&&(r.policy.maximumGapMs===null||d<=r.policy.maximumGapMs);if(!ok)reject(i,d<0?"FUTURE_EVENT":"GAP_EXCEEDED");return ok}).sort((a,b)=>point(b)-point(a)||refOrder(a,b));return m.slice(0,1)}const candidates=inputs.filter(i=>{const d=point(i)-target;if((r.policy.nearestDirection==="PRIOR_ONLY"||r.policy.noLookahead||r.knowledgeTime.mode==="AS_KNOWN_THEN")&&d>0){reject(i,"FUTURE_EVENT");return false}if(r.policy.maximumGapMs!==null&&Math.abs(d)>r.policy.maximumGapMs){reject(i,"GAP_EXCEEDED");return false}return true}).sort((a,b)=>Math.abs(point(a)-target)-Math.abs(point(b)-target)||refOrder(a,b));return candidates.slice(0,1)}
 private tie(inputs:AvailableTemporalAlignmentInput[],r:TemporalAlignmentRequest){return inputs.length<=1?inputs:[[...inputs].sort((a,b)=>r.policy.tieBreak==="HIGHEST_RECORD_VERSION_THEN_LOWEST_ID"?b.fact.recordVersion-a.fact.recordVersion||refOrder(a,b):refOrder(a,b))[0]!].filter(Boolean)}
 private diagnostic(i:AvailableTemporalAlignmentInput,r:TemporalAlignmentRequest):TemporalAlignmentDiagnostic{const target=time(r.targetEventTime??r.eventTimeWindow.end);let overlapStart:null|string=null,overlapEnd:null|string=null,overlapDurationMs:null|number=null;if(i.intervalStart&&i.intervalEnd){const a=Math.max(time(i.intervalStart),time(r.eventTimeWindow.start)),b=Math.min(time(i.intervalEnd),time(r.eventTimeWindow.end));if(b>a){overlapStart=new Date(a).toISOString();overlapEnd=new Date(b).toISOString();overlapDurationMs=b-a}}return Object.freeze({code:"TEMPORAL_SELECTION",roleId:i.roleId,fact:i.fact,temporalOffsetMs:point(i)-target,knowledgeOffsetMs:i.knowledgeAvailableAt?time(i.knowledgeAvailableAt)-time(r.knowledgeTime.cutoff):null,overlapStart,overlapEnd,overlapDurationMs,policy:{policyId:r.policy.policyId,policyVersion:r.policy.policyVersion}})}
}
