import { canonicalChecksum } from "@/lib/data-platform/contracts"
import { verifyMvpProjection, type MvpProjectionKind, type MvpProjectionVersion } from "@/lib/data-platform/evidence-platform"
import type { MvpProjectionExposureDecision } from "@/lib/data-platform/consistency-evidence/postgres"
import type { MvpConsumerProjectionSource } from "@/lib/data-platform/consumer-projections"
import type { MvpServingPostgresClient } from "./client"
import { verifyReplaySnapshot, type MvpServingPublication, type ServingCorpusRecord, type ServingDemoProfile, type ServingEvidenceSummary, type ServingReleaseInventoryItem, type ServingReplaySnapshot } from "./contracts"

export class MvpServingStore {
  constructor(private readonly client: MvpServingPostgresClient) { if (client.roleIntent !== "PUBLISHER") throw new Error("MVP_SERVING_PUBLISHER_REQUIRED") }

  async publish(publication: MvpServingPublication): Promise<"CREATED" | "DUPLICATE"> {
    return this.client.transaction(async (sql) => {
      await sql.unsafe("SELECT pg_advisory_xact_lock(hashtext($1))", [publication.corpus.sourceCorpusId])
      const existing = await sql.unsafe<Array<{ serving_checksum: string }>>("SELECT serving_checksum FROM serving.serving_corpus WHERE corpus_id=$1", [publication.corpus.corpusId])
      if (existing[0]) {
        if (existing[0].serving_checksum !== publication.corpus.servingChecksum) throw new Error("MVP_SERVING_CORPUS_CONFLICT")
        const eventId = `mspu_${canonicalChecksum({ corpusId: publication.corpus.corpusId, eventType: "DUPLICATE" })}`
        await sql.unsafe("INSERT INTO serving.serving_publication_event VALUES($1,$2,'DUPLICATE','VERIFIED',$3,$4,$5::text::jsonb,$6,now()) ON CONFLICT DO NOTHING", [eventId, publication.corpus.corpusId, publication.corpus.sourceCorpusChecksum, publication.corpus.servingChecksum, JSON.stringify(counts(publication)), "EXACT_PUBLICATION_ALREADY_PRESENT"])
        return "DUPLICATE"
      }
      await insertCorpus(sql, publication.corpus)
      for (const value of publication.projections) await insertProjection(sql, publication.corpus, value)
      for (const value of publication.evidenceSummaries) await insertEvidence(sql, publication.corpus, value)
      for (const value of publication.replaySnapshots) await insertReplay(sql, publication.corpus, value)
      for (const value of publication.demoProfiles) await insertProfile(sql, publication.corpus, value)
      for (const value of publication.releaseInventory) await insertInventory(sql, publication.corpus, value)
      const exposureBasis = { corpusId: publication.corpus.corpusId, exposureState: "CONSUMER_VISIBLE", effectiveFrom: publication.corpus.generatedAt, publicationNote: "MVP7A_LOCAL_CERTIFIED_PUBLICATION" }
      const exposureChecksum = canonicalChecksum(exposureBasis), exposureId = `msex_${exposureChecksum}`
      await sql.unsafe("INSERT INTO serving.serving_exposure VALUES($1,$2,'CONSUMER_VISIBLE',$3,$4,$5,$3)", [exposureId, publication.corpus.corpusId, publication.corpus.generatedAt, exposureChecksum, exposureBasis.publicationNote])
      const eventId = `mspu_${canonicalChecksum({ corpusId: publication.corpus.corpusId, eventType: "PUBLISHED" })}`
      await sql.unsafe("INSERT INTO serving.serving_publication_event VALUES($1,$2,'PUBLISHED','ACTIVE',$3,$4,$5::text::jsonb,$6,$7)", [eventId, publication.corpus.corpusId, publication.corpus.sourceCorpusChecksum, publication.corpus.servingChecksum, JSON.stringify(counts(publication)), "ATOMIC_LOCAL_SERVING_CORPUS_ACTIVATION", publication.corpus.generatedAt])
      return "CREATED"
    })
  }
}

export class PostgresMvpServingReadPort {
  constructor(private readonly client: MvpServingPostgresClient) { if (client.roleIntent !== "READER" && client.roleIntent !== "PUBLISHER") throw new Error("MVP_SERVING_READ_ROLE_REQUIRED") }

  async activeCorpus(): Promise<ServingCorpusRecord | null> {
    const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT c.* FROM serving.serving_exposure e JOIN serving.serving_corpus c ON c.corpus_id=e.corpus_id WHERE e.exposure_state='CONSUMER_VISIBLE' ORDER BY e.effective_from DESC,e.exposure_id DESC LIMIT 1")
    return rows[0] ? mapCorpus(rows[0]) : null
  }
  async activeExposure(): Promise<{ readonly exposureId: string; readonly corpusId: string; readonly exposureState: "CONSUMER_VISIBLE"; readonly effectiveFrom: string; readonly checksum: string } | null> {
    const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT * FROM serving.serving_exposure WHERE exposure_state='CONSUMER_VISIBLE' ORDER BY effective_from DESC,exposure_id DESC LIMIT 1")
    const row = rows[0]; return row ? Object.freeze({ exposureId: String(row.exposure_id), corpusId: String(row.corpus_id), exposureState: "CONSUMER_VISIBLE", effectiveFrom: iso(row.effective_from), checksum: String(row.checksum) }) : null
  }
  async projectionByVersion(id: string): Promise<MvpProjectionVersion | null> { const corpus = await this.requireCorpus(); const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT * FROM serving.serving_projection WHERE serving_corpus_id=$1 AND projection_version_id=$2", [corpus.corpusId, id]); return rows[0] ? mapProjection(rows[0]) : null }
  async latestProjection(kind: MvpProjectionKind, subjectId: string): Promise<MvpProjectionVersion | null> { const corpus = await this.requireCorpus(); const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT p.* FROM serving.serving_projection p WHERE p.serving_corpus_id=$1 AND p.projection_kind=$2 AND p.subject_id=$3 AND p.lifecycle='GENERATED' AND p.exposure='READY_FOR_CUTOVER' AND NOT EXISTS (SELECT 1 FROM serving.serving_projection s WHERE s.serving_corpus_id=p.serving_corpus_id AND s.supersedes_projection_version_id=p.projection_version_id) ORDER BY p.event_time_end DESC,p.source_created_at DESC,p.projection_version_id DESC LIMIT 1", [corpus.corpusId, kind, subjectId]); return rows[0] ? mapProjection(rows[0]) : null }
  async listProjections(input: { readonly kind?: MvpProjectionKind; readonly subjectId?: string; readonly start?: string; readonly end?: string; readonly limit: number; readonly offset?: number }): Promise<readonly MvpProjectionVersion[]> { if (!Number.isInteger(input.limit) || input.limit < 1 || input.limit > 100) throw new Error("MVP_SERVING_PROJECTION_LIMIT_INVALID"); const corpus = await this.requireCorpus(); const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT * FROM serving.serving_projection WHERE serving_corpus_id=$1 AND ($2::text IS NULL OR projection_kind=$2) AND ($3::text IS NULL OR subject_id=$3) AND ($4::timestamptz IS NULL OR event_time_start >= $4) AND ($5::timestamptz IS NULL OR event_time_end <= $5) ORDER BY event_time_start,subject_id,projection_version_id LIMIT $6 OFFSET $7", [corpus.corpusId, input.kind ?? null, input.subjectId ?? null, input.start ?? null, input.end ?? null, input.limit, input.offset ?? 0]); return Object.freeze(rows.map(mapProjection)) }
  async evidenceSummary(packetId: string): Promise<ServingEvidenceSummary | null> { const corpus = await this.requireCorpus(); const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT * FROM serving.serving_evidence_summary WHERE serving_corpus_id=$1 AND evidence_packet_id=$2", [corpus.corpusId, packetId]); return rows[0] ? mapEvidence(rows[0]) : null }
  async replaySnapshot(input: { readonly sourceProjectionVersionId?: string; readonly instrument?: string; readonly start?: string; readonly end?: string }): Promise<ServingReplaySnapshot | null> { const corpus = await this.requireCorpus(); const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT * FROM serving.serving_replay_sequence WHERE serving_corpus_id=$1 AND ($2::text IS NULL OR source_projection_version_id=$2) AND ($3::text IS NULL OR instrument=$3) AND ($4::timestamptz IS NULL OR event_time_start=$4) AND ($5::timestamptz IS NULL OR event_time_end=$5) LIMIT 2", [corpus.corpusId, input.sourceProjectionVersionId ?? null, input.instrument ?? null, input.start ?? null, input.end ?? null]); if (rows.length > 1) throw new Error("MVP_SERVING_REPLAY_SNAPSHOT_AMBIGUOUS"); return rows[0] ? mapReplay(rows[0]) : null }
  async demoProfile(role: "PRIMARY" | "BACKUP"): Promise<ServingDemoProfile | null> { const corpus = await this.requireCorpus(); const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT * FROM serving.serving_demo_profile WHERE serving_corpus_id=$1 AND role=$2", [corpus.corpusId, role]); return rows[0] ? mapProfile(rows[0]) : null }
  async releaseInventory(): Promise<readonly ServingReleaseInventoryItem[]> { const corpus = await this.requireCorpus(); const rows = await this.client.sql.unsafe<Record<string, unknown>[]>("SELECT * FROM serving.serving_release_inventory WHERE serving_corpus_id=$1 ORDER BY projection_kind,source_projection_version_id", [corpus.corpusId]); return Object.freeze(rows.map(mapInventory)) }
  async health(): Promise<Record<string, unknown>> { const corpus = await this.activeCorpus(), exposure = await this.activeExposure(); if (!corpus || !exposure) return Object.freeze({ status: "UNHEALTHY", reason: "SERVING_CORPUS_UNAVAILABLE" }); const rows = await this.client.sql.unsafe<Array<{ projections: number; evidence: number; replay: number; profiles: number; inventory: number }>>("SELECT (SELECT count(*)::int FROM serving.serving_projection WHERE serving_corpus_id=$1) projections,(SELECT count(*)::int FROM serving.serving_evidence_summary WHERE serving_corpus_id=$1) evidence,(SELECT count(*)::int FROM serving.serving_replay_sequence WHERE serving_corpus_id=$1) replay,(SELECT count(*)::int FROM serving.serving_demo_profile WHERE serving_corpus_id=$1) profiles,(SELECT count(*)::int FROM serving.serving_release_inventory WHERE serving_corpus_id=$1) inventory", [corpus.corpusId]); const observed = rows[0]!, checksumVerified = observed.projections === corpus.projectionCount && observed.evidence === corpus.evidenceSummaryCount && observed.replay === corpus.replaySnapshotCount && observed.profiles === corpus.demoProfileCount && observed.inventory === corpus.releaseInventoryCount; return Object.freeze({ status: checksumVerified ? "HEALTHY" : "UNHEALTHY", checksumVerified, corpus, exposure, counts: observed }) }
  private async requireCorpus(): Promise<ServingCorpusRecord> { const value = await this.activeCorpus(); if (!value) throw new Error("SERVING_CORPUS_UNAVAILABLE"); return value }
}

export function createServingProjectionSource(port: PostgresMvpServingReadPort, corpus: ServingCorpusRecord): MvpConsumerProjectionSource {
  const exposure: MvpProjectionExposureDecision = Object.freeze({ decisionId: `serving:${corpus.corpusId}`, projectionCorpusId: corpus.corpusId, projectionCorpusChecksum: corpus.servingChecksum, action: "CUTOVER", effectiveExposure: "CONSUMER_VISIBLE", previousDecisionId: null, reasonCode: "SERVING_CORPUS_ACTIVE", actorId: "mvp-serving-publisher", decisionChecksum: canonicalChecksum({ corpusId: corpus.corpusId, checksum: corpus.servingChecksum }), createdAt: corpus.generatedAt })
  return Object.freeze({ latest: port.latestProjection.bind(port), byVersion: port.projectionByVersion.bind(port), list: (input) => port.listProjections(input), exposure: () => Promise.resolve(exposure) })
}

async function insertCorpus(sql: any, c: ServingCorpusRecord) { await sql.unsafe("INSERT INTO serving.serving_corpus VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)", [c.corpusId,c.corpusVersion,c.sourceCorpusId,c.sourceCorpusChecksum,c.servingChecksum,c.schemaVersion,c.generatedAt,c.governedThrough,c.lifecycle,c.exposure,c.projectionCount,c.evidenceSummaryCount,c.replaySnapshotCount,c.demoProfileCount,c.releaseInventoryCount,c.publicationEventCount]) }
async function insertProjection(sql: any, c: ServingCorpusRecord, p: MvpProjectionVersion) { if (!verifyMvpProjection(p)) throw new Error(`SERVING_SOURCE_PROJECTION_CHECKSUM_INVALID:${p.projectionVersionId}`); await sql.unsafe("INSERT INTO serving.serving_projection VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::text::jsonb,$12,$13,$14,$15,$16::text::jsonb,$17,$18,$19,$20,$21,$22,$23,$24)", [p.projectionVersionId,p.projectionId,p.projectionVersionIdentity,p.projectionKind,p.subjectId,p.eventTimeStart,p.eventTimeEnd,p.knowledgeTimeCutoff,p.projectionChecksum,p.dependencyDigest,JSON.stringify(p.dependencies),p.generatorId,p.generatorVersion,p.schemaVersion,c.sourceCorpusId,JSON.stringify(p.structuredPayload),p.completeness,p.limitations,p.lifecycleState,p.consumerExposureState,p.supersedesProjectionVersionId,p.createdAt,c.generatedAt,c.corpusId]) }
async function insertEvidence(sql: any, c: ServingCorpusRecord, e: ServingEvidenceSummary) { await sql.unsafe("INSERT INTO serving.serving_evidence_summary VALUES($1,$2,$3,$4,$5,$6,$7::text::jsonb,$8::text::jsonb,$9::text::jsonb,$10::text::jsonb,$11::text::jsonb,$12::text::jsonb,$13,$14,$15,$16,$17)", [e.evidenceSummaryId,e.evidencePacketId,e.instrument,e.eventTimeStart,e.eventTimeEnd,e.assessmentState,JSON.stringify(e.confidence),JSON.stringify(e.coverage),JSON.stringify(e.verifiedFacts),JSON.stringify(e.interpretation),JSON.stringify(e.supportingEvidence),JSON.stringify(e.counterEvidence),e.sourceLimitations,e.sourceProjectionIdentities,e.summaryChecksum,c.corpusId,c.generatedAt]) }
async function insertReplay(sql: any, c: ServingCorpusRecord, r: ServingReplaySnapshot) { if (!verifyReplaySnapshot(r)) throw new Error(`SERVING_REPLAY_CHECKSUM_INVALID:${r.replaySnapshotId}`); await sql.unsafe("INSERT INTO serving.serving_replay_sequence VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::text::jsonb,$12,$13,$14,$15,$16,$17,$18,$19,$20)", [r.replaySnapshotId,r.snapshotIdentity,r.sourceProjectionVersionId,r.sourceProjectionChecksum,r.sourceDependencyDigest,r.instrument,r.eventTimeStart,r.eventTimeEnd,r.knowledgeTimeCutoff,r.modelVersion,JSON.stringify(r.payload),r.modelChecksum,r.snapshotChecksum,r.priceSampleCount,r.openInterestSampleCount,r.fundingSampleCount,r.flowBucketCount,r.limitations,c.corpusId,c.generatedAt]) }
async function insertProfile(sql: any, c: ServingCorpusRecord, p: ServingDemoProfile) { await sql.unsafe("INSERT INTO serving.serving_demo_profile VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::text::jsonb,$11,$12,$13)", [p.profileId,p.role,p.instrument,p.eventTimeStart,p.eventTimeEnd,p.evidenceIdentity,p.replayIdentity,p.researchIdentity,p.initialCursorTimestamp,JSON.stringify(p.profilePayload),p.profileChecksum,c.corpusId,c.generatedAt]) }
async function insertInventory(sql: any, c: ServingCorpusRecord, i: ServingReleaseInventoryItem) { await sql.unsafe("INSERT INTO serving.serving_release_inventory VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)", [i.inventoryId,i.sourceProjectionVersionId,i.projectionKind,i.subjectId,i.sourceChecksum,i.checksumValid,i.lifecycle,i.exposure,i.supersessionIdentity,i.eligibility,i.disposition,i.dispositionReason,c.corpusId,c.generatedAt]) }
function counts(p: MvpServingPublication) { return { projections:p.projections.length,evidenceSummaries:p.evidenceSummaries.length,replaySnapshots:p.replaySnapshots.length,demoProfiles:p.demoProfiles.length,releaseInventory:p.releaseInventory.length } }
function mapCorpus(r: Record<string, unknown>): ServingCorpusRecord { return Object.freeze({ corpusId:String(r.corpus_id),corpusVersion:String(r.corpus_version),sourceCorpusId:String(r.source_corpus_id),sourceCorpusChecksum:String(r.source_corpus_checksum),servingChecksum:String(r.serving_checksum),schemaVersion:String(r.schema_version) as ServingCorpusRecord["schemaVersion"],generatedAt:iso(r.generated_at),governedThrough:iso(r.governed_through),lifecycle:"PUBLISHED",exposure:"CONSUMER_VISIBLE",projectionCount:Number(r.projection_count),evidenceSummaryCount:Number(r.evidence_summary_count),replaySnapshotCount:Number(r.replay_snapshot_count),demoProfileCount:Number(r.demo_profile_count),releaseInventoryCount:Number(r.release_inventory_count),publicationEventCount:Number(r.publication_event_count) }) }
function mapProjection(r: Record<string, unknown>): MvpProjectionVersion { const value=Object.freeze({projectionId:String(r.projection_id),projectionVersionId:String(r.projection_version_id),projectionVersionIdentity:String(r.projection_version_identity),projectionKind:String(r.projection_kind) as MvpProjectionKind,subjectId:String(r.subject_id),eventTimeStart:iso(r.event_time_start),eventTimeEnd:iso(r.event_time_end),knowledgeTimeCutoff:iso(r.knowledge_time_cutoff),dependencyDigest:String(r.dependency_digest),generatorId:String(r.generator_id) as MvpProjectionVersion["generatorId"],generatorVersion:String(r.generator_version) as MvpProjectionVersion["generatorVersion"],schemaVersion:String(r.schema_version) as "1.0.0",structuredPayload:r.payload as Record<string,unknown>,completeness:String(r.completeness) as MvpProjectionVersion["completeness"],limitations:Object.freeze((r.limitations as string[])??[]),lifecycleState:String(r.lifecycle) as MvpProjectionVersion["lifecycleState"],consumerExposureState:String(r.exposure) as MvpProjectionVersion["consumerExposureState"],supersedesProjectionVersionId:r.supersedes_projection_version_id?String(r.supersedes_projection_version_id):null,dependencies:Object.freeze((r.dependencies as MvpProjectionVersion["dependencies"])??[]),projectionChecksum:String(r.projection_checksum),createdAt:iso(r.source_created_at)}); if(!verifyMvpProjection(value))throw new Error("SERVING_PROJECTION_CHECKSUM_MISMATCH");return value }
function mapEvidence(r: Record<string,unknown>): ServingEvidenceSummary { return Object.freeze({evidenceSummaryId:String(r.evidence_summary_id),evidencePacketId:String(r.evidence_packet_id),instrument:String(r.instrument),eventTimeStart:iso(r.event_time_start),eventTimeEnd:iso(r.event_time_end),assessmentState:String(r.assessment_state),confidence:r.confidence as Record<string,unknown>,coverage:r.coverage as Record<string,unknown>,verifiedFacts:r.verified_facts as Record<string,unknown>,interpretation:r.interpretation as Record<string,unknown>,supportingEvidence:r.supporting_evidence as unknown[],counterEvidence:r.counter_evidence as unknown[],sourceLimitations:Object.freeze((r.source_limitations as string[])??[]),sourceProjectionIdentities:Object.freeze((r.source_projection_identities as string[])??[]),summaryChecksum:String(r.summary_checksum)}) }
function mapReplay(r: Record<string,unknown>): ServingReplaySnapshot { const value=Object.freeze({replaySnapshotId:String(r.replay_snapshot_id),snapshotIdentity:String(r.snapshot_identity),sourceProjectionVersionId:String(r.source_projection_version_id),sourceProjectionChecksum:String(r.source_projection_checksum),sourceDependencyDigest:String(r.source_dependency_digest),instrument:String(r.instrument),eventTimeStart:iso(r.event_time_start),eventTimeEnd:iso(r.event_time_end),knowledgeTimeCutoff:iso(r.knowledge_time_cutoff),modelVersion:String(r.model_version),payload:r.payload as ServingReplaySnapshot["payload"],modelChecksum:String(r.model_checksum),snapshotChecksum:String(r.snapshot_checksum),priceSampleCount:Number(r.price_sample_count),openInterestSampleCount:Number(r.open_interest_sample_count),fundingSampleCount:Number(r.funding_sample_count),flowBucketCount:Number(r.flow_bucket_count),limitations:Object.freeze((r.limitations as string[])??[])});if(!verifyReplaySnapshot(value))throw new Error("REPLAY_SNAPSHOT_CHECKSUM_MISMATCH");return value }
function mapProfile(r: Record<string,unknown>): ServingDemoProfile { return Object.freeze({profileId:String(r.profile_id),role:String(r.role) as "PRIMARY"|"BACKUP",instrument:String(r.instrument),eventTimeStart:iso(r.event_time_start),eventTimeEnd:iso(r.event_time_end),evidenceIdentity:String(r.evidence_identity),replayIdentity:String(r.replay_identity),researchIdentity:String(r.research_identity),initialCursorTimestamp:iso(r.initial_cursor_timestamp),profilePayload:r.profile_payload as Record<string,unknown>,profileChecksum:String(r.profile_checksum)}) }
function mapInventory(r: Record<string,unknown>): ServingReleaseInventoryItem { return Object.freeze({inventoryId:String(r.inventory_id),sourceProjectionVersionId:String(r.source_projection_version_id),projectionKind:String(r.projection_kind),subjectId:String(r.subject_id),sourceChecksum:String(r.source_checksum),checksumValid:Boolean(r.checksum_valid),lifecycle:String(r.lifecycle),exposure:String(r.exposure),supersessionIdentity:r.supersession_identity?String(r.supersession_identity):null,eligibility:String(r.eligibility) as "ELIGIBLE"|"INELIGIBLE",disposition:String(r.disposition) as "INCLUDED"|"EXCLUDED",dispositionReason:String(r.disposition_reason) as ServingReleaseInventoryItem["dispositionReason"]}) }
function iso(value: unknown): string { return new Date(String(value)).toISOString() }
