import type { ProviderRegistration } from "../contracts"

export const PROVIDERS = [
  { providerId: "binance-futures-api", displayName: "Binance Futures API", tier: "A_OFFICIAL_API", certificationStatus: "CERTIFIED_WITH_LIMITATIONS", datasetScope: ["ohlcv", "funding", "open-interest", "liquidation", "agg-trade", "orderbook"], limitations: ["Dataset-specific endpoint retention applies."], registrationVersion: "1.0.0", effectiveAt: "2026-07-12T00:00:00.000Z" },
  { providerId: "binance-public-archive", displayName: "Binance Public Archive", tier: "B_OFFICIAL_ARCHIVE", certificationStatus: "CERTIFIED_WITH_LIMITATIONS", datasetScope: ["ohlcv", "agg-trade"], limitations: ["Archive publication latency varies."], registrationVersion: "1.0.0", effectiveAt: "2026-07-12T00:00:00.000Z" },
  { providerId: "cryptohftdata", displayName: "CryptoHFTData", tier: "C_VERIFIED_PUBLIC", certificationStatus: "CERTIFIED_WITH_LIMITATIONS", datasetScope: ["orderbook"], limitations: ["Full reconstruction requires background processing."], registrationVersion: "1.0.0", effectiveAt: "2026-07-12T00:00:00.000Z" },
  { providerId: "governed-external", displayName: "Governed External Provider", tier: "C_VERIFIED_PUBLIC", certificationStatus: "VALIDATING", datasetScope: ["prediction-market", "etf-flow", "reserve", "macro", "research-document"], limitations: ["Dataset-specific provider certification remains proposed."], registrationVersion: "1.0.0", effectiveAt: "2026-07-12T00:00:00.000Z" },
  { providerId: "fred", displayName: "Federal Reserve Economic Data", tier: "A_OFFICIAL_API", certificationStatus: "VALIDATING", datasetScope: ["macro"], limitations: ["FRED_API_KEY is required; vintage metadata governs Knowledge Time."], registrationVersion: "1.0.0", effectiveAt: "2026-07-15T00:00:00.000Z" },
  { providerId: "alpha-vantage", displayName: "Alpha Vantage", tier: "A_OFFICIAL_API", certificationStatus: "VALIDATING", datasetScope: ["daily-market-context"], limitations: ["Daily context only; licensing and request limits are role-specific."], registrationVersion: "1.0.0", effectiveAt: "2026-07-15T00:00:00.000Z" },
  { providerId: "farside-investors", displayName: "Farside Investors", tier: "C_VERIFIED_PUBLIC", certificationStatus: "CERTIFIED_WITH_LIMITATIONS", datasetScope: ["etf-flow"], limitations: ["Public HTML embedded table; scheduled browser-backed retrieval required because direct server HTTP is edge-rejected.", "Source reports aggregated daily ETF flows in USD millions and disclaims errors or inaccuracies."], registrationVersion: "1.0.0", effectiveAt: "2026-07-15T00:00:00.000Z" },
  { providerId: "internal-canonical", displayName: "QuantTerminal Canonical Processor", tier: "A_OFFICIAL_API", certificationStatus: "CERTIFIED_WITH_LIMITATIONS", datasetScope: ["research-packet", "evidence-packet", "coverage-projection", "derived-market-intelligence", "population-job", "consistency-result"], limitations: ["Certification covers deterministic internal contracts, not analytical correctness."], registrationVersion: "1.0.0", effectiveAt: "2026-07-12T00:00:00.000Z" },
] as const satisfies readonly ProviderRegistration[]
