import { canonicalChecksum } from "@/lib/data-platform/contracts"
import { assembleCoreEvidencePacket,type CoreEvidencePacket,type EvidenceAssemblyConflict,type EvidenceAssemblyOutcome,type EvidenceAssemblyProfile,type EvidenceAssemblyRequest } from "@/lib/data-platform/evidence-platform"
import type postgres from "postgres"
import type { ConsistencyPostgresRuntime } from "./client"

export type EvidenceStoreFailurePoint="AFTER_CANDIDATE_NORMALIZATION"|"AFTER_BUSINESS_IDENTITY"|"AFTER_PACKET_VERSION_IDENTITY"|"AFTER_PACKET_ROW"|"AFTER_SUPPORTING_LINK"|"AFTER_CONFLICTING_LINK"|"AFTER_REQUIREMENT_LINK"|"AFTER_RESULT_REFERENCE"|"AFTER_LINEAGE"|"AFTER_CHECKSUM"|"BEFORE_COMMIT"|"AFTER_COMMIT_UNKNOWN"
export interface EvidenceStoreFaultInjector{readonly fail:(point:EvidenceStoreFailurePoint)=>void}
type Sql=postgres.TransactionSql
const profileChecksum=(profile:EvidenceAssemblyProfile)=>canonicalChecksum(profile)
const conflictId=(identity:string,existing:string,incoming:string)=>"epconf_"+canonicalChecksum({identity,existing,incoming})

export class CoreEvidenceStore{
  constructor(private readonly runtime:ConsistencyPostgresRuntime,private readonly faults?:EvidenceStoreFaultInjector){if(runtime.roleIntent!=="EVIDENCE_ASSEMBLER")throw new Error("EVIDENCE_ASSEMBLER_ROLE_REQUIRED")}
  async assemble(request:EvidenceAssemblyRequest):Promise<EvidenceAssemblyOutcome>{let packet:CoreEvidencePacket;try{packet=assembleCoreEvidencePacket(structuredClone(request));this.faults?.fail("AFTER_CANDIDATE_NORMALIZATION");this.faults?.fail("AFTER_BUSINESS_IDENTITY");this.faults?.fail("AFTER_PACKET_VERSION_IDENTITY")}catch(error){return{status:"REJECTED",reason:error instanceof Error?error.message:"EVIDENCE_ASSEMBLY_INVALID"}}return this.persist(packet,profileChecksum(request.profile),"ASSEMBLY")}
  async writePacket(packet:CoreEvidencePacket,expectedProfileChecksum:string):Promise<EvidenceAssemblyOutcome>{return this.persist(packet,expectedProfileChecksum,"COMMAND")}
  async exists(packetVersionIdentity:string):Promise<{readonly packetVersionId:string;readonly checksum:string}|null>{const rows=await this.runtime.sql.unsafe<{packet_version_id:string;packet_checksum:string}[]>("SELECT packet_version_id,packet_checksum FROM evidence.core_packet_versions WHERE packet_version_identity=$1",[packetVersionIdentity]);return rows[0]?{packetVersionId:rows[0].packet_version_id,checksum:rows[0].packet_checksum}:null}
  async conflicts(packetVersionIdentity:string):Promise<readonly EvidenceAssemblyConflict[]>{const rows=await this.runtime.sql.unsafe<Record<string,unknown>[]>("SELECT * FROM evidence.core_packet_conflicts WHERE packet_version_identity=$1 ORDER BY detected_at,conflict_id",[packetVersionIdentity]);return Object.freeze(rows.map(r=>Object.freeze({conflictId:String(r.conflict_id),packetVersionIdentity:String(r.packet_version_identity),existingPacketVersionId:String(r.existing_packet_version_id),existingChecksum:String(r.existing_checksum),incomingChecksum:String(r.incoming_checksum),detectedAt:new Date(String(r.detected_at)).toISOString(),reasonCode:"IMMUTABLE_PACKET_CONTENT_MISMATCH" as const})))}
  private async persist(packet:CoreEvidencePacket,expectedProfileChecksum:string,kind:"ASSEMBLY"|"COMMAND"):Promise<EvidenceAssemblyOutcome>{let outcome:EvidenceAssemblyOutcome;try{outcome=await this.runtime.transaction(sql=>this.write(sql,packet,expectedProfileChecksum,kind))}catch{return{status:"RETRYABLE_FAILURE",reason:"DATABASE_RETRYABLE"}}try{this.faults?.fail("AFTER_COMMIT_UNKNOWN");return outcome}catch{const found=await this.exists(packet.packetVersionIdentity);return found?.checksum===packet.packetChecksum?{status:"DUPLICATE",packet,reconciledUnknownOutcome:true}:{status:"RETRYABLE_FAILURE",reason:"UNKNOWN_WRITE_OUTCOME_UNRESOLVED"}}}
  private async write(sql:Sql,p:CoreEvidencePacket,expectedProfileChecksum:string,kind:"ASSEMBLY"|"COMMAND"):Promise<EvidenceAssemblyOutcome>{await sql.unsafe("SELECT pg_advisory_xact_lock(hashtext($1))",[p.packetVersionIdentity]);const profile=await sql.unsafe<{definition_checksum:string}[]>("SELECT definition_checksum FROM evidence.core_assembly_profiles WHERE profile_id=$1 AND profile_version=$2",[p.profileId,p.profileVersion]);if(profile[0]?.definition_checksum!==expectedProfileChecksum)return{status:"REJECTED",reason:"EVIDENCE_PROFILE_BINDING_MISMATCH"};const existing=await sql.unsafe<{packet_version_id:string;packet_checksum:string}[]>("SELECT packet_version_id,packet_checksum FROM evidence.core_packet_versions WHERE packet_version_identity=$1",[p.packetVersionIdentity]);if(existing[0]){if(existing[0].packet_checksum===p.packetChecksum)return kind==="ASSEMBLY"?{status:"REUSED",packet:p}:{status:"DUPLICATE",packet:p,reconciledUnknownOutcome:false};const conflict:EvidenceAssemblyConflict=Object.freeze({conflictId:conflictId(p.packetVersionIdentity,existing[0].packet_checksum,p.packetChecksum),packetVersionIdentity:p.packetVersionIdentity,existingPacketVersionId:existing[0].packet_version_id,existingChecksum:existing[0].packet_checksum,incomingChecksum:p.packetChecksum,detectedAt:p.createdAt,reasonCode:"IMMUTABLE_PACKET_CONTENT_MISMATCH"});await sql.unsafe("INSERT INTO evidence.core_packet_conflicts VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING",[conflict.conflictId,conflict.packetVersionIdentity,conflict.existingPacketVersionId,conflict.existingChecksum,conflict.incomingChecksum,conflict.detectedAt,conflict.reasonCode]);return{status:"CONFLICT",conflict,existingPacketVersionId:existing[0].packet_version_id}}
    const identity=await sql.unsafe<{packet_id:string}[]>("SELECT packet_id FROM evidence.core_packet_identities WHERE evidence_business_identity=$1",[p.evidenceBusinessIdentity]);if(identity[0]&&identity[0].packet_id!==p.packetId)return{status:"REJECTED",reason:"EVIDENCE_BUSINESS_IDENTITY_CONFLICT"};await sql.unsafe("INSERT INTO evidence.core_packet_identities VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT DO NOTHING",[p.packetId,p.evidenceBusinessIdentity,p.subject.subjectId,p.subject.subjectType,p.topic,p.timeScope.eventTimeStart,p.timeScope.eventTimeEnd,p.timeScope.knowledgeMode,p.timeScope.knowledgeTimeCutoff,p.profileId,p.profileVersion,p.schemaVersion,p.createdAt])
    for(const c of p.candidates){const found=await sql.unsafe<{candidate_checksum:string}[]>("SELECT candidate_checksum FROM evidence.core_candidates WHERE candidate_identity=$1",[c.candidateIdentity]);if(found[0]&&found[0].candidate_checksum!==c.checksum)return{status:"REJECTED",reason:"EVIDENCE_CANDIDATE_CONFLICT"};await sql.unsafe("INSERT INTO evidence.core_candidates VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23::text::jsonb,$24,$25) ON CONFLICT DO NOTHING",[c.candidateId,c.candidateIdentity,c.checksum,c.subject.subjectId,c.subject.subjectType,c.topic,c.role,c.status,c.resultId,c.resultIdentity,c.resultChecksum,c.ruleId,c.ruleVersion,c.ruleSetId,c.ruleSetVersion,c.resultOutcome,c.resultSeverity,c.timeScope.eventTimeStart,c.timeScope.eventTimeEnd,c.timeScope.knowledgeMode,c.timeScope.knowledgeTimeCutoff,c.dependencySnapshotId,JSON.stringify(c.policyReferences),c.diagnosticCodes,p.createdAt])}
    await sql.unsafe("INSERT INTO evidence.core_packet_versions VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[p.packetVersionId,p.packetVersionIdentity,p.packetId,p.packetChecksum,p.conclusionCode,p.status,p.uncertaintyReasonCodes,p.createdAt]);this.faults?.fail("AFTER_PACKET_ROW")
    for(const c of p.candidates){await sql.unsafe("INSERT INTO evidence.core_packet_candidates VALUES($1,$2,$3)",[p.packetVersionId,c.candidateId,c.role]);if(c.role==="SUPPORTING")this.faults?.fail("AFTER_SUPPORTING_LINK");if(c.role==="CONFLICTING")this.faults?.fail("AFTER_CONFLICTING_LINK");const ref=p.resultReferences.find(r=>r.candidateId===c.candidateId)!;await sql.unsafe("INSERT INTO evidence.core_packet_result_references VALUES($1,$2,$3,$4,$5)",[p.packetVersionId,c.candidateId,c.resultId,c.resultIdentity,ref.checksum]);this.faults?.fail("AFTER_RESULT_REFERENCE");for(const f of c.exactFactReferences)await sql.unsafe("INSERT INTO evidence.core_packet_fact_references VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)",[p.packetVersionId,c.candidateId,f.roleId,f.canonicalRecordId,f.recordVersion,f.datasetId,f.providerId,f.providerSnapshotId,f.effectiveAt,f.observedAt,f.knowledgeAvailableAt,f.publicationState,f.supersessionState,f.checksum,f.lineageNodeId])}
    for(const r of [...p.missingEvidence,...p.unsupportedEvidence,...p.inapplicableEvidence,...p.blockingConditions])await sql.unsafe("INSERT INTO evidence.core_packet_requirements VALUES($1,$2,$3,$4,$5,$6,$7)",[p.packetVersionId,r.requirementId,r.kind,r.datasetId,r.reasonCode,r.policyId,r.policyVersion]);this.faults?.fail("AFTER_REQUIREMENT_LINK")
    for(const l of p.lineageReferences)await sql.unsafe("INSERT INTO evidence.core_packet_lineage VALUES($1,$2,$3,$4,$5,$6)",["eplin_"+canonicalChecksum({packetVersionId:p.packetVersionId,lineageChecksum:l.checksum}),p.packetVersionId,l.lineageType,l.fromId,l.toId,l.checksum]);this.faults?.fail("AFTER_LINEAGE");this.faults?.fail("AFTER_CHECKSUM");this.faults?.fail("BEFORE_COMMIT")
    if(p.status==="BLOCKED")return{status:"BLOCKED",packet:p};if(p.status==="INSUFFICIENT")return{status:"INSUFFICIENT_EVIDENCE",packet:p};if(p.status==="NOT_APPLICABLE")return{status:"NOT_APPLICABLE",packet:p};return{status:"CREATED",packet:p,reconciledUnknownOutcome:false}
  }
}
