import { canonicalChecksum } from "@/lib/data-platform/contracts"
import { createConsistencyRunEventId, isLegalRunLifecycleTransition, isTerminalRunLifecycleState, runEventTypeForState } from "@/lib/data-platform/consistency"
import type { ConsistencyRunRecord, ConsistencyRunCompletionSummary, ConsistencyRunCreateResult, ConsistencyRunEvent, ConsistencyRunLifecycleState, ConsistencyRunSpecification, ConsistencyRunTransitionCommand, ConsistencyRunTransitionResult } from "@/lib/data-platform/consistency"
import type postgres from "postgres"
import type { ConsistencyPostgresRuntime } from "./client"

export type RunStoreFailurePoint = "AFTER_SPECIFICATION" | "AFTER_CREATED_EVENT" | "AFTER_STATE" | "AFTER_TRANSITION_EVENT" | "AFTER_STATE_UPDATE" | "AFTER_SUMMARY"
export interface RunStoreFaultInjector { readonly fail: (point: RunStoreFailurePoint) => void }
type Sql = postgres.Sql | postgres.TransactionSql

function conflictId(runId:string, existing:string,candidate:string){return "crconf_"+canonicalChecksum({runId,existing,candidate})}
function eventChecksum(event: Omit<ConsistencyRunEvent,"eventChecksum">){return canonicalChecksum(event)}
function validateSummary(summary:ConsistencyRunCompletionSummary,state:ConsistencyRunLifecycleState){
  if(summary.runId.trim()===""||summary.terminalState!==state) throw new Error("RUN_SUMMARY_STATE_MISMATCH")
  if(summary.completedRuleCount>summary.requiredRuleCount) throw new Error("RUN_SUMMARY_COUNT_INVALID")
  if(state==="COMPLETED"&&(summary.completedRuleCount!==summary.requiredRuleCount||summary.unresolvedCount||summary.failedEvaluationCount)) throw new Error("RUN_COMPLETION_OBLIGATIONS_UNSATISFIED")
  if(state==="PARTIAL"&&!summary.unresolvedCount&&!summary.failedEvaluationCount) throw new Error("RUN_PARTIAL_OBLIGATION_REQUIRED")
  const checksum=canonicalChecksum({summaryId:summary.summaryId,runId:summary.runId,requiredRuleCount:summary.requiredRuleCount,completedRuleCount:summary.completedRuleCount,consistentResultCount:summary.consistentResultCount,inconsistentResultCount:summary.inconsistentResultCount,blockedResultCount:summary.blockedResultCount,failedEvaluationCount:summary.failedEvaluationCount,unresolvedCount:summary.unresolvedCount,terminalState:summary.terminalState,reasonCodes:summary.reasonCodes})
  if(checksum!==summary.summaryChecksum)throw new Error("RUN_SUMMARY_CHECKSUM_MISMATCH")
}
export class ConsistencyRunStore {
  constructor(private readonly runtime:ConsistencyPostgresRuntime,private readonly faults?:RunStoreFaultInjector){if(runtime.roleIntent!=="CONSISTENCY_WORKER")throw new Error("RUN_COORDINATOR_ROLE_REQUIRED")}
  async create(spec:ConsistencyRunSpecification):Promise<ConsistencyRunCreateResult>{
    return this.runtime.transaction(async sql=>{
      await sql.unsafe("SELECT pg_advisory_xact_lock(hashtext($1))",[spec.runId])
      const existing=await sql.unsafe<{specification_checksum:string}[]>("SELECT specification_checksum FROM consistency.run_specifications WHERE run_id=$1",[spec.runId])
      if(existing[0]){if(existing[0].specification_checksum===spec.specificationChecksum)return {status:"DUPLICATE",run:await this.readWith(sql,spec.runId)};const id=conflictId(spec.runId,existing[0].specification_checksum,spec.specificationChecksum);await sql.unsafe("INSERT INTO consistency.run_creation_conflicts(conflict_id,run_id,existing_checksum,candidate_checksum,detected_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING",[id,spec.runId,existing[0].specification_checksum,spec.specificationChecksum,spec.createdAt]);return {status:"CONFLICT",runId:spec.runId,existingChecksum:existing[0].specification_checksum,candidateChecksum:spec.specificationChecksum,conflictId:id}}
      await sql.unsafe("INSERT INTO consistency.run_specifications VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::text::jsonb,$14,$15,$16,$17,$18,$19)",[spec.runId,spec.ruleSetId,spec.ruleSetVersion,spec.subjectId,spec.eventTimeStart,spec.eventTimeEnd,spec.knowledgeMode,spec.knowledgeTimeCutoff,spec.inputSetIdentity,spec.ruleRegistryChecksum,spec.policyBindings.temporalPolicyId,spec.policyBindings.temporalPolicyVersion,JSON.stringify(spec.policyBindings.comparisonPolicyReferences),spec.policyBindings.severityPolicyId,spec.policyBindings.severityPolicyVersion,spec.policyBindings.retryPolicyReference,spec.executionProfile,spec.specificationChecksum,spec.createdAt])
      this.faults?.fail("AFTER_SPECIFICATION")
      const event=this.createdEvent(spec);await this.insertEvent(sql,event);this.faults?.fail("AFTER_CREATED_EVENT")
      await sql.unsafe("INSERT INTO consistency.run_states(run_id,current_state,last_event_sequence) VALUES($1,'PENDING',1)",[spec.runId]);this.faults?.fail("AFTER_STATE")
      return {status:"CREATED",run:await this.readWith(sql,spec.runId)}
    })
  }
  async transition(command:ConsistencyRunTransitionCommand):Promise<ConsistencyRunTransitionResult>{
    return this.runtime.transaction(async sql=>{
      const states=await sql.unsafe<{current_state:ConsistencyRunLifecycleState;last_event_sequence:number}[]>("SELECT current_state,last_event_sequence FROM consistency.run_states WHERE run_id=$1 FOR UPDATE",[command.runId]);const state=states[0]
      if(!state)return {status:"REJECTED",runId:command.runId,failure:"INPUT_SET_MISSING"}
      const specs=await sql.unsafe<{specification_checksum:string;rule_set_id:string;rule_set_version:string;rule_registry_checksum:string;temporal_policy_id:string;severity_policy_id:string;comparison_policy_references:readonly {policyId:string}[]}[]>("SELECT specification_checksum,rule_set_id,rule_set_version,rule_registry_checksum,temporal_policy_id,severity_policy_id,comparison_policy_references FROM consistency.run_specifications WHERE run_id=$1",[command.runId]);const spec=specs[0]!
      if(spec.specification_checksum!==command.specificationChecksum)return {status:"REJECTED",runId:command.runId,failure:"INPUT_SET_CONFLICT"}
      const type=runEventTypeForState(command.nextState);const eventId=createConsistencyRunEventId({commandId:command.commandId,runId:command.runId,eventType:type,previousState:state.current_state,nextState:command.nextState,specificationChecksum:command.specificationChecksum})
      const prior=await sql.unsafe<{event_id:string}[]>("SELECT event_id FROM consistency.run_events WHERE event_id=$1",[eventId]);if(prior[0])return {status:"DUPLICATE",run:await this.readWith(sql,command.runId),event:await this.readEvent(sql,eventId)}
      if(!isLegalRunLifecycleTransition(state.current_state,command.nextState))return {status:"REJECTED",runId:command.runId,failure:"ILLEGAL_TRANSITION"}
      if(command.nextState==="RUNNING"){const available=await sql.unsafe<{ok:boolean}[]>("SELECT EXISTS(SELECT 1 FROM consistency.rule_sets rs JOIN control.policy_versions pv ON pv.policy_version_id=rs.policy_version_id WHERE rs.rule_set_id=$1 AND rs.rule_set_version=$2 AND rs.definition_checksum=$3 AND rs.state='APPROVED') ok",[spec.rule_set_id,spec.rule_set_version,spec.rule_registry_checksum]);if(!available[0]?.ok)return {status:"REJECTED",runId:command.runId,failure:"REGISTRY_CHECKSUM_MISMATCH"};const policyIds=[spec.temporal_policy_id,spec.severity_policy_id,...spec.comparison_policy_references.map(item=>item.policyId)];const policies=await sql.unsafe<{count:number}[]>("SELECT count(DISTINCT policy_version_id)::int count FROM control.policy_versions WHERE policy_version_id=ANY($1)",[policyIds]);if(policies[0]?.count!==new Set(policyIds).size)return {status:"REJECTED",runId:command.runId,failure:"POLICY_BINDING_MISSING"}}
      if(["COMPLETED","PARTIAL","FAILED"].includes(command.nextState)){if(!command.completionSummary)return {status:"REJECTED",runId:command.runId,failure:"ILLEGAL_TRANSITION"};validateSummary(command.completionSummary,command.nextState)}
      if((command.nextState==="CANCELLED"||command.nextState==="EXPIRED")&&!command.reasonCodes.length)return {status:"REJECTED",runId:command.runId,failure:command.nextState==="CANCELLED"?"EXECUTION_CANCELLED":"EXECUTION_EXPIRED"}
      const event=this.transitionEvent(command,state.current_state,state.last_event_sequence+1,eventId);await this.insertEvent(sql,event);this.faults?.fail("AFTER_TRANSITION_EVENT")
      if(command.completionSummary){await this.insertSummary(sql,command.completionSummary);this.faults?.fail("AFTER_SUMMARY")}
      await sql.unsafe("UPDATE consistency.run_states SET current_state=$2,last_event_sequence=$3,started_at=CASE WHEN $2='RUNNING' THEN $4 ELSE started_at END,terminal_at=CASE WHEN $5 THEN $4 ELSE NULL END,completion_summary_id=$6 WHERE run_id=$1",[command.runId,command.nextState,event.eventSequence,command.occurredAt,isTerminalRunLifecycleState(command.nextState),command.completionSummary?.summaryId??null]);this.faults?.fail("AFTER_STATE_UPDATE")
      return {status:"TRANSITIONED",run:await this.readWith(sql,command.runId),event}
    })
  }
  async read(runId:string){return this.readWith(this.runtime.sql,runId)}
  async events(runId:string){const rows=await this.runtime.sql.unsafe("SELECT * FROM consistency.run_events WHERE run_id=$1 ORDER BY event_sequence",[runId]);return Object.freeze(rows.map(row=>this.mapEvent(row as Record<string,unknown>)))}
  private createdEvent(spec:ConsistencyRunSpecification):ConsistencyRunEvent{const base={eventId:createConsistencyRunEventId({commandId:"CREATE:"+spec.specificationChecksum,runId:spec.runId,eventType:"RUN_CREATED",previousState:null,nextState:"PENDING",specificationChecksum:spec.specificationChecksum}),runId:spec.runId,attemptId:null,eventSequence:1,eventType:"RUN_CREATED" as const,previousState:null,nextState:"PENDING" as const,actorType:"COORDINATOR" as const,actorId:"RUN_CREATOR",occurredAt:spec.createdAt,policyVersionReferences:Object.freeze([spec.policyBindings.temporalPolicyVersion,spec.policyBindings.severityPolicyVersion]),reasonCodes:Object.freeze([]),details:Object.freeze([])};return Object.freeze({...base,eventChecksum:eventChecksum(base)})}
  private transitionEvent(c:ConsistencyRunTransitionCommand,previousState:ConsistencyRunLifecycleState,eventSequence:number,eventId:string):ConsistencyRunEvent{const base={eventId,runId:c.runId,attemptId:null,eventSequence,eventType:runEventTypeForState(c.nextState),previousState,nextState:c.nextState,actorType:c.actorType,actorId:c.actorId,occurredAt:c.occurredAt,policyVersionReferences:Object.freeze([...c.policyVersionReferences]),reasonCodes:Object.freeze([...c.reasonCodes]),details:Object.freeze([...c.details])};return Object.freeze({...base,eventChecksum:eventChecksum(base)})}
  private async insertEvent(sql:Sql,e:ConsistencyRunEvent){await sql.unsafe("INSERT INTO consistency.run_events VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::text::jsonb,$13)",[e.eventId,e.runId,e.eventSequence,e.eventType,e.previousState,e.nextState,e.actorType,e.actorId,e.occurredAt,e.policyVersionReferences,e.reasonCodes,JSON.stringify(e.details),e.eventChecksum])}
  private async insertSummary(sql:Sql,s:ConsistencyRunCompletionSummary){await sql.unsafe("INSERT INTO consistency.run_completion_summaries VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)",[s.summaryId,s.runId,s.requiredRuleCount,s.completedRuleCount,s.consistentResultCount,s.inconsistentResultCount,s.blockedResultCount,s.failedEvaluationCount,s.unresolvedCount,s.terminalState,s.reasonCodes,s.summaryChecksum])}
  private async readWith(sql:Sql,runId:string):Promise<ConsistencyRunRecord>{const rows=await sql.unsafe<Record<string,unknown>[]>("SELECT s.*,st.current_state,st.last_event_sequence,st.started_at,st.terminal_at,cs.* FROM consistency.run_specifications s JOIN consistency.run_states st USING(run_id) LEFT JOIN consistency.run_completion_summaries cs ON cs.summary_id=st.completion_summary_id WHERE s.run_id=$1",[runId]);if(!rows[0])throw new Error("RUN_NOT_FOUND");const r=rows[0];const policyBindings={temporalPolicyId:String(r.temporal_policy_id),temporalPolicyVersion:String(r.temporal_policy_version),comparisonPolicyReferences:r.comparison_policy_references as ConsistencyRunSpecification["policyBindings"]["comparisonPolicyReferences"],severityPolicyId:String(r.severity_policy_id),severityPolicyVersion:String(r.severity_policy_version),retryPolicyReference:r.retry_policy_reference===null?null:String(r.retry_policy_reference)};const specification={runId:String(r.run_id),ruleSetId:String(r.rule_set_id),ruleSetVersion:String(r.rule_set_version),subjectId:String(r.subject_id),eventTimeStart:new Date(String(r.event_time_start)).toISOString(),eventTimeEnd:new Date(String(r.event_time_end)).toISOString(),knowledgeMode:r.knowledge_mode as ConsistencyRunSpecification["knowledgeMode"],knowledgeTimeCutoff:new Date(String(r.knowledge_time_cutoff)).toISOString(),inputSetIdentity:String(r.input_set_identity),ruleRegistryChecksum:String(r.rule_registry_checksum),policyBindings,executionProfile:String(r.execution_profile),specificationChecksum:String(r.specification_checksum),createdAt:new Date(String(r.created_at)).toISOString()};return Object.freeze({specification:Object.freeze(specification),currentState:r.current_state as ConsistencyRunLifecycleState,lastEventSequence:Number(r.last_event_sequence),startedAt:r.started_at?new Date(String(r.started_at)).toISOString():null,terminalAt:r.terminal_at?new Date(String(r.terminal_at)).toISOString():null,completionSummary:r.summary_id?this.mapSummary(r):null})}
  private async readEvent(sql:Sql,id:string){const rows=await sql.unsafe<Record<string,unknown>[]>("SELECT * FROM consistency.run_events WHERE event_id=$1",[id]);return this.mapEvent(rows[0]!)}
  private mapEvent(r:Record<string,unknown>):ConsistencyRunEvent{return Object.freeze({eventId:String(r.event_id),runId:String(r.run_id),attemptId:null,eventSequence:Number(r.event_sequence),eventType:r.event_type as ConsistencyRunEvent["eventType"],previousState:r.previous_state as ConsistencyRunLifecycleState|null,nextState:r.next_state as ConsistencyRunLifecycleState,actorType:r.actor_type as ConsistencyRunEvent["actorType"],actorId:String(r.actor_id),occurredAt:new Date(String(r.occurred_at)).toISOString(),policyVersionReferences:Object.freeze(r.policy_version_references as string[]),reasonCodes:Object.freeze(r.reason_codes as string[]),details:Object.freeze(r.bounded_details as ConsistencyRunEvent["details"]),eventChecksum:String(r.event_checksum)})}
  private mapSummary(r:Record<string,unknown>):ConsistencyRunCompletionSummary{return Object.freeze({summaryId:String(r.summary_id),runId:String(r.run_id),requiredRuleCount:Number(r.required_rule_count),completedRuleCount:Number(r.completed_rule_count),consistentResultCount:Number(r.consistent_result_count),inconsistentResultCount:Number(r.inconsistent_result_count),blockedResultCount:Number(r.blocked_result_count),failedEvaluationCount:Number(r.failed_evaluation_count),unresolvedCount:Number(r.unresolved_count),terminalState:r.terminal_state as ConsistencyRunCompletionSummary["terminalState"],reasonCodes:Object.freeze(r.reason_codes as string[]),summaryChecksum:String(r.summary_checksum)})}
}
